### ISSUE TITLE
Breadcrumbs (design update & new variant)

### ISSUE THREAD

**Issue by NateBaldwinDesign** [adobe/spectrum-css#102]
### Overview
Implement design updates to Breadcrumb component. Updates include:
- Additional Variant ("Compact")
- Renaming of "Title" variant to "Multiline"
- Hierarchy truncation (into a dropdown)
- Additional state for Drag-and-Drop

Redlines & DNA tokens are in staging, Documentation in progress.

###### Default
![default](https://user-images.githubusercontent.com/13972198/53124110-d2488a00-3517-11e9-8a0a-d41c1737b034.png)

###### Compact
![compact](https://user-images.githubusercontent.com/13972198/53124109-d2488a00-3517-11e9-9821-89d18dccfddf.png)

###### Multiline
![multiline](https://user-images.githubusercontent.com/13972198/53124111-d2488a00-3517-11e9-83f7-c907da49e891.png)

###### Truncation (with option: Root Context)
![with_root_context](https://user-images.githubusercontent.com/13972198/53124112-d2488a00-3517-11e9-8edb-42958d92413a.png)

**Comment by lazd** [comment]
For the last item, we need to use an actual `h3` or `h4` and make sure styles are reset.

**Comment by lazd** [comment]
Need the new icon with the little dropdown.
