### ISSUE TITLE
Color wheel variables for width (and height) should exist in the output

### ISSUE THREAD

**Issue by mischnic** [adobe/spectrum-css#1032]
## Description

These variables cannot be overwritten at runtime because they are stripped out during the build process:

https://github.com/adobe/spectrum-css/blob/8e6fade0bfee690d8d9a0b2d94a63884eeba4d2f/components/colorwheel/index.css#L5-L6

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/colorwheel.html
2. Take a look at `width` and `height` of `.spectrum-ColorWheel`. These should be 
`width: var(--spectrum-colorwheel-width, calc(var(--spectrum-global-dimension-size-125) * 16));`
and not
`width: calc(var(--spectrum-global-dimension-size-125) * 16);`

**Comment by lazd** [comment]
`--spectrum-colorwheel-width` and `--spectrum-colorwheel-height` are now available in output, merged in `main` but not released yet.
