### ISSUE TITLE
[Accordion] Item hight not using a controlled CSS Custom Property

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1033]
## Description
There is an uncontrolled unit of measure used to calculate the height of the Accordion Header that ends up having the same value for `medium` and `large` themes. This is indicated in the below CSS samples and in the `dist/vars.css` file which lists the value as `40px` rather than a derivative of a system wide custom property:

```
.spectrum-Accordion-itemIndicator {
    top: calc(
        (
                var(--spectrum-accordion-item-height, 40px) -
                    var(
                        --spectrum-accordion-item-border-size,
                        var(--spectrum-alias-border-size-thin)
                    )
            ) / 2 -
            var(
                --spectrum-accordion-icon-height,
                var(--spectrum-global-dimension-size-125)
            ) / 2
    );
}

 .spectrum-Accordion-itemHeading {
    height: var(--spectrum-accordion-item-height, 40px);
}

.spectrum-Accordion-itemHeader {
    min-height: calc(
        var(--spectrum-accordion-item-height, 40px) -
            var(
                --spectrum-accordion-item-border-size,
                var(--spectrum-alias-border-size-thin)
            )
    );
}

 .spectrum-Accordion-item.is-open>.spectrum-Accordion-itemHeader:after {
    height: calc(
        var(--spectrum-accordion-item-height, 40px) -
            var(
                --spectrum-accordion-item-border-size,
                var(--spectrum-alias-border-size-thin)
            )
    );
}
```

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/accordion.html
2. Choose the "Large" size
3. Observe how hovering on an Accordion Item causes the hover styling to bleed past the standard styling.

## Expected behavior
A controlled variable ensures correct delivery across all scales and color sets.

## Screenshots
![image](https://user-images.githubusercontent.com/1156657/95005353-45a3f000-05c5-11eb-891c-a73b5efe3d15.png)
![image](https://user-images.githubusercontent.com/1156657/95005356-4dfc2b00-05c5-11eb-88b3-8688c14c7e4a.png)

## Environment
 - **Spectrum CSS version:** Latest beta
 - **Browser(s) and OS(s):** observed on Chrome, macOS: though all environments are likely here.

**Comment by Westbrook** [comment]
Upon closer review, this issue could also be avoided by not relying on this value all together and leveraging the following styles instead:
```
.spectrum-Accordion-itemIndicator {
    top: calc(
                50% -
            var(
                --spectrum-accordion-icon-height,
                var(--spectrum-global-dimension-size-125)
            ) / 2
    );
}

.spectrum-Accordion-itemHeading {
    height: auto;
    position: relative;
}

.spectrum-Accordion-itemHeader {
    min-height: calc(
        100% -
            var(
                --spectrum-accordion-item-border-size,
                var(--spectrum-alias-border-size-thin)
            )
    );
}

 .spectrum-Accordion-item.is-open>.spectrum-Accordion-itemHeader:after {
    height: calc(
        100% -
            var(
                --spectrum-accordion-item-border-size,
                var(--spectrum-alias-border-size-thin)
            )
    );
}
```

**Comment by lazd** [comment]
If that fixes the alignment of the icon, I'd accept a PR!
