### ISSUE TITLE
[Checkbox|Radio] Mismatch in "fill" styling

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1035]
## Description
Unclear whether this is intended or not, but I was surprised to see the fill styling of the radio and the checkbox patterns diverge:

![image](https://user-images.githubusercontent.com/1156657/95087163-5781b200-06ef-11eb-9288-7049a36a0b1e.png)
![image](https://user-images.githubusercontent.com/1156657/95087181-610b1a00-06ef-11eb-9d4a-79fd7e82f5cd.png)

Is this to be expected, or is this something that will wash out of later beta releases?

https://opensource.adobe.com/spectrum-css/checkbox.html
https://opensource.adobe.com/spectrum-css/radio.html

**Comment by lazd** [comment]
Looks like this is due to https://github.com/adobe/spectrum-css/issues/349

**Comment by Westbrook** [comment]
That looks like the ticket. Thanks!

Feel free to close as duplicate as you'd prefer.

**Comment by lazd** [comment]
Closing in favor of #349, new PR #1057 will address this issue. Thanks!
