### ISSUE TITLE
Action Group should support ActionButton of size other than M

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#1036]
## Description

Currently, Action Group has a number of overrides for border-width and border-radius that use the medium Action Button variables. Either this needs to be done in a size-agnostic way, or we need to add t-shirt sizing to the Action Group itself

## Why do you need this feature or component?

Full support for t-shirt sizing.

## Additional context

Discovered implementing #936

**Comment by pfulton** [comment]
With the migration to `@adobe/spectrum-tokens`, ActionGroup now has t-shirt sizing.
