### ISSUE TITLE
color components do not work correctly in Windows High Contrast mode

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-css#1037]
## Description
Color components are not useful in Windows High Contrast mode

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/colorarea.html
2. Turn on Windows High Contrast mode
3. Observe that the color areas are not useful

## Expected behavior
Color pickers should be useful, disabled color pickers should use the disabled color

## Screenshots
![Color Handle - Spectrum CSS - Profile 1 - Microsoft​ Edge 10_5_2020 1_43_02 PM](https://user-images.githubusercontent.com/1724479/95130137-f9fe5d00-0710-11eb-8e9a-e65b19f0ee9c.png)
![Color Handle - Spectrum CSS - Profile 1 - Microsoft​ Edge 10_5_2020 1_42_50 PM](https://user-images.githubusercontent.com/1724479/95130143-fbc82080-0710-11eb-9b6a-111e37a332fa.png)
![Color Handle - Spectrum CSS - Profile 1 - Microsoft​ Edge 10_5_2020 1_42_35 PM](https://user-images.githubusercontent.com/1724479/95130146-fc60b700-0710-11eb-9776-bcaa988e9697.png)

## Environment
 - **Spectrum CSS version:** 2.13.0
 - **Browser(s) and OS(s):** Edge 85.0 on Windows 10

**Comment by pfulton** [comment]
Closing, as all of our Color-* components have been migrated to use `@adobe/spectrum-tokens` and have accounted for high-contrast mode during that migration work.

The only outstanding migration that needs to be completed is for [ColorSlider](https://jira.corp.adobe.com/browse/CSS-188). Once that work is merged and released, it will also support high-contrast mode.
