### ISSUE TITLE
[ActionBar] Popover padding not content direction managed

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1042]
## Description
Currently, the Popover inside of an ActionBar gets unbalanced padding:
```
.spectrum-ActionBar-popover {
  // ...
  padding: 0 calc(var(--spectrum-global-dimension-size-200) / 2) 0 var(--spectrum-global-dimension-size-200);
  // ...
}
```
Which means that it doesn't deliver with the same intention in a right to left content layout.

It's likely that this just needs a:
```
[dir=ltr] .spectrum-ActionBar-popover {
  // ...
  padding: 0 calc(var(--spectrum-global-dimension-size-200) / 2) 0 var(--spectrum-global-dimension-size-200);
  // ...
}

[dir=rtl] .spectrum-ActionBar-popover {
  // ...
  padding: 0 var(--spectrum-global-dimension-size-200) 0 calc(var(--spectrum-global-dimension-size-200) / 2);
  // ...
}
```
If you agree, I can pop in a PR.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/actionbar.html
2. Click on "Right to Left" direction
3. Observe the left/right padding of the ActionBar not switching.

## Expected behavior
The padding balance swaps with the content direction.

## Screenshots

![image](https://user-images.githubusercontent.com/1156657/95283445-dc70e680-0829-11eb-9e9e-a8747b93ae8c.png)

**Comment by jianliao** [comment]
Hi @Westbrook, 
Good catch for RTL. Your fix looks good to me, please create the PR. Thanks
