### ISSUE TITLE
[Menu] Icons in "large" menu-item elements are positioned too high

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1047]
## Description
Icons in large menu icon elements are positioned too high.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/menu.html
2. Click on "Large" scale
3. Observe the icons in https://opensource.adobe.com/spectrum-css/menu.html#standard that the icons are not centered vertically with the text.

## Expected behavior
Should be vertically aligned with the first line of text.

## Screenshots
![image](https://user-images.githubusercontent.com/1156657/95402583-156a9300-08de-11eb-8c09-69446ab1c3ec.png)

## Environment
 - **Spectrum CSS version:** Latest
 - **Browser(s) and OS(s):** Chrome and macOS

**Comment by castastrophe** [comment]
@Westbrook I wanted to check in and see if, in the latest updates, you are still having this issue? https://opensource.adobe.com/spectrum-css/menu.html#sizingwithicons

If you approve, I'll close out this issue.

**Comment by Westbrook** [comment]
Seems fixed by time and space. Thanks!
