### ISSUE TITLE
[FieldGroup] Horizontal variant doesn't control for content direction.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1050]
## Description
The following CSS doesn't control for content direction:
https://github.com/adobe/spectrum-css/blob/8e6fade0bfee690d8d9a0b2d94a63884eeba4d2f/components/fieldgroup/index.css#L25-L29

Seems like the fix is to move to logical properties in the source. If there is no alternative path already being pursued, I can submit a PR.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/fieldgroup.html
2. Click on content direction = RTL
3. Observe the collapse of margin between the field items.

## Expected behavior
Has reciprocal margin based on direction.

## Screenshots
![image](https://user-images.githubusercontent.com/1156657/95859949-5bd04f80-0d2d-11eb-841b-b7daa6a710af.png)

## Environment
 - **Spectrum CSS version:** Latest
 - **Browser(s) and OS(s):** Chrome on macOS

**Comment by Westbrook** [comment]
Also, while I'm here, it looks like the usage of `margin-inline-start` on items after the first will cause unexpected wrapping behavior (note the lack of start [left] edge alignment):
![image](https://user-images.githubusercontent.com/1156657/95863617-693c0880-0d32-11eb-81cd-b1d5405bd7a5.png)
If this is indeed unexpected, should I use `margin-inline-end` on all but the last child to avoid this?

**Comment by Westbrook** [comment]
Another question:

The styles here are applied via `.spectrum-FieldGroup--horizontal` or (though also and if a user is mistaken) `.spectrum-FieldGroup--horizontal`. Should one of these be the "default" and the other be the modifier? Based on the styles applied to `.spectrum-FieldGroup`, `.spectrum-FieldGroup--horizontal` is _almost_ the default as it is. Is there reason why the default here doesn't supply margin?

**Comment by snowystinger** [comment]
We've been slowly moving components to logical properties in React Spectrum, https://react-spectrum.adobe.com/react-spectrum/CheckboxGroup.html these changes are making their way into Spectrum-CSS.

I think I'd actually argue against putting a margin on anything and leave that to container components. Margin's affect things outside of the component, which isn't great for reusability. This is why we now have Flex/Grid components in React Spectrum, to make this kind of thing easier and more predictable, and they accept standard Spectrum sizes using the native gap property (kinda polyfilled for flex).
https://react-spectrum.adobe.com/react-spectrum/Flex.html
In other cases, such as the Checkboxes, we actually switched to padding. This way the size is still dependable.

**Comment by lazd** [comment]
> The styles here are applied via `.spectrum-FieldGroup--horizontal` or (though also and if a user is mistaken) `.spectrum-FieldGroup--horizontal`. Should one of these be the "default" and the other be the modifier? Based on the styles applied to `.spectrum-FieldGroup`, `.spectrum-FieldGroup--horizontal` is _almost_ the default as it is. Is there reason why the default here doesn't supply margin?

We're starting to avoid defaults, and instead are making it so you must add classes for all variants you want to apply. This makes it so we don't have to override default values in variant classes, cleaning up the CSS and making things simpler to generate.

**Comment by lazd** [comment]
> If this is indeed unexpected, should I use `margin-inline-end` on all but the last child to avoid this?

That's a good solution, we should probably go that direction instead.

**Comment by lazd** [comment]
> In other cases, such as the Checkboxes, we actually switched to padding. This way the size is still dependable.

Applying padding to a Checkbox in checkbox groups will increase its hit area, and we actually want dead space between them in a group, so we should be using margin. Unless I'm misunderstanding?

**Comment by snowystinger** [comment]
Ah, if we want dead space in there, we should probably move our checkbox group to be in a Flex. Not what we currently have. I'll make an issue on our side if that's the case.
I just tried it out though, is it actually dead space or should that "empty" space be part of the hit area for the next checkbox (in horizontal) because that's how it currently works. The order of dom elements places each sequential checkbox above the previous one when receiving interaction events.
