### ISSUE TITLE
[Card] subtitle style incorrectly uses `text-transform: uppercase;`

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-css#1054]
## Description
The subtitle isn't all-uppercase in the spectrum design examples https://spectrum.adobe.com/page/cards/

## Steps to reproduce
1. Go to http://opensource.adobe.com/spectrum-css/card
2. Inspect the subtitle in the examples, and you'll see "text-transform: uppercase;"

## Expected behavior
We shouldn't transform to uppercase. In general this is a really bad pattern to use for some languages as well, so it's not something we should use css to enforce.

**Comment by lazd** [comment]
Looks like a design change, we should fix it. Also good call on the issue with other languages.
