### ISSUE TITLE
Update to DNA v6.0.0-beta.26

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#1058]
## Description

There are likely to be broken components as a result and bugs in DNA we will find in the process of upgrading.

This issue will include assessing the broken components through VRT and getting Spectrum CSS back to at least a place of stable builds before integrating all the new features and changes in beta.26.

## Why do you need this feature or component?

Stay in sync with the latest release of DNA

synced to jira: https://jira.corp.adobe.com/browse/SDS-7687

**Comment by lazd** [comment]
This one's done!
