### ISSUE TITLE
Add additional documentation for tick with labels for Slider

### ISSUE THREAD

**Issue by bernhard-adobe** [adobe/spectrum-css#1060]
## Description
We may have to update some of our documentation for tick with labels for the slider component. 
There are cases where long labels need to be dropped depending on the text-width and space left between the labels.

The logic for showing / dropping labels will be done via JavaScript but we should maybe still hard-code 3-4 examples how things might look like in the specified scenarios. Hardcoding this for class-names and YAML-HTML.

@badimon provides us with the following rulesets:

![Rules](https://user-images.githubusercontent.com/52184321/96638110-834a8d80-12d4-11eb-9bb7-3866e61541c2.png)

## Link to documentation
https://opensource.adobe.com/spectrum-css/slider.html#tickwithlabels

## Additional context
We may have to reach out to @badimon in case we have more quesitons.

**Comment by castastrophe** [comment]
Going to close this out as we are migrating to Storybook and the design documentation does exist as a source of reference; please feel free to reopen if you feel this has not yet been addressed!
