### ISSUE TITLE
Set font-family on Button based on 'lang' attribute

### ISSUE THREAD

**Issue by ktabors** [adobe/spectrum-css#1062]
## Description
When a spectrum-css user sets a `lang` attribute it changes the `font-family` in `:root`, which is great. The following components set the '`font-family` on themselves, not inherit, to avoid unexpected fonts in weird contexts,' accordion, button, checkbox, commons, menu, radio, textfield, and typography. This causes issues because the button family is more specific than what is set at `:root`via `lang`.

Possible solution is for these components, 'feature request to set font-family correctly on Button and friends when [lang] is set.'

## Additional context

Buttons setting font family https://github.com/adobe/spectrum-css/blob/main/components/button/index.css#L63
Font family set in `:root` https://github.com/adobe/spectrum-css/blob/main/components/commons/fonts.css

![spectrum button](https://user-images.githubusercontent.com/309540/96791857-15729480-13ae-11eb-962a-b34b140b7969.png)

### Associated Issues
https://github.com/adobe/react-spectrum/issues/1094

**Comment by ktabors** [comment]
I'm looking back at the original conversation in Slack and I'm not seeing guidance on how to fix this. Is there availability to suggest a fix or work on this?

**Comment by castastrophe** [comment]
Font-family is no longer set on button at all and it instead inherits the appropriate font-family; closing this out but please reopen if you feel this has not been addressed.
