### ISSUE TITLE
Progress bar width cannot be customized

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#1064]
## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/meter.html
2. Drop to console
3. Run `document.querySelector('.spectrum-ProgressBar').style.width = '400px'`
4. Note that the progress bar does not get bigger

![image](https://user-images.githubusercontent.com/201344/97244478-0dec2a80-17b6-11eb-9711-4a6ddef2b03f.png)

## Expected behavior

Progress bar fills container.

Run `document.querySelector('.spectrum-ProgressBar-track').style.width = '100%'` to see expected behavior.
![image](https://user-images.githubusercontent.com/201344/97244491-15133880-17b6-11eb-8900-f1104f1394fa.png)

## Environment
 - **Spectrum CSS version:** 	@spectrum-css/progressbar@1.0.0-beta.2
 - **Browser(s) and OS(s):** Chrome

**Comment by snowystinger** [comment]
I noticed this is setup as a flex row wrap, would it make more sense to move this to grid?
```
|label-------|value|
|------meter-------|
```

**Comment by lazd** [comment]
Perhaps, but it works as-is with the workaround posted, so we'll probably do that in the meantime unless there are bugs we don't know about with the current implementation.
