### ISSUE TITLE
Fix VRT issues surfaced with DNA v6.0.0-beta.27

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#1065]
## Description
Updating CSS to the latest version of Spectrum Tokens (DNA) caused a bunch of VRT errors.

We need to work through and potentially split them into individual issues.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css-vr-results/vrt-156e705-2020-11-02_21-09-00/html_report/

## Expected behavior
no errors, but getting lots.

## Additional context

All the work has been done in this PR #1063

**Comment by lazd** [comment]
Done deal. Thanks everyone!
