### ISSUE TITLE
Table Column Headers do not match Spectrum DNA's style

### ISSUE THREAD

**Issue by matthewdeutsch** [adobe/spectrum-css#1067]
## Description
Table Column Headers do not match Spectrum DNA's style

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/table.html
3. Observe table column header

## Expected behavior
Style should match spectrum dna's

## Screenshots
Left: [spectrum css](https://opensource.adobe.com/spectrum-css/table.html)
Right: [spectrum dna](https://spectrum.corp.adobe.com/page/table/)
![image](https://user-images.githubusercontent.com/700930/98053668-13292500-1e07-11eb-98c2-6bd28a348ed8.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** 

## Additional context
Tracking ticket - https://jira.corp.adobe.com/browse/CJM-4503

**Comment by pfulton** [comment]
This component is currently being migrated to use `@adobe/spectrum-tokens` and will match the updated design spec once the migration work is complete. Open PR here: https://github.com/adobe/spectrum-css/pull/1842
