### ISSUE TITLE
High Contrast issues with textfield/textarea

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-css#1071]
## Description
WHCM for text fields are incorrect in the following ways:

- placeholder in disabled field is not using the grayText colour
- validation and error icons are colorized
- invalid fields to not show the highlight border
- focused and keyboard focused fields do not show the highlight style

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Turn on Windows High Contrast mode
3. Use Chromium Edge
4. Go to textfield demo
5. Observe

## Expected behavior
Expected behaviour described above

## Environment
 - **Spectrum CSS version:**  3.0.0-beta.5
 - **Browser(s) and OS(s):**  Edge 86.0.622.63 on Win 10

**Comment by pfulton** [comment]
This should have been taken care of with the migration to `@adobe/spectrum-tokens`. Please reopen if needed.
