### ISSUE TITLE
Prototype slider with ticks

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#1077]
How can we implement ticks on the slider and position labels?

Discussion started with React and Design.

**Comment by Westbrook** [comment]
Is this related to how the handle doesn't go to the "end" of the track, so you can't represent any number but `50%` in exactly the place that it needs to be? If so, this should related to https://github.com/adobe/spectrum-css/issues/711, maybe.

**Comment by pfulton** [comment]
Closing as maybe no longer relevant due to time and also a migration of this component to `@adobe/spectrum-tokens`. Please open a new issue if necessary.
