### ISSUE TITLE
[vars] Invalid CSS Available

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1084]
https://github.com/adobe/spectrum-css/blob/437005ad4b927296ffe6a207fbbe457f6e0cfffc/components/vars/css/scales/spectrum-large.css#L339-L340

Not sure if this is human generated or not, but it's got some extra back ticks in it that invalidate the content. Can I just delete?

**Comment by Westbrook** [comment]
It's also in the `medium` scale as well, which leads me more to think this is generated at some point.
https://github.com/adobe/spectrum-css/blob/437005ad4b927296ffe6a207fbbe457f6e0cfffc/components/vars/css/scales/spectrum-medium.css#L339-L340

**Comment by lazd** [comment]
Gotta be generated... We'll fix in DNA.
