### ISSUE TITLE
[Slider] "--spectrum-slider-track-color" token removed

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1087]
## Description
It looks like the `--spectrum-slider-track-color` token was removed between the `beta.4` and `beta.5` releases, was that intentional?

With token:
https://unpkg.com/browse/@spectrum-css/slider@3.0.0-beta.4/dist/index-vars.css#L595

Without token:
https://unpkg.com/browse/@spectrum-css/slider@3.0.0-beta.5/dist/index-vars.css#L629

## Expected behavior
At Spectrum Web Components we'd previously used this token to support the delivery of https://spectrum.adobe.com/page/slider/#Gradient in https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/slider--gradient

## Environment
 - **Spectrum CSS version:** @spectrum-css/slider@3.0.0-beta.5
 - **Browser(s) and OS(s):** All

**Comment by lazd** [comment]
@Westbrook Slider got t-shirt sized tokens, so that token is now `--spectrum-slider-m-track-color`. You'll find the same for ActionButton, FieldLabel, ProgressBar, etc

**Comment by Westbrook** [comment]
🤔 This version of Slider doesn't seem to have any of the `.spectrum-Slider--sizeM` styles that I would expect in that case.  https://unpkg.com/browse/@spectrum-css/slider@3.0.0-beta.5/dist/index-vars.css Am I missing something?

Separately, track color being pinned to display size seems...less than optimal. Is that really the goal here?

**Comment by lazd** [comment]
> 🤔 This version of Slider doesn't seem to have any of the `.spectrum-Slider--sizeM` styles that I would expect in that case. https://unpkg.com/browse/@spectrum-css/slider@3.0.0-beta.5/dist/index-vars.css Am I missing something?

T-shirt sized variables were implemented in DNA, but we didn't have time to implement support in CSS, instead we just fixed the build and got it building.

> Separately, track color being pinned to display size seems...less than optimal. Is that really the goal here?

I said that too, but unfortunately, this is the way DNA is architected right now. The variables are all repeated for every single size. As such, their names include `-m-`. We remap them for actual dimensional values, but instead of messing with that for colors, we just reference them directly.

**Comment by lazd** [comment]
So @Westbrook, we have `--spectrum-slider-m-track-color` for this now. Should we rename all of those and drop the `-m-` for your API's sake, or does it matter?

**Comment by Westbrook** [comment]
In that this isn't a measurement, I'd certainly prefer this.

Particularly, that means I wouldn't need to be overriding this at the SWC level. However, it's not too crazy for us to do that locally if needed.

**Comment by castastrophe** [comment]
This appears to be an outdated issue. If you run into this issue again, please feel free to open a new issue with details and we can look into it further from there!
