### ISSUE TITLE
Static number in Checkbox/Radio/Switch label variable breaks scaling

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1089]
## Description
The value for `--spectrum-checkbox-label-margin-top` is currently static: https://unpkg.com/browse/@spectrum-css/checkbox@3.0.0-beta.6/dist/index-vars.css#L11 The inclusion of the local variable setting make me that this is somehow related to some up coming t-shirt sizing leaking into this release?

## Expected behavior
All custom properties are managed by the scaling system.

## Screenshots
![image](https://user-images.githubusercontent.com/1156657/101549652-0bb3e900-397c-11eb-88c9-340dcedd2fd4.png)

## Environment
 - **Spectrum CSS version:** `@spectrum-css/checkbox@3.0.0-beta.6`
 - **Browser(s) and OS(s):** All

## Additional context
If there was a token I could point this to locally for now, I'd be much obliged.

**Comment by Westbrook** [comment]
It also seems that the usage of `static` properties in positioning the check/indeterminate icons fail to support delivery correctly across the various scales either: https://unpkg.com/browse/@spectrum-css/checkbox@3.0.0-beta.6/dist/index-vars.css#L174

**Comment by Westbrook** [comment]
Seems that the label issue also effects the `Radio` pattern delivery.

**Comment by lazd** [comment]
Hey weird, [that variable should change between scales](https://github.com/adobe/spectrum-css/blob/main/components/checkbox/index.css#L24-L26)... There might be some build funniness happening here. Definitely a bug.

**Comment by Westbrook** [comment]
This looks like it came back with the move to t-shirt sizes for Checkbox, https://opensource.adobe.com/spectrum-css/checkbox.html#t-shirtsizes:

![image](https://user-images.githubusercontent.com/1156657/106781460-1656cb80-6617-11eb-952b-bc11f80bc195.png)

Hard to tell if the check is actually centered in any of these.

**Comment by Westbrook** [comment]
With this issue continuing to crop up, and the `.spectrum-Checkbox-box` element already being `position: relative;` would it make sense to move to:
```
.spectrum-Checkbox-checkmark {
    top: 50%;
    left: 50%;
    position: absolute;
    transform: scale(1) translate(-50%, -50%);
}
```
and reduce the x-t-shirt size complexity of positioning this?
