### ISSUE TITLE
T-shirt sizing has rebroken high contrast mode

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-css#1090]
## Description
High Contrast mode colors are not rendering correctly after T-shirt sizing has been applied

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Use Edge on Windows
3. Turn on High Contrast mode
4. Run Checkbox pattern

## Expected behavior
Colors should be the Windows High Conrast colors 
(in High Contrast dark, disabled should be green and highlight color a light blue)

## Environment
 - **Spectrum CSS version:** 3.0.0.beta-6
 - **Browser(s) and OS(s):** Edge Windows 87.0.664.57

**Comment by lazd** [comment]
This is caused by https://github.com/adobe/spectrum-css/issues/1046
