### ISSUE TITLE
The CSS var --spectrum-listitem-padding-left doesn't seem to be defined

### ISSUE THREAD

**Issue by macdonst** [adobe/spectrum-css#1093]
## Description
I'm using `@spectrum-css/menu` to build a Popover menu and some spectrum variables seem not to be defined.

## Steps to reproduce

Create a page that uses `@spectrum-css/menu` and just use the example html:

```html
 <ul class="spectrum-Menu" role="menu">
    <li class="spectrum-Menu-item" role="menuitem" tabindex="0">
      <span class="spectrum-Menu-itemLabel">Deselect</span>
    </li>
    <li class="spectrum-Menu-item" role="menuitem" tabindex="0">
      <span class="spectrum-Menu-itemLabel">Select Inverse</span>
    </li>
    <li class="spectrum-Menu-item" role="menuitem" tabindex="0">
      <span class="spectrum-Menu-itemLabel">Feather...</span>
    </li>
    <li class="spectrum-Menu-item" role="menuitem" tabindex="0">
      <span class="spectrum-Menu-itemLabel">Select and Mask...</span>
    </li>
    <li class="spectrum-Menu-divider" role="separator"></li>
    <li class="spectrum-Menu-item" role="menuitem" tabindex="0">
      <span class="spectrum-Menu-itemLabel">Save Selection</span>
    </li>
    <li class="spectrum-Menu-item is-disabled" role="menuitem" aria-disabled="true">
      <span class="spectrum-Menu-itemLabel">Make Work Path</span>
    </li>
  </ul>
```

## Expected behavior
I expect the padding to be applied to my menu items so that the items is not completely aligned to the left of the popover. See screen shots below.

## Screenshots

Padding set to:

```css
padding: var(--spectrum-global-dimension-size-85)
          var(--spectrum-listitem-padding-right)
          var(--spectrum-global-dimension-size-85)
          var(--spectrum-listitem-padding-left);
```

<img width="432" alt="Screen Shot 2020-12-16 at 12 14 28" src="https://user-images.githubusercontent.com/353180/102382808-d8371700-3f98-11eb-9af9-a8512c7c33fb.png">

Padding set to:

```css
padding: var(--spectrum-global-dimension-size-85)
          var(--spectrum-listitem-padding-right)
          var(--spectrum-global-dimension-size-85)
          12px;
```

<img width="433" alt="Screen Shot 2020-12-16 at 12 15 31" src="https://user-images.githubusercontent.com/353180/102382948-f7ce3f80-3f98-11eb-9e1d-2e41c3a5499c.png">

## Environment
 - **Spectrum CSS version:**     "@spectrum-css/menu": "^3.0.0-beta.2",
 - **Browser(s) and OS(s):** Chrome Version 87.0.4280.88 on MacOS 10/15/7

**Comment by lazd** [comment]
Hmm that's odd, I think it's a mismatch between the version of `@spectrum-css/vars` and `@spectrum-css/menu`. It seems to work here with `@spectrum-css/menu@3.0.0-beta.5` and `@spectrum-css/vars@3.0.0-beta.2` https://codepen.io/lazd/pen/XWjRRjr?editors=1000

**Comment by lazd** [comment]
@macdonst did you give this a try with the latest versions of `menu` and `vars`? I think that'll fix it for you.

**Comment by castastrophe** [comment]
This appears to be an outdated issue.  If you run into this issue again, please feel free to open a new issue with details and we can look into it further from there!
