### ISSUE TITLE
Docs site is requesting certificate on mobile for git.corp.adobe.com

### ISSUE THREAD

**Issue by benjamind** [adobe/spectrum-css#11]
### Expected Behavior
Should be able to navigate to the site without issue and definitely without needing internal corporate certificates.

### Actual Behavior
I get prompted to install the corporate cert:

![screenshot_20181117-103201](https://user-images.githubusercontent.com/332843/48664519-9f908080-ea54-11e8-8048-e86e7c2fac14.png)

### Reproduce Scenario (including but not limited to)
Any mobile without the corp certificate.

#### Steps to Reproduce
Navigate to docs site on a mobile without the Adobe corp certificate installed.

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
Chrome, Android.

**Comment by GarthDB** [comment]
I wonder if this is because of the typekit config. We need to check that the new url is added too.

**Comment by benjamind** [comment]
It might just be these two resouces:

https://git.corp.adobe.com/pages/govett/photos/photos/DSC01822-Pano.jpeg
https://git.corp.adobe.com/pages/govett/photos/photos/DSC06369.jpg

**Comment by GarthDB** [comment]
Are those the shantanu avatars?

**Comment by benjamind** [comment]
One is an image in the Card demo, the other I think is related to the Popover. I'll investigate further.
