### ISSUE TITLE
horizontal tabs are improperly indented

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-css#1107]
## Description
Compare the SpectrumCSS implementation to the [design](https://spectrum.corp.adobe.com/page/tabs/)

Horizontal tabs should be left-aligned, but the text of the tabs is indented. The underline is no longer indented, which looks bad because of the discrepency

## Expected behavior

SpectrumCSS should match the designs

## Environment
Tested on Chrome Mac

**Comment by charlessuh** [comment]
<img width="945" alt="Screen Shot 2021-08-10 at 12 08 39 PM" src="https://user-images.githubusercontent.com/77195/128920454-2db46bf7-12ee-45bf-83f4-eeabea620435.png">

**Comment by pfulton** [comment]
This should be fixed in 79b7a822e1eb7972cb86eb916bd6e042add04350.

**Comment by adixon-adobe** [comment]
@pfulton is there a place I can preview this fix?

**Comment by GarthDB** [comment]
@adixon-adobe you can check it out locally. Our automated build is currently down. It's in the `DNA-7.0-beta` branch.

**Comment by adixon-adobe** [comment]
@Westbrook sent me a SWC link that looks great!
