### ISSUE TITLE
[link] Pattern color themeing scoped to element.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1108]
## Description
As per https://unpkg.com/browse/@spectrum-css/link@3.1.0-beta.0/dist/index-vars.css the "t-shirt" sizing approach to "remap" all `-m-` vars to the `.spectrum-Link` selector causes color themeing to be scoped directly on the selector along with the t-shirt sizing scoping. This situation means that color customization can no longer be passed to these elements from outside of shadow root. Can we move the color theming off of the selector root so that this (and likely a number of other elements taking on t-shirt sizing) can be customized appropriately?

## Steps to reproduce
Compare https://webcomponents.dev/edit/cIYQ1Cgeo77nfSPgWlvu?file=src%2Findex.stories.js where the lint test has been customized as `red` via the deprecated CSS Custom Property token `--spectrum-link-text-color` to https://webcomponents.dev/edit/YW7jcmS06Fi1BLOqLuaE?file=src%2Findex.stories.js where the current CSS Custom Property Token `--spectrum-link-primary-text-color` is defined directly on the element so that it cannot be given a new value from the outside.

## Expected behavior
A CSS Custom Property based themeing system should allow for shadow root piercing customization of its values.

## Screenshots
Yay!
![image](https://user-images.githubusercontent.com/1156657/105558288-3f549380-5cdc-11eb-957e-4644521e1c88.png)

No...
![image](https://user-images.githubusercontent.com/1156657/105558294-454a7480-5cdc-11eb-973c-7478a0710e80.png)

CC: @simshanith

**Comment by lazd** [comment]
Oh jeeze this is just done wrong, I don't know why I remapped colors at the top of `index.css`, I should be referencing them with `-m-` instead in `skin.css`.

This problem is not present in ActionButton, which is doing this properly: https://unpkg.com/browse/@spectrum-css/actionbutton@1.0.0-beta.1/dist/index-vars.css
