### ISSUE TITLE
High Contrast: Icons should appear in the text colour

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-css#1115]
## Description
When Icons are used they should be the same colour as adjacent text, not the icon colour. Depending on the color scheme chosen they may disappear if we don't do this

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Turn on High contrast mode (windows, new edge browser)
3. Observe Icons are hard to see on pages like Accordion, Text Field etc.

## Expected behavior
Icons should be easy to see

## Screenshots
![Accordion - Spectrum CSS and 2 more pages - Work - Microsoft​ Edge 1_29_2021 11_07_00 AM](https://user-images.githubusercontent.com/1724479/106317385-1d4e9a00-6223-11eb-8cbf-50a14c961b1a.png)
![Accordion - Spectrum CSS and 2 more pages - Work - Microsoft​ Edge 1_29_2021 11_06_42 AM](https://user-images.githubusercontent.com/1724479/106317392-20498a80-6223-11eb-96f5-f586838b0a26.png)
![Accordion - Spectrum CSS and 2 more pages - Work - Microsoft​ Edge 1_29_2021 11_06_27 AM](https://user-images.githubusercontent.com/1724479/106317401-22abe480-6223-11eb-914e-ad59b7c07b2a.png)

## Environment
 - **Spectrum CSS version:**  2.13.0 
 - **Browser(s) and OS(s):**  Edge 88.0.705.56 on Win 10

**Comment by castastrophe** [comment]
Closing this as outdated but please reopen with additional context if this still needs to be addressed.
