### ISSUE TITLE
high contrast checkboxes need refining for spectrum

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-css#1117]
## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Click on checkboxes
3. run in WHCM with edge (chromium)
3. Observe does not meet the spectrum guidelines for WHCM

## Expected behavior
Should meet the spectrum guidelines

## Screenshots
https://spectrum.adobe.com/static/Windows-High-Contrast-Kits/Checkbox-WindowsHighContrast.xd

## Environment
 - **Spectrum CSS version:** 2.13.0 
 - **Browser(s) and OS(s):** Edge 88.0 on Win 10

**Comment by pfulton** [comment]
@jnurthen I think we've taken care of this with the move to the new `@adobe/spectrum-tokens` system, but please open a new issue if you see any additional problems.
