### ISSUE TITLE
WHCM buttons need to meet spectrum designs

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-css#1119]
## Description
Buttons don't meet WHCM as defined by spectrum

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Click on button-CTA (and the other button pages)
3. Observe 

## Expected behavior
Should meet https://spectrum.adobe.com/static/Windows-High-Contrast-Kits/Button-WindowsHighContrast.xd

## Environment
 - **Spectrum CSS version:** 2.13.0 
 - **Browser(s) and OS(s):** Edge 88.0 on Windows 10

**Comment by pfulton** [comment]
This should have been fixed during the migration to `@adobe/spectrum-tokens` - please open a new issue if it's still a problem.
