### ISSUE TITLE
[Search][Textarea][Textfield] Correct placeholder text color alias to var(--spectrum-alias-placeholder-text-color);

### ISSUE THREAD

**Issue by majornista** [adobe/spectrum-css#1123]
## Description
Currently, Spectrum-CSS uses `var(--spectrum-global-color-gray-600);` for the `::placeholder` text color in Search, Textarea and Textfield components, which results in placholder text that does not comply with WCAG 2.1 AA contrast ratio requirements, and is different than the value specified in Spectrum for `var(--spectrum-alias-placeholder-text-color)`, `gray-800`.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/textfield.html
2. Inspect the placeholder text element in the sub-dom for any of the enabled textfield examples. 
3. Observe the color specified in CSS is currently `var(--spectrum-global-color-gray-600);`

## Expected behavior
Placeholder text should use the token defined in Spectrum `var(--spectrum-alias-placeholder-text-color)` which corresponds to  `var(--spectrum-global-color-gray-800);`.

### Current behavior
![Non-compliant Placeholder text](https://user-images.githubusercontent.com/154077/106511085-c0124d00-649d-11eb-9957-00c76925dbd9.png)

### Expected behavior
![Compliant Placeholder text](https://user-images.githubusercontent.com/154077/106511474-4464d000-649e-11eb-9080-c4052cf1d010.png)

## Environment
 - **Spectrum CSS version:**  2.18.0, @spectrum-css/search@3.0.0-beta.7, @spectrum-css/textfield@3.0.0-beta.6
 - **Browser(s) and OS(s):** Chrome Version 88.0.4324.96 (Official Build) (x86_64) on macOS

**Comment by castastrophe** [comment]
Closing this as the current design guidance is not to use placeholders: https://spectrum.adobe.com/page/text-field/#Don’t-use-placeholder-text
