### ISSUE TITLE
secondary links appearing as text color not link color in WHCM

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-css#1125]
## Description
Secondary links are appearing as text color not link color in WHCM

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/link.html
2. Use Edge , Win 10 , Windows High Contrast Mode on
3. Observe secondary link (both quiet and non) are text color not link color

## Expected behavior
Should be link color as shown in https://spectrum.adobe.com/static/Windows-High-Contrast-Kits/Link-WindowsHighContrast.xd

## Environment
 - **Spectrum CSS version:**  2.13.0
 - **Browser(s) and OS(s):** Edge 88.0 on Win 10

**Comment by castastrophe** [comment]
This is fixed on main. 🎉 

![](https://snapshots.chromatic.com/snapshots/63f7908f19912748edc50f0d-6705a7489e4d11ed029ee7d4/capture-fc4de3e5.png)
