### ISSUE TITLE
[menu] Missing token values

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1130]
## Description
`--spectrum-listitem-selectable-padding-right` doesn't seem to be given a value in the Menu styles.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/picker.html
2. Add the `.is-selectable` class to one of the open Menu element (which is likely also missing in that metadata for this UI)
3. Observe :
![image](https://user-images.githubusercontent.com/1156657/107426554-6093ed00-6aee-11eb-876c-b98cc54e5add.png)

## Expected behavior
There's a value for `--spectrum-listitem-selectable-padding-right` which had previously been approximately;
```
calc(
        var(--spectrum-global-dimension-size-100) +
            var(--spectrum-icon-checkmark-medium-width) +
            var(--spectrum-listitem-icon-gap)
    )
```

cc @GarthDB as I think you're looking at this right now.

**Comment by pfulton** [comment]
This component has been completely overhauled and migrated to use `@adobe/spectrum-tokens`. Please open a new issue if you find that custom properties are still missing.
