### ISSUE TITLE
Slider thumb inner background should not be transparent

### ISSUE THREAD

**Issue by charlessuh** [adobe/spectrum-css#1133]
## Description

For sliders with a ramp or tick, the circle thumb shows the ramp or tick behind it.

## Steps to reproduce

spectrum-css:

<img width="484" alt="Screen Shot 2021-02-10 at 2 40 31 PM" src="https://user-images.githubusercontent.com/77195/107582733-cd6ebc00-6bae-11eb-8cfc-5107d0ccc83d.png">

## Expected behavior

Design spec:

<img width="598" alt="Screen Shot 2021-02-10 at 2 39 11 PM" src="https://user-images.githubusercontent.com/77195/107582750-d3649d00-6bae-11eb-9815-f88b040fa82d.png">

## Screenshots

See above.

## Environment
 - **Spectrum CSS version:** @spectrum-css/slider@3.0.0
 - **Browser(s) and OS(s):** Chrome 88

## Additional context
n/a

**Comment by castastrophe** [comment]
This is resolved on our latest build: https://opensource.adobe.com/spectrum-css/?path=/story/components-slider--default&globals=testingPreview:!true
