### ISSUE TITLE
Are the mitigating factors behind the "fill" version of the thumbnail pattern

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1134]
## Description
Currently the "fill" delivery of the following DOM structure:
```
<div class="spectrum-Thumbnail">
  <div class="spectrum-Thumbnail-background" style="background-image: url(img/example-card-portrait.jpg)" title="Eiffel Tower at night"></div>
</div>
```
As opposed to the default version featuring an `<img>` tag:
```
<div class="spectrum-Thumbnail is-focused">
  <img class="spectrum-Thumbnail-image" src="img/example-card-portrait.jpg" alt="Eiffel Tower at night">
</div>
```

Was there something in particular about `background-size: cover` and its requirement for this alternate DOM that lead to its use over something like `object-fit: cover` on the image?
```
<div class="spectrum-Thumbnail is-focused">
  <img class="spectrum-Thumbnail-image" src="img/example-card-portrait.jpg" alt="Eiffel Tower at night" style="object-fit: cover;">
</div>
```
In this way a `spectrum-Thumbnail--cover` or `spectrum-Thumbnail-image--cover` toggle would be all that's needed to support this delivery, as opposed to change to the entire DOM.

Thoughts?

**Comment by lazd** [comment]
> Was there something in particular about `background-size: cover` and its requirement for this alternate DOM that lead to its use over something like `object-fit: cover` on the image?

Yup, it's because IE 11 didn't support `object-fit` at all, so we had to go with `background-size: cover`.

**Comment by Westbrook** [comment]
Looks like we went with `cover` all the time and broke these: ![image](https://user-images.githubusercontent.com/1156657/145141936-8e9e8755-5e5f-4478-aa31-014513b1820c.png)
