### ISSUE TITLE
[Card] Support for extended body content

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1137]
## Description
Are there plans to support an extended amount of body content as found in: https://spectrum.adobe.com/page/cards/#Anatomy

![image](https://user-images.githubusercontent.com/1156657/108923736-5c47f380-7607-11eb-8ee8-abc346568482.png)

For instance the area where text about XD is applied.

## Why do you need this feature or component?
@charlessuh can you share some extended use case for this in your work?

**Comment by Westbrook** [comment]
Usage example:

![help](https://user-images.githubusercontent.com/1156657/108925576-e6de2200-760a-11eb-8444-0b66f32f97ba.png)

This goes so far as to forgo the heading content all together, which currently leverages some fixed sized containers that might need an edit pass for this sort of thing to be added.

**Comment by mephraim** [comment]
Similarly, on Adobe Fonts we include multiple lines of content in our "Family cards" for fonts.

Example:

![image](https://user-images.githubusercontent.com/35886/109035485-4f221780-768e-11eb-9ab6-35d2f8844e3e.png)

**Comment by lazd** [comment]
Yeah looks like we need to remove the height from `.spectrum-Card-content` and just let you write that stuff in `.spectrum-Body` inside of it.

**Comment by adixon-adobe** [comment]
Looking at most of the examples for card on the design site, it seems like in most cases the subtitle is multi-line: https://spectrum.adobe.com/page/cards/

It also looks like the font size is smaller in Spectrum CSS than the designs. Not sure that all fits with this issue, but right now I'm finding this really hard to use and get a result that looks good.

**Comment by castastrophe** [comment]
These use-cases seem feasible with the open-ended approach the card currently uses. https://opensource.adobe.com/spectrum-css/?path=/docs/components-card--docs&globals=testingPreview:!true

Let me know if we need to reopen this though!
