### ISSUE TITLE
[Button] Between 3.0.0 and 3.0.1 custom properties were removed from the output

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1157]
## Description
See https://unpkg.com/browse/@spectrum-css/button@3.0.0/dist/index-vars.css#L250
See https://unpkg.com/browse/@spectrum-css/button@3.0.1/dist/index-vars.css#L250

Notice the removal of `--spectrum-button-primary-padding-right`.

This is true in each one of the sizes and while it doesn't directly effect the `Button` pattern as most of the usage of this value has customizations regarding the state of the element, it does effect `SplitButton`, see: https://opensource.adobe.com/spectrum-css-vr-results/vrt-19bcf7f-2021-03-18_01-32-29/dist/docs/splitbutton.html

**Comment by pfulton** [comment]
Closing as this component has been migrated to use `@adobe/spectrum-tokens`
