### ISSUE TITLE
[Accordion] Control over item title text transform.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1164]
https://github.com/adobe/spectrum-css/blob/051b16be1e880fbabd98b0e98b0bbfa6173fc4fe/components/accordion/index.css#L101

Can this be updated to surface a Custom Property? There are a handful of product lines that are currently reviewing designs that have this title not in uppercase. I'm not sure if there's an established pattern to add localized custom properties like this, but happy to update to `var(--spectrum-accordion-item-text-transform, uppercase)` or similar via a PR.

**Comment by Westbrook** [comment]
@simshanith we're tracking the addition of a `text-transform` custom property here. Being able to similarly manage the `font-weight` sounds like a great idea!

https://github.com/adobe/spectrum-css/blob/051b16be1e880fbabd98b0e98b0bbfa6173fc4fe/components/accordion/index.css#L106

**Comment by simshanith** [comment]
My extension used the following variables and fallbacks:

```css
text-transform: var(
  --spectrum-accordion-item-title-text-transform,
  uppercase
);
font-weight: var(--spectrum-accordion-item-title-text-font-weight, 500);
```

**Comment by GarthDB** [comment]
We'll be talking about this with the Design team. We need to figure out what the default styling should be and how we override it for a11y and localization needs.

**Comment by castastrophe** [comment]
Closing this as outdated but please reopen with additional context if this still needs to be addressed.
