### ISSUE TITLE
Show Markup broken for some examples

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#117]
### Expected Behavior

Show Markup does what it promises to do, all of the time

### Actual Behavior

Broken promises, broken hearts\

#### Steps to Reproduce

1. http://opensource.adobe.com/spectrum-css/2.8.0/docs/#toast
2. Click "Show Markup"
3. Cry

#### Spectrum-CSS version

2.8.0

**Comment by jianliao** [comment]
Yeah, seen this issue quite a few times.

**Comment by filmaj** [comment]
Same, like the Link examples. I need to open up devtools, like a sucker, to see the markup! 😉

**Comment by naeohmi** [comment]
In progress, here: https://github.com/naeohmi/spectrum-css/tree/issue/117
