### ISSUE TITLE
WHCM for tabs

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-css#1175]
## Description
Tabs do not show selection or focus correctly in WHCM

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Click on Tabs
3. Enable WHCM
3. Observe focus 

## Expected behavior
I expect behaviour to match native windows behaviour

## Screenshots
![Tabs - Spectrum CSS and 3 more pages - Work - Microsoft​ Edge 4_29_2021 4_50_03 PM](https://user-images.githubusercontent.com/1724479/116632146-52928300-a90b-11eb-8ff7-7ea87bdb90a3.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** Edge 90 on Windows 10

**Comment by pfulton** [comment]
Will be implemented as part of the work for the migration to `@adobe/spectrum-tokens`: https://jira.corp.adobe.com/browse/CSS-180
