### ISSUE TITLE
#spectrum-icon-18-Edit not in node_modules/@spectrum-css/icon/dist/index-vars.css

### ISSUE THREAD

**Issue by mscherotter** [adobe/spectrum-css#1179]
## Description

I'm using the spectrum-css button here https://opensource.adobe.com/spectrum-css/button-cta.html and find that the small button with the icon works but the icon is not showing up. where in the CSS is the #spectrum-icon-18-Edit icon?

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Click on ...
3. Observe ...

## Expected behavior

Edit icons shows up

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by castastrophe** [comment]
This appears to be an outdated issue. If you run into this issue again, please feel free to open a new issue with details and we can look into it further from there!
