### ISSUE TITLE
[Textfield] Icons should be "pointer-events: none"

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1181]
## Description
When using a Textfield, I'd like users who accidentally click on the Icon element that is available when valid, invalid, a Search Field, etc to be able to focus the field the same way they would when they clicked a small number of pixels up/down/left/right of where they actually clicked. Can we add `pointer-events: none;` to those icons?

## Why do you need this feature or component?
Clarify usage of the field.

## Additional context
Currently if you visit https://opensource.adobe.com/spectrum-css/textfield.html#valid and click exactly on the Checkmark you get the "active" styling while the pointer is down, but nothing will have focus when you complete the click.

**Comment by GarthDB** [comment]
Looks like this was fixed and released with this commit https://github.com/adobe/spectrum-css/commit/d2c57b77fe3f1550d196ca628e940ec0e17b236c
