### ISSUE TITLE
Remove margins from Heading and Body size classes

### ISSUE THREAD

**Issue by bdenham** [adobe/spectrum-css#1190]
## Description

In `"@spectrum-css/typography": "^3.0.2"` release, the Heading and Body sizes include `margin-top: 0;` and `margin-bottom: 0;`, which results in no spacing between paragraphs. 

## Steps to reproduce

1. Install `"@spectrum-css/typography": "^3.0.2",` in your project.
2. Open the installed package: `node_modules/@spectrum-css/typography/dist/index-vars.css`.
3. Observe the additions of `margin-top: 0` and `margin-bottom: 0` within the `.spectrum-Heading--size*` and `.spectrum-Body--size*` classes.

```
.spectrum-Body--sizeM {
        font-size: var(--spectrum-body-m-text-size, var(--spectrum-global-dimension-font-size-200));
      font-weight: var(--spectrum-body-m-text-font-weight, var(--spectrum-alias-body-text-font-weight));
      line-height: var(--spectrum-body-m-text-line-height, var(--spectrum-alias-body-text-line-height));
      font-style: var(--spectrum-body-m-text-font-style, var(--spectrum-global-font-style-regular));
      letter-spacing: var(--spectrum-body-m-text-letter-spacing, var(--spectrum-global-font-letter-spacing-none));
      text-transform: var(--spectrum-body-m-text-transform, none);
      margin-top: 0;
      margin-bottom: 0;
  }
```

## Expected behavior

Margins should not be part of the font sizing classes.

## Screenshots

This should be four separate paragraphs. 

![image](https://user-images.githubusercontent.com/1828494/118386737-3b2be900-b5df-11eb-8c03-657783095a26.png)

## Environment
 - **Spectrum CSS version:** 3.0.2
 - **Browser(s) and OS(s):** Chrome 90.0.4430.212 (Official Build) (x86_64) on macOS 11.3

**Comment by castastrophe** [comment]
This appears to be an outdated issue. With the addition of the wrapper .spectrum-Typography class, margins are added to the appropriate nested typography elements.

If you run into this issue again, please feel free to open a new issue with details and we can look into it further from there!
