### ISSUE TITLE
Icons not loading on webpage

### ISSUE THREAD

**Issue by mscherotter** [adobe/spectrum-css#1191]
## Description

I am loading icons for use in spectrum CSS as described in the docs at https://github.com/adobe/spectrum-css/blob/main/README.md but the icons do not show up.  I see the icons are loaded in the DOM but are not loaded in the svg use element.  Do you have a working sample that demonstrates this method in HTML/css/js
Also, some icons in the HTML like #spectrum-icon-18-More are not defined at all in the SVG files in in the node_modules @spectrum icons folder https://opensource.adobe.com/spectrum-css/card.html

<script src="/node_modules/loadicons/index.js"></script>
<script>
    loadIcons("/node_modules/@spectrum-css/icon/dist/spectrum-css-icons.svg", function(result){
       console.log("Loaded Spectrum icons.");
})
</script>

                  <svg class="spectrum-Icon spectrum-Icon--sizeM" focusable="false" aria-hidden="true">
                    <use xlink:href="#spectrum-icon-18-More"/>
                  </svg>

## Steps to reproduce

follow steps at https://github.com/adobe/spectrum-css/blob/main/README.md to use icons.

## Expected behavior
icons show up.

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by lazd** [comment]
You need `<link rel="stylesheet" href="node_modules/@spectrum-css/icon/dist/index-vars.css">` also.

See this pen: https://codepen.io/lazd/pen/JjWbogp

Inspect the includes for CSS by clicking the gear icon:

![image](https://user-images.githubusercontent.com/201344/118720030-f6ba6c00-b7dd-11eb-91f5-889e238940e2.png)

**Comment by mscherotter** [comment]
I was missing loadicons for the worklflow icons.  Working now - the docs for the Spectrum CSS should list the dependencies.
Michael
