### ISSUE TITLE
[Slider] Range slider track is given wrong "margin-block-start"

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1205]
The _roughly_ `margin-block-start: -1px;` rule in the following line:

https://github.com/adobe/spectrum-css/blob/842406ad3e9da3a652f2d76acddeba3b5d02ecc3/components/slider/index.css#L109

Is overridden as `margin-block-start: 0;` in the following line:

https://github.com/adobe/spectrum-css/blob/main/components/slider/index.css#L180

Naively, the following would appear to cure this situation:
```
margin-block: calc(var(--spectrum-slider-track-height) / -2) var(--spectrum-slider-range-track-reset);
```

I'd be happy to submit a PR if this seemed appropriate.

**Comment by Westbrook** [comment]
Might the be something that could find its way into the Express pass on this pattern?

**Comment by castastrophe** [comment]
This appears fixed here: https://opensource.adobe.com/spectrum-css/?path=/story/components-slider--default&globals=testingPreview:!true
