### ISSUE TITLE
Audit Express Designs

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#1219]
Rough Visual Audit - break into separate tasks as needed.
- [x] ActionButton (API Change) #1219 - progress
- [x] Button (API Change) #1228  - progress
- [x] #1241
- [x] #1256
- [x] #1255
- [x] #1242
- [x] #1243
- [x] #1244
- [x] #1245
- [x] #1246
- [x] #1247
- [x] #1248
- [x] #1249
- [x] #1250
- [x] #1251
- [x] #1252
- [x] #1253
- [x] #1254

**Comment by castastrophe** [comment]
@GarthDB It looks like most of the related issues have been resolved, should I close this out?
