### ISSUE TITLE
icon-only Action Button/Action Menu small size not to spec

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-css#1237]
## Description

The small size in SpectrumCSS is 30x24: https://spectrum.adobe.com/page/action-button/ (it's the only size/variant that's not square, so that's a clue)

## Expected behavior

The small size is 24x24 per the XD designs here https://spectrum.adobe.com/page/action-button/ (sizing examples near the bottom)

## Workaround

`--spectrum-actionbutton-s-min-width: 24px`

**Comment by Westbrook** [comment]
Does this seem like the sort of thing that might be addressable during the Express review of the Action Button pattern?
