### ISSUE TITLE
Form (labels right) example doesn't have labels on the right

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#1265]
## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/form.html#formlabelsright
2. The labels aren't all right

## Expected behavior

The labels are on the right

## Screenshots

![image](https://user-images.githubusercontent.com/201344/132742139-4d71eea3-3f71-410c-8575-4f71475af419.png)

**Comment by Westbrook** [comment]
The labels are aligned right in this case, was that not the goal?

If we change the delivery here should we use start/end style API naming post change?

**Comment by lazd** [comment]
Ah, it seems they are aligned right. Looks like it's not an issue, the docs are just unclear.
