### ISSUE TITLE
High Contrast broken for actionbutton

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-css#1284]
## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Turn on High Contrast mode
2. Click on Action Button
3. Observe focus, icons etc all broken

## Expected behavior
I expect to see the behaviour in PR https://github.com/adobe/spectrum-css/pull/1076

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** Edge 93 on Windows

## Additional context
Spectrum variable names have all been updates. The high contrast variables all need updating

**Comment by pfulton** [comment]
Should be fixed with the move to `@adobe/spectrum-tokens`. Please open a new issue if you notice any new problems.
