### ISSUE TITLE
Add Dialog example with footer.

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#1285]
## Description
We have a class `.spectrum-Dialog-footer` that isn't used in any examples on the website.

## Link to documentation
[Dialog page](https://opensource.adobe.com/spectrum-css/dialog.html)

**Comment by castastrophe** [comment]
Examples are available now on the documentation with action buttons in the footer: https://opensource.adobe.com/spectrum-css/?path=/story/components-dialog--default&globals=testingPreview:!true
