### ISSUE TITLE
TreeView 4.0.0 Invalid CSS (extra closing parenthesis)

### ISSUE THREAD

**Issue by kbuchanan** [adobe/spectrum-css#1292]
After upgrading to TreeView 4.0.0, I was no longer able to build due to an invalid CSS error.

I noticed an extra closing parenthesis in `index.css` (which means it is also present in `index-vars.css`) in the TreeView component:

https://github.com/adobe/spectrum-css/commit/6d9168ad12e13f2ea2cbf0235124ea42e1cb8aea#diff-d024aba3c31ddd0c3349329224cc5568b239d00f3bef73d6630d513e0c12d006R142

When I removed the extra closing brace, I was able to compile in my app again.

**Comment by lazd** [comment]
Bug introduced in https://github.com/adobe/spectrum-css/commit/6d9168ad12e13f2ea2cbf0235124ea42e1cb8aea

@kbuchanan Wanna send a quick PR?
