### ISSUE TITLE
[Progress Bar] Indeterminate Progress Bar: animation skips in modal dialog

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1298]
## Description
When an `.spectrum-ProgressBar--indeterminate` Progress Bar is leveraged with in a `.spectrum-Modal` wrapped dialog, then the animation of the progress bar skips.

## Steps to reproduce

1. Go to https://codepen.io/Westbrook/pen/bGreRdx?editors=1010
2. Click on "Open Scrolling Dialog"
3. Observe the progress bar skip
4. Click "Toggle Fix" adds `overflow: visible; max-width: 100%;` (the second might not be needed but I was testing in a rather narrow window.
5. See the animation go smoothly.

## Expected behavior
Animation should be smooth.

## Environment
 - **Spectrum CSS version:** Latest
 - **Browser(s) and OS(s):** Chrome `Version 94.0.4606.81 (Official Build) (x86_64)`

## Additional context
Relates to https://github.com/adobe/spectrum-web-components/issues/1869

**Comment by castastrophe** [comment]
Opened the pen and updated the file paths to use tokens instead of vars. This issue seems to be resolved.
