### ISSUE TITLE
Logical Property in Media Query

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1306]
Should there be a postCSS plugin or similar that washes the following out in the build?

https://github.com/adobe/spectrum-css/blob/f36154fa03c3d64a5fcf9d70399e6b1b2e4f01d3/components/dialog/index.css#L314

I'm not seeing it working in any version of Chrome right now: https://codepen.io/Westbrook/pen/jOLZZEM so it seems weird that this would be shipping in the default packages.

**Comment by lazd** [comment]
Oh weird, that shouldn't have happened. I think it might have been a search/replace when we switched to logical properties. It's strange that `postcss-logical` doesn't have anything to say about that.
