### ISSUE TITLE
Migrations tables do not use t-shirt sized class.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1310]
## Description
![image](https://user-images.githubusercontent.com/1156657/140769308-2f55960c-7456-46fe-9b3a-b8e7f389186f.png)

## Link to documentation
https://opensource.adobe.com/spectrum-css/button-warning.html#migrationguide

## Additional context
Seems like it just needs `.spectrum-Table--sizeM`...
![image](https://user-images.githubusercontent.com/1156657/140769438-153200da-5a32-4f25-b448-a14ff9c6cfd2.png)

**Comment by lazd** [comment]
Fixed by #1311
