### ISSUE TITLE
Stepper shows Firefox native up/down buttons in control

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-css#132]
### Expected Behavior
Native up/down step control buttons should not show

### Actual Behavior
When running in FF up/down buttons show in the control along with the spectrum up/down buttons

### Reproduce Scenario (including but not limited to)
Run http://opensource.adobe.com/spectrum-css/2.9.1/docs/#stepper in Firefox

#### Steps to Reproduce
Run page in Firefox - look at stepper control 

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
Firefox 66.0.3 (64-bit) MacOS

#### Spectrum-CSS version
2.9.1

**Comment by jnurthen** [comment]
This is caused by 
```
.spectrum-Textfield {
...
 -moz-appearance:textfield;
 -webkit-appearance:none!important;
}
```
`-webkit-appearance` is also supported by FF so is overriding `-moz-appearance`

**Comment by lazd** [comment]
Thanks, @jnurthen! It turns out we don't need `!important` there at all. After checking with the latest version of normalize.css, there are no problems even if that statement is removed entirely. I dropped the `!important` and tested in FF and Chrome + Normalize, and it's looking right now.

**Comment by jnurthen** [comment]
Still reproduces. I think you need to reverse the order of -moz-appearance and -webkit-appearance

**Comment by jnurthen** [comment]
@lazd Do I need to log a new issue or can you reopen this one.

**Comment by GarthDB** [comment]
@jnurthen Reopening should be good.

**Comment by lazd** [comment]
Looks like this should be fixed by https://github.com/adobe/spectrum-css/commit/0fc6c3b12b26e87c4730878003509e3a44c0da86, which will be merged to master shortly.

**Comment by lazd** [comment]
This is fixed, just tested in Firefox.
