### ISSUE TITLE
How to update from 3.0.3 to 3.0.7

### ISSUE THREAD

**Issue by topperblues** [adobe/spectrum-css#1321]
Hi, after updating the minor version of spectrum CSS from .3 to .7  (3.0.3 to 3.0.7 for some components and from 1.0.3 to 1.0.7 for other components) we have multiple differences on almost all components.

For example, buttons become squared and get white borders color, quite TextFields does not have bottom border.

![image](https://user-images.githubusercontent.com/7091716/141161279-5d850687-7446-428a-810f-111fdc233986.png)

![image](https://user-images.githubusercontent.com/7091716/141161380-3d39585d-99d9-4c1e-b63c-c58a797bb399.png)

Do we need to make any changes to be able to upgrade?
We have read the changelogs of some components and checked the reference site but we have not found any information about it.

Thank you.

**Comment by pfulton** [comment]
This is quite old, so I am going to close. Please open a new issue if you still need support.
