### ISSUE TITLE
[Thumbnail] Border content escapes clip path

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1334]
Currently the `::before` pseudo element of the Thumbnail pattern is given a `z-index` property to support it stacking correctly internal to the Thumbnail pattern.

https://github.com/adobe/spectrum-css/blob/99f93b95cbdab841d4428440da407328452b1a5a/components/thumbnail/index.css#L40

However, this can cause the border that it represents to leak _OVER_ other content:

![image](https://user-images.githubusercontent.com/1156657/142650227-da3698ad-b9b0-4c45-b862-2f7d8cf18bd7.png)
![image](https://user-images.githubusercontent.com/1156657/142650447-4327a232-8b37-4bbd-89ec-a008495963ac.png)

It's possible that using `z-index: 0` on the root `.spectrum-Thumbnail` would prevent this issue, thought it might cause some others of its own. It's possible that the combination of a "selection ring" and a "focus ring" precipitates a more complex HTML structure here. Maybe there's another smart answer that I can think of just now, but it seems that there are some display issues possible do to the current delivery.

synced to jira: https://jira.corp.adobe.com/browse/CSS-81

**Comment by Deanna-w1** [comment]
Garth will check with patrick to ensure this is fixed.

**Comment by GarthDB** [comment]
I tried the `z-index: 0` on the thumbnail and it doesn't seem to have any negative impact - would you like to test it out to see if it fixes the issue for you @Westbrook ?

**Comment by Westbrook** [comment]
That does seem to work, however forcing the root element to `z-index: 0` might cause some surprising cases with advanced layouts leveraging this element. I'm not doing that, but I could see it happening.

An alternative might be to use `::after` instead of `::before` in which case I don't think the pseudo element needs a `z-index` at all.
