### ISSUE TITLE
[Action Button] Small text baseline too low in Chrome

### ISSUE THREAD

**Issue by bmancini-adobe** [adobe/spectrum-css#1340]
## Description
Noticed during testing that the baseline for Action Button is too low on the "small" size, in Chrome but not in Safari.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/actionbutton.html#sizing
2. Look at the buttons under "S" in Chrome
3. Observe that the baseline is lower than expected
4. Look at the same buttons in Safari -- looks as expected

## Expected behavior
Chrome should have the text more centered as it is in Safari.

## Screenshots
These screenshots are from https://opensource.adobe.com/spectrum-css/actionbutton.html#sizing

### Chrome:
<img width="58" alt="Screen Shot 2021-12-13 at 12 11 05 PM" src="https://user-images.githubusercontent.com/51969402/146076464-6c93b6f8-3062-4da3-82ab-06083111beaf.png">

### Safari:
<img width="57" alt="Screen Shot 2021-12-13 at 2 12 53 PM" src="https://user-images.githubusercontent.com/51969402/146076512-66bb0bde-db48-41ed-93a0-b4067c79f02d.png">

## Environment
 - **Spectrum CSS version:** @spectrum-css/actionbutton@1.1.0
 - **Browser(s) and OS(s):** Mac Chrome and Safari

**Comment by castastrophe** [comment]
Baseline corrected in the latest build: https://opensource.adobe.com/spectrum-css/?path=/story/components-action-button--default&globals=testingPreview:!true
