### ISSUE TITLE
Ongoing: Explore API differences between Spectrum CSS and React Spectrum

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#136]
New React API proposals: https://paper.dropbox.com/folder/show/API-e.1gg8YzoPEhbTkrhvQwJ2zzy3zzZvAmrqu7Rj5Jv6AtvjO1cwcMJf

Typography API exploration: https://paper.dropbox.com/doc/Typography-API--AcvJ2T2f~lkraEeBYnOzU_DgAg-M9oL1ItYZwARYk8sTCGc5

Breaking API differences: https://github.com/adobe/spectrum-css/milestone/2

**Comment by lazd** [comment]
Documentation is here: https://paper.dropbox.com/folder/show/API-e.1gg8YzoPEhbTkrhvQwJ2zzy3zzZvAmrqu7Rj5Jv6AtvjO1cwcMJf

**Comment by GarthDB** [comment]
Mostly fixed in the RSP V3 work, but an ongoing effort.
