### ISSUE TITLE
HTML <input type="file"/>

### ISSUE THREAD

**Issue by mscherotter** [adobe/spectrum-css#1370]
## Description
How do you style an HTML <input type="file"> to get a file upload UI in Spectrum CSS.
label

`<input id="coverImageInput" type="file" accept=".jpg,.png,.webp,image/"/>
`

## Screenshots
![image](https://user-images.githubusercontent.com/641702/152089245-7828f094-0a56-4c34-98af-b5bbfed7336d.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by GarthDB** [comment]
This is a great question. I submitted it to the Spectrum Design team and I'll let you know what they come back with.

**Comment by castastrophe** [comment]
Not an input field semantically but this is the design direction we got for uploading files: https://opensource.adobe.com/spectrum-css/?path=/story/components-drop-zone--default&globals=testingPreview:!true

Going to close this issue at this time until we receive design direction.
