### ISSUE TITLE
Rename Banner to Badge, add variants and icon

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#138]
- [ ] Rename Banner to Badge
- [ ] Rename `info`/`warning`/`error` to `info`/`negative`/`positive` + the 8 colors above
- [ ] Remove `spectrum-Banner-header`
- [ ] Add `spectrum-Banner-icon`
- [ ] Add `size=small` for number/notification badges
- [ ] Add CSS for alignment to remove corner radii?

synced to jira: https://jira.corp.adobe.com/browse/SDS-7330

**Comment by GarthDB** [comment]
Remove Label as part of this, would close #140
