### ISSUE TITLE
Button label line-height ends up as 18.2px, makes buttons sized incorrectly

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#1380]
## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/button-accent.html
2. Inspect a Medium Button
3. Observe height is fractional (32.2px instead of 32px)

## Expected behavior

Height is exactly 32px.

## Screenshots

![image](https://user-images.githubusercontent.com/201344/153513827-a3160a01-f664-46f2-939b-44a7f11cfb13.png)
<img width="382" alt="image" src="https://user-images.githubusercontent.com/201344/153513858-8bb20c4e-c71c-453f-958c-12d83bede678.png">

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** 

## Additional context

This is due to the 1.3 line height, which calculates to 18.2px. It needs to be driven by a round pixel value, which will change for each t-shirt size.

synced to jira: https://jira.corp.adobe.com/browse/CSS-74

**Comment by castastrophe** [comment]
Closing this as outdated but please reopen with additional context if this still needs to be addressed.
