### ISSUE TITLE
[Text Area] Rendering weirdness

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1383]
## Description
The focus and keyboard focus delivery can get out of alignment.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/textarea.html
2. Tab into a text area
3. Use the resize handle to change the size of the Text Area
4. See the focus states not align.

## Expected behavior
Should probably keep the borders aligned with each other.

## Screenshots
<img width="299" alt="image" src="https://user-images.githubusercontent.com/1156657/154123343-be167475-a1a0-4d0f-9d76-d26b5cd80cd3.png">

## Environment
 - **Spectrum CSS version:** Latest
 - **Browser(s) and OS(s):** macOS

## Additional context
In SWC I'm looking at just _moving_ the keyboard focus designs onto the `<textarea>` element rather than using the wrapper with an `:after` pseudo element that is used elsewhere possibly fixing this.

synced to jira: https://jira.corp.adobe.com/browse/CSS-76

**Comment by Deanna-w1** [comment]
Deanna to share update with WB and confirm if this is done

**Comment by pfulton** [comment]
Should have been closed by https://github.com/adobe/spectrum-css/pull/1863
