### ISSUE TITLE
[Action Group] Express Condensed non-quiet action group spacing

### ISSUE THREAD

**Issue by Deanna-w1** [adobe/spectrum-css#1386]
## Description
The condensed non-quiet action group has buttons overlapping by border size. 

## Expected behavior
Change spacing to 2 px

## Screenshots
![image](https://user-images.githubusercontent.com/91302351/154133391-2c74c615-dc0e-4fa4-a79e-1bbe17ad5e9d.png)

synced to jira: https://jira.corp.adobe.com/browse/CSS-77

**Comment by castastrophe** [comment]
This appears to be fixed! https://opensource.adobe.com/spectrum-css/?path=/story/components-action-group--default&args=isFocused:!true&globals=context:express;testingPreview:!true
