### ISSUE TITLE
[Action Button] :hover styling causes unexpected behavior on touchscreen devices

### ISSUE THREAD

**Issue by asthapasta** [adobe/spectrum-css#1389]
## Description
:hover styling is used to set the color of an icon within an `action-button`. However, touchscreen devices are known to have issues with :hover, where the hover state can stick to a button even after deselecting it. That means both a selected and deselected button can have the same icon-color, leading to a confusing user experience. 

## Steps to reproduce
1. Make sure your user-agent is set to a mobile device (for instance, make sure you're using a iPad as your device via Google Dev Tools)
2. Go to [this link](https://photoshop.adobe.com/id/urn:aaid:sc:US:cbcf5e5c-47bb-432c-985c-89abd054b908)  
3. Toggle the comments panel on by clicking the comment icon. 
4. Toggle it off. Notice that the icon is the same color as when it's selected

## Expected behavior
The comments icon should return to its deselected color

## Screenshots
Screenshots and suggestions are in proposal document

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** 

## Additional context
-- [Hover State Proposal.pdf](https://github.com/adobe/spectrum-css/files/8084360/Hover.State.Proposal.pdf)
-- related to [DIWI-427](https://jira.corp.adobe.com/secure/RapidBoard.jspa?rapidView=33182&projectKey=DIWI&view=detail&selectedIssue=DIWI-427)

synced to jira: https://jira.corp.adobe.com/browse/CSS-72

**Comment by castastrophe** [comment]
We are currently using a hover plugin that addresses this: https://www.npmjs.com/package/postcss-hover-media-feature
