### ISSUE TITLE
[Color Handle] Variable resolution

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1394]
https://github.com/adobe/spectrum-css/blob/fd9f01c3179fa3f6cb17d3fc9b30d4837606fd24/components/colorhandle/skin.css#L31

This variable seems to be resolved differently than its usage earlier in the file?

https://unpkg.com/browse/@spectrum-css/colorhandle@2.0.0/dist/index-vars.css#L102
```
  box-shadow: inset 0 0 0 var(--spectrum-colorhandle-outer-border-size, var(--spectrum-alias-border-size-thin)) var(--spectrum-colorhandle-inner-shadow-color, var(--spectrum-colorhandle-outer-shadow-color));
```

VS

https://unpkg.com/browse/@spectrum-css/colorhandle@2.0.0/dist/index-vars.css#L77
```
  box-shadow: 0 0 var(--spectrum-colorhandle-outer-shadow-blur, 0) var(--spectrum-colorhandle-outer-shadow-spread, var(--spectrum-alias-border-size-thin)) var(--spectrum-colorhandle-outer-shadow-color, rgba(0, 0, 0, 0.42));
```

synced to jira: https://jira.corp.adobe.com/browse/CSS-73

**Comment by Westbrook** [comment]
Seems to originate from https://github.com/adobe/spectrum-css/blob/main/components/vars/custom.css which is unexpected on our end. I can work around for now, but not sure if it should be normalized or not.

**Comment by lazd** [comment]
Hmm, a bunch of variables were renamed and repurposed in that latest updates. What is the actual issue on your end here?

**Comment by Deanna-w1** [comment]
I'll add this as a topic to one of syncs when Westbrook is back in office

**Comment by Westbrook** [comment]
For this, we use:
```
var(--spectrum-colorhandle-outer-shadow-color, rgba(0, 0, 0, 0.42))
```
When leveraging `--spectrum-colorhandle-outer-shadow-color` but then when falling back to it, we use:
```
var(
            --spectrum-colorhandle-inner-shadow-color,
            var(--spectrum-colorhandle-outer-shadow-color)
        )
```
So if we callback to `--spectrum-colorhandle-outer-shadow-color` and it’s not set we don’t get `rgba(0, 0, 0, 0.42)`

**Comment by lazd** [comment]
So it looks like this is set for both Express and Spectrum inside of `custom.css`, which gets rolled into `dist/specturm-globals.css` for the `vars`/`expressvars` package here: https://unpkg.com/browse/@spectrum-css/vars@8.0.0-beta.0/dist/spectrum-global.css

As such, it should never be unset? So I'm not sure what's happening here, it should be good to go.

**Comment by lazd** [comment]
Is the problem that the variables reference eachother>?

If we changed this:

```
.spectrum {
  --spectrum-colorhandle-inner-shadow-color: var(--spectrum-colorhandle-outer-shadow-color);
  --spectrum-colorhandle-outer-shadow-color: rgba(0, 0, 0, 0.42);
}
```

To:

```
.spectrum {
  --spectrum-colorhandle-shadow-color: rgba(0, 0, 0, 0.42);
  --spectrum-colorhandle-inner-shadow-color: var(--spectrum-colorhandle-shadow-color);
  --spectrum-colorhandle-outer-shadow-color: var(--spectrum-colorhandle-shadow-color);
}
```

Would that fix it?

**Comment by lazd** [comment]
Looks like we're good here, it was a parser issue on the SWC side.
