### ISSUE TITLE
Core Token to CSS Custom Property format

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#1412]
Consume the [Spectrum Tokens](https://github.com/adobe/spectrum-tokens) and format them as CSS Custom Properties.

synced to jira: https://jira.corp.adobe.com/browse/CSS-70

**Comment by pfulton** [comment]
Pretty sure this was closed by #1430 - but if this was about something else, we can re-open or create a new issue for it.

**Comment by GarthDB** [comment]
Nope, this is closed.
