### ISSUE TITLE
[Picker][quiet][express] Hover displays questionably.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1419]
## Description
When hovering a quiet express picker the visual delivery is awkward.

<img width="97" alt="image" src="https://user-images.githubusercontent.com/1156657/162538638-2d66fd30-7c1a-45fb-bf04-d2a033075ab4.png">

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Switch to express vars
3. Hover one of the theme pickers.

## Expected behavior
Something nice...

**Comment by lazd** [comment]
Totally. I noted this when we did the CSS implementation. We could use a pseudo-element to draw an overlapping rectangle with the hover background color so it's not clipped on the left/right... Quiet is just problematic all-around, honestly.

**Comment by castastrophe** [comment]
It's transparent now which is also not ideal but we'll need to wait for design direction before addressing this further: https://opensource.adobe.com/spectrum-css/?path=/story/components-picker--default&args=isQuiet:!true;isHovered:!true&globals=context:express
