### ISSUE TITLE
Refactor Textfield to be a container with separate icon and input (ala DecoratedTextfield)

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#142]
Rename DecoratedTextfield to something else to match React Spectrum's icon usage

**Comment by lazd** [comment]
This could end up as something like this:

```html
<div class="spectrum-Textfield">
  <input class="spectrum-Textfield-input">
  <svg class="spectrum-Textfield-icon">​
</div>
```

That is, all textfields have a wrapper, and all textfields can have an icon in them that is automatically positioned correctly.

**Comment by lazd** [comment]
It was discussed that error text should go in a surrounding label component.

**Comment by GarthDB** [comment]
Closed with https://github.com/adobe/spectrum-css/pull/537
