### ISSUE TITLE
[fieldgroup] CSS reaches into child component.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1424]
https://github.com/adobe/spectrum-css/blob/92c045f540f2ab3578512abd76c94eda9c6faad6/components/fieldgroup/index.css#L24-L38

The above code reaches into the Checkbox component to apply styles rather the interacting with a CSS Custom Property API surfaced on that component making it difficult to apply in a portable way when pairing this pattern with shadow DOM in SWC.

**Comment by castastrophe** [comment]
This code has since been updated and no longer references nested components directly.
