### ISSUE TITLE
[Button][ActionButton]: Static Color should use a custom property API, not color: inherit to set text color

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#1425]
## Description
Currently, Static Color buttons rely on `color` being set on the outer element to set the text color of the button. This is because this mechanism was created before custom properties were mainstream.

This has two issues:

1. Setting color on an outer element such that its inherited and used within the button is counter-intuitive, and despite it being a fundamental aspect of how CSS behaves, most folks are unaware of this application. Despite documentation, this has confused users before.
2.  The usage of color precludes the newly added design requirement that the default color be `black` or `white` -- it's not possible to say "inherit unless someone says not to" because of the nature of inheritance. 

To address this, we should use a CSS custom property API to define the text color for Static Color buttons, something like `--spectrum-custom-background-color` (as the text is supposed to match the background color) or `--spectrum-custom-static-text-color` (as its actually affecting the text itself).

Using custom property fallbacks, we could easily use a `white`/`black` fallback color with something like:

```
css
.spectrum-Button--staticBlack .spectrum-Button-label {
  color: var(--spectrum-custom-static-text-color, white);
}
```

## Why do you need this feature or component?

Intuitive API, simpler docs, and correct implementation of design requirements.

## Additional context

Customer confused by existing mechanism: https://adobedesign.slack.com/archives/C5N154FEY/p1649805163901619
Slack discussion with design: https://adobedesign.slack.com/archives/G019JTYMT6H/p1649861392969419

**Comment by castastrophe** [comment]
This issue appears to be out of date. This is the current solution for text color in action button:

```
.spectrum-ActionButton.spectrum-ActionButton--staticWhite {
  --spectrum-actionbutton-content-color-default: var(--spectrum-white);
}

.spectrum-ActionButton {
  color: var(--highcontrast-actionbutton-content-color-default, var(--mod-actionbutton-content-color-default, var(--spectrum-actionbutton-content-color-default)));
}
```

* Example above exists between the theme layer (theme/*.css) and the source css (index.css) and is simplified to focus on just the relevant parts setting the value.
