### ISSUE TITLE
[Treeview] Hovering an item make icons dissapear.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1428]
## Description
Hovering an item with an icon gives the icon the same color as the background, or something.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/treeview.html#foldersfiles
2. Hover one of the items with an icon
3. Observe the icon become "invisible"

## Expected behavior
Icon should have a suitable hover color.

## Screenshots
<img width="279" alt="image" src="https://user-images.githubusercontent.com/1156657/164737540-02ea0c35-b3a6-4763-b301-8f0f688b4952.png">

synced to jira: https://jira.corp.adobe.com/browse/CSS-205

**Comment by Westbrook** [comment]
Whoops, this isn't about color, it's about the use of the `:before` pseudo element is `position: absolute` which places it _over_ the icon when the hover state is activated.

**Comment by pfulton** [comment]
I noticed this, too, and I've fixed it in my WIP Tree View branch, which (as you know) has been temporarily de-prioritized. We'll be sure to get this in, though.

**Comment by mscherotter** [comment]
Any word on when this might be fixed?
