### ISSUE TITLE
[Treeview] The hover and selection boxes overlap

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1432]
## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/treeview.html#sizing
2. Hover over some of the Tree View Items
3. Observe the selection box and the hover box overlapping in the t-shirt size demos.

## Expected behavior
They don't overlap.

## Screenshots
<img width="315" alt="image" src="https://user-images.githubusercontent.com/1156657/165399964-b60271d3-3076-45eb-bbbf-f62992cc4942.png">

synced to jira: https://jira.corp.adobe.com/browse/CSS-138

**Comment by Deanna-w1** [comment]
Manually copied to Jira here: [CSS-123](https://jira.corp.adobe.com/browse/CSS-123)

Sync to Jira didn't work. @misterbrownlee
