### ISSUE TITLE
Label for Meter and Progress bar should follow the Field-Label sizing

### ISSUE THREAD

**Issue by bernhard-adobe** [adobe/spectrum-css#1433]
## Description
Currently the font-size in Meter / Progress bar have a font-size of 14px in Express. 
It should follow the field-label sizing that is currently using the 12px for size medium for both Express and Spectrum. 

## Steps to reproduce

Toggle the vars source and inspect the font-size and observe the changes from 12 to 14px.
https://opensource.adobe.com/spectrum-css/meter.html#variants
https://opensource.adobe.com/spectrum-css/progressbar.html

## Expected behavior
Font-size stays 12px.

## Screenshots
<img width="1297" alt="Screen Shot 2022-04-27 at 12 42 31" src="https://user-images.githubusercontent.com/52184321/165597468-230295cc-cfab-45f9-bd1d-c16db255b44b.png">

## Environment
 - **Spectrum CSS version:**  Express 1.0.2
 - **Browser(s) and OS(s):** every browser everywhere

**Comment by bernhard-adobe** [comment]
fixed in: https://github.com/adobe/spectrum-css/issues/1433. We just need to update CSS

**Comment by castastrophe** [comment]
Updated in the latest build: https://opensource.adobe.com/spectrum-css/?path=/story/components-progress-bar--default&globals=testingPreview:!true
