### ISSUE TITLE
Badge: add styles for additional spec'd features

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-css#1443]
## Description

There are a couple features in the [badge spec](https://spectrum.adobe.com/page/badge/) that aren't implemented yet in CSS:

- [icons](https://spectrum.adobe.com/page/badge/#Icon)
- [fixed placement styling](https://spectrum.adobe.com/page/badge/#Fixed)

## Why do you need this feature or component?

Right now I'm adding these features to the SWC implementation on top of the existing CSS in https://github.com/adobe/spectrum-web-components/pull/2305

![image](https://user-images.githubusercontent.com/364501/170529552-8c9dd561-b1e0-4ecb-aa24-ee754fc1140f.png)

![image](https://user-images.githubusercontent.com/364501/170529517-f2264ed4-cef3-4b3b-88af-a46c451937ff.png)

**Comment by pfulton** [comment]
Completed as part of our migration to `@adobe/spectrum-tokens`
