### ISSUE TITLE
Display p3 color support

### ISSUE THREAD

**Issue by NateBaldwinDesign** [adobe/spectrum-css#1448]
## Description

Implement colors in spectrum-CSS with display-p3 declarations for global Spectrum colors. Implement to display p3 colors for browsers and devices that support display p3.

Display-p3 is a much wider gamut of RGB, producing a much wider set of values and more vivid color. 

## Why do you need this feature or component?

Display-p3 gamut is supported in many desktop and native OS environments. Spectrum colors were evaluated on devices supporting display p3 (Mac OS, Xd). The wide gamut presentation of Spectrum RGB values exhibit the most accurate intent of the color. It would be advantageous to display the p3 colors and gracefully degrade to sRGB. 

## Additional context

Note that RGB values from Spectrum tokens would need to be recalculated for each channel from 0-1 (opposed to 0-255 in sRGB).

For example `color(display-p3(1, 1, 1))` with the fallback of `rgb(255, 255, 255)`

**Comment by castastrophe** [comment]
This is a change that will need to be sourced from the tokens project ideally. Closing this until we're able to prioritize that initiative.
