### ISSUE TITLE
Need apache-2 compatible source code headers in all source files

### ISSUE THREAD

**Issue by filmaj** [adobe/spectrum-css#145]
All source files, other than machine-generated files, need to have the Apache-2 source code header, which you can find here: https://github.com/adobe/starter-repo/blob/master/LICENSE_HEADER.md#javascript-java-c-c-swift-go-objective-c

**Comment by guillermoarellano** [comment]
Hi Fil, 

Is this just for .js files? What are the file types the Apache-2 source code header will apply?

Thanks,
Guillermo

**Comment by filmaj** [comment]
I think CSS, JS, YAML - anything that can handle comments and is not machine generated.

**Comment by filmaj** [comment]
Going to reopen this issue as, unfortunately, we'll need these headers in CSS as well. I understand that that's a big pain in the butt for this project, and I'm sorry 😞 but the Open Source Office's legal counsel insist we need this in place.

I don't think this is massive priority but we should get this done at some point. Let me know, maybe I can take a stab at a first-pass PR if I can wiggle some time out, I could probably take a cut at it on Monday...

**Comment by GarthDB** [comment]
@lazd Would you be able to create a gulp task that can rip these headers out as it is processing it?

**Comment by lazd** [comment]
@GarthDB on it. I'll use @guillermoarellano's PR + and will add a task to rip the headers out after the build.

**Comment by lazd** [comment]
This issue is still open until comment stripping in output is up to snuff.

**Comment by filmaj** [comment]
Y'all rock, thanks for tackling this!

**Comment by lazd** [comment]
Blocked by https://github.com/Topdoc/postcss-topdoc/pull/4
