### ISSUE TITLE
[Picker]: quiet variant has wrong focus-ring

### ISSUE THREAD

**Issue by bernhard-adobe** [adobe/spectrum-css#1455]
### Expected Behaviour

For Spectrum Express, the picker should featured the focus-border in the bottom of the quiet variant Picker, not a focus-ring
![image](https://user-images.githubusercontent.com/52184321/173404557-eea984e6-19d9-4106-83a7-4249a31bbe8f.png)

### Actual Behaviour
![Uploading image.png…]()

### Reproduce Scenario (including but not limited to)
key -focus on quiet picker: https://opensource.adobe.com/spectrum-css/picker.html#quiet

#### Steps to Reproduce
key-focus

#### Logs taken while reproducing problem

synced to jira: https://jira.corp.adobe.com/browse/CSS-162

**Comment by jnurthen** [comment]
https://github.com/adobe/spectrum-css/pull/1458 will resolve this
