### ISSUE TITLE
[clearbutton]: Correct WHCM styling for search clear button in search input UI

### ISSUE THREAD

**Issue by PreetiNagal** [adobe/spectrum-css#1461]
### Expected Behaviour
Search clear button should not overlap with search input text field

### Actual Behaviour
Search clear button overlaps with search input text field causing UI experience doesn't look  good. @jnurthen 

### Reproduce Scenario (including but not limited to)
check search input UI experience in WHCM

#### Platform and Version
Windows and all

#### Logs taken while reproducing problem

synced to jira: https://jira.corp.adobe.com/browse/CSS-203

**Comment by jnurthen** [comment]
--spectrum-clearbutton-fill-background-color: ButtonFace;
    --spectrum-clearbutton-fill-background-color-disabled: ButtonFace;
    --spectrum-clearbutton-fill-background-color-down: ButtonFace;
    --spectrum-clearbutton-fill-background-color-hover: ButtonFace;
    --spectrum-clearbutton-fill-background-color-key-focus: ButtonFace;
should all be transparent not ButtonFace.

@pfulton I suggest this can wait until the core token work.

**Comment by castastrophe** [comment]
This has been addressed and is corrected in the latest version.
