### ISSUE TITLE
[Swatch|Swatch Group] First Swatch selected interacts poorly with `display: inline-flex`

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1463]
## Description
`display: inline-flex` _sometimes_ adds the trailing "space", but selecting the first Swatch in the Swatch Group causes the "space" to collapse.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/swatchgroup.html#density-compact
2. Add a `<div>` with content AFTER the `.spectrum-SwatchGroup` element
3. Remove the width of the `.spectrum-SwatchGroup` element, so the Swatches all display on a single row.
4. Add `.is-selected` to the FIRST Swatch element.
5. See the "space" between the Group and the `<div>` change.

## Expected behavior
Default styles are not effected by the selection of Swatches in the group.

## Screenshots
With selection:
<img width="796" alt="image" src="https://user-images.githubusercontent.com/1156657/176474722-2be2be1b-8c2d-461c-b27d-39dbc9b34611.png">

Without selection:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/1156657/176474835-62c19c54-3292-41c1-80e8-a0fe71b91127.png">

synced to jira: https://jira.corp.adobe.com/browse/CSS-202

**Comment by pfulton** [comment]
I think this has been fixed on our end, but if it persists, please open a new issue.

With selection:
<img width="747" alt="Screenshot 2023-05-19 at 2 27 11 PM" src="https://github.com/adobe/spectrum-css/assets/360251/98e41ac5-fef7-42d7-ae47-5f29e783497d">

Without selection:
<img width="708" alt="Screenshot 2023-05-19 at 2 28 22 PM" src="https://github.com/adobe/spectrum-css/assets/360251/56e7f663-0c6d-48a8-98e8-ceaaa67fe2d5">
