### ISSUE TITLE
[Switch] Use of "z-index" interacts poorly with custom layout engines

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1473]
## Description
See https://github.com/adobe/spectrum-web-components/issues/2405 and https://jira.corp.adobe.com/browse/VEN-3548

The use of `z-index` in this line https://github.com/adobe/spectrum-css/blob/main/components/switch/index.css#L63 can cause custom layout engines that rely on `position: absolute` to place the `<input>` on a different `z` level than the actual interface.

It look like this is because the `<input>` goes first in the code order, so as to leverage its state while styling. This same effect could be achieved by leveraging the `<label>` which is at the end of the DOM here, in a similar way, but instead of placing it on a new z-index, giving it padding to appropriately hold open the pattern and allowing it being last in the DOM and bound to the input via the `for` attribute to facilitate the same result.

synced to jira: https://jira.corp.adobe.com/browse/CSS-219

**Comment by Deanna-w1** [comment]
Synced this to Jira
