### ISSUE TITLE
WHCM for Divider

### ISSUE THREAD

**Issue by PreetiNagal** [adobe/spectrum-css#1474]
## Description
Divider is not getting handled in High Contrast mode, is this expected?

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Search for divider and enable high contrast mode
3. Observe

## Expected behavior
Divider should be visible in high contrast mode

## Screenshots
<img width="1344" alt="divider_HC" src="https://user-images.githubusercontent.com/93984110/178417668-de3299cf-ea62-4227-86c8-91fd516cfddb.png">

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by pfulton** [comment]
@PreetiNagal thank you for reporting this. It'll be addressed in #1490
