### ISSUE TITLE
NPM is unable to resolve actionbutton with breadcrumbs

### ISSUE THREAD

**Issue by davidkudera** [adobe/spectrum-css#1498]
## Description
`@spectrum-css/breadcrumbs` can not be installed alongside `@spectrum-css/actionbutton`. This affects new projects as well as running `npm ci` on existing projects.

It looks like the same problem that was happening here - https://github.com/adobe/spectrum-css/issues/1450

## Steps to reproduce

1. `npm install --save @spectrum-css/actionbutton` - installs version 2.1.2
2. `npm install --save @spectrum-css/breadcrumb`

**output:**

```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @spectrum-css/actionbutton@2.1.2
npm ERR! node_modules/@spectrum-css/actionbutton
npm ERR!   @spectrum-css/actionbutton@"^2.1.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @spectrum-css/actionbutton@"^1.1.13" from @spectrum-css/breadcrumb@5.0.0
npm ERR! node_modules/@spectrum-css/breadcrumb
npm ERR!   @spectrum-css/breadcrumb@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## Expected behavior
To be able to install multiple `@spectrum-css/*` packages within one project.

## Environment
 - **node:** 16.16.0
 - **npm:** 8.11.0

**Comment by castastrophe** [comment]
This should now be fixed, please let us know if you run into this again. Thanks for reaching out!
