### ISSUE TITLE
[docs]: Code overflows parent container

### ISSUE THREAD

**Issue by andrewdoro** [adobe/spectrum-css#1525]
## Description

Code overflows the parent container.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/get-started.html
2. Change window width to less than 842px
3. Observe code overflow

## Expected behavior

A good solution would be to add `overflow: auto` to the pre tag. Just assign me to this and I can work on it.

## Screenshots

![image](https://user-images.githubusercontent.com/17547035/194567382-4350944d-605a-4d15-b1ea-0efef7c15e9b.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by castastrophe** [comment]
This is corrected with the release of our updated docs site: https://opensource.adobe.com/spectrum-css/?path=/docs/guides-contributing--docs
