### ISSUE TITLE
tabs: "quiet" lack of border is applied to vertical, compact tabs

### ISSUE THREAD

**Issue by hunterloftis** [adobe/spectrum-css#1526]
## Description

Re: conversation w/ @pfulton and PJ, vertical compact should have a border, but currently doesn't:

https://opensource.adobe.com/spectrum-css/tabs.html#compactverticaltabs

## Screenshots

![image](https://user-images.githubusercontent.com/364501/194618029-a9ec0f81-957c-48c5-853b-2fefcf73d742.png)

I'm adding this issue to track, so I can override it temporarily in Spectrum Web Components & then delete the override once this is 👍

**Comment by pfulton** [comment]
closed via #1902
