### ISSUE TITLE
[docs]: Switcher UI enhancement

### ISSUE THREAD

**Issue by adsingh14** [adobe/spectrum-css#1536]
## Description

1. Open [this link](https://opensource.adobe.com/spectrum-css/accordion.html)
2. On desktop, switcher should stay on the top while scrolling.
3. On mobile and tablet, it should attach with 'toggle-settings' button adjacent to navigation 'hamburger icon'. 

## Why do you need this feature or component?

Switcher goes off screen on scrolling the content section. That should stay on the top after scrolling.

## Additional context

![image](https://user-images.githubusercontent.com/35252877/197804367-c59ecf27-0dc9-43da-9e12-fe06da28b04c.png)

**Comment by castastrophe** [comment]
This has been updated with the release of our updated docs site: https://opensource.adobe.com/spectrum-css/
