### ISSUE TITLE
[docs]: Copy button in code markup section

### ISSUE THREAD

**Issue by adsingh14** [adobe/spectrum-css#1537]
## Description

1. Visit [this link](https://opensource.adobe.com/spectrum-css/helptext.html).
2. In 'Markup' section, there should be a 'Copy text' or 'Copy icon' button on top-right corner.

## Why do you need this feature or component?

Some sections are having multiple code blocks which take much time if we need to copy the whole section manually. For example, take [Accordion](https://opensource.adobe.com/spectrum-css/accordion.html) section, having a 'Copy' button can save much time.

## Additional context

I have marked yellow dot (in the attachment.

![image](https://user-images.githubusercontent.com/35252877/197806494-bbb6a560-3f6a-4b1e-be6e-c58968a72787.png)

**Comment by castastrophe** [comment]
Great suggestion. @Rajdeepc, I found this plugin you might consider including that would add the copy link to the code snippets: https://www.npmjs.com/package/eleventy-plugin-code-clipboard

**Comment by adsingh14** [comment]
I would also like to contribute if assigned.

**Comment by castastrophe** [comment]
@adsingh14 That's wonderful! At the moment @Rajdeepc is working on a rewrite of our documentation site to use 11ty so we would want to hold off adding new features until the migration is complete. We'll definitely reach out though after if the feature hasn't yet been implemented.

**Comment by adsingh14** [comment]
@castastrophe I visited the documentation and the 'copy code' button is still missing.

**Comment by castastrophe** [comment]
Yes, the documentation rework has not yet been merged. I'll update the ticket when that work is published.

**Comment by castastrophe** [comment]
https://opensource.adobe.com/spectrum-css/
