### ISSUE TITLE
Windows: Lower pixels of text cropped in H2 dialog titles with CJK text

### ISSUE THREAD

**Issue by peller** [adobe/spectrum-css#155]
### Expected Behavior
Chinese text should be fully visible

### Actual Behavior
Bottom pixel or two is missing on Windows only.  It's subtle, especially for those who don't know the language!

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
IE11/Win10

#### Spectrum-CSS version
whatever react-spectrum 2.20.0 is using

#### Screenshots (if applicable)
![Select files to share](https://user-images.githubusercontent.com/46139/57541156-61e22580-731c-11e9-8be8-b9caa2d8d2b9.png)

**Comment by peller** [comment]
text in that title is 选择要共享的文件

**Comment by lazd** [comment]
This may be fixed by #176, we need to test.

**Comment by lazd** [comment]
@peller Is this using a specific font family for the CJK text, or is this just normal Adobe Clean? Which Typekit ID is being used, and what is the `lang` attribute set to?

**Comment by peller** [comment]
@lazd the problem can be seen on documentcloud.adobe.com where we are still using the default react-spectrum typekit (adobe clean and whatever it falls back to on IE11 for Chinese glyphs), though it will be fixed shortly when we deploy han-japanese-specific fonts with our new custom typekit.

**Comment by peller** [comment]
@lazd see DCTD-921 and its Firefox-based cousin DCTD-1526

**Comment by lazd** [comment]
@peller ok, from your comment it sounds like fixing https://github.com/adobe/spectrum-css/issues/183 would fix this, yes?

**Comment by peller** [comment]
@lazd yes, that fixed it for us.  If you can assume the use of adobe-han fonts, this problem seems to go away.
