### ISSUE TITLE
Slider Down state

### ISSUE THREAD

**Issue by bengfarrell** [adobe/spectrum-css#1583]
## Description
I just happened to see a bug filed with the slider on Spectrum Web Components
https://github.com/adobe/spectrum-web-components/issues/2836

I referred back to Spectrum CSS, and indeed the down state of the slider thumb doesn't activate on 
https://opensource.adobe.com/spectrum-css/slider.html

Unfortunately, the down state is not on the spec on the web page (nor are any interactive states mentioned really)

However this state is clearly defined in the XD UI Kit specs

## Steps to reproduce

Visit 
https://opensource.adobe.com/spectrum-css/slider.html

Notice that the slider thumb, when interacting does not fill with a black/down color

## Expected behavior
It should visually look like my screenshot posted from the XD UI Kit

## Screenshots

UI Kit screen shot:
![Screen Shot 2023-01-12 at 9 44 25 AM](https://user-images.githubusercontent.com/1298188/212141741-dafabe27-99c4-4688-b4d2-4c622cf5cd49.png)

**Comment by bernhard-adobe** [comment]
Thank you @bengfarrell for pointing this out. 
The active state is indeed missing from the current Slider in Spectrum CSS and the Spectrum XD file is correct.

I have added in the PR #1547.
![2023-01-20_10-23-40 (1)](https://user-images.githubusercontent.com/52184321/213770948-54ae94c2-beaa-4ed8-9d45-729b8ab9730f.gif)
