### ISSUE TITLE
Make Travis keep the build output

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#159]
### Expected Behavior

We have build output we can link to for testing purposes, including visual regression testing reports.

### Actual Behavior

Travis throws it away.

#### Steps to Reproduce

1. See https://travis-ci.org/adobe/spectrum-css

### Notes

Apparently the answer lies here https://docs.travis-ci.com/user/deployment/

**Comment by GarthDB** [comment]
Where are you thinking it would store the built files?

**Comment by lazd** [comment]
@GarthDB haven't thought that far, but it would be very helpful in reviewing pull requests from a design standpoint.

**Comment by lazd** [comment]
@jianliao sounds like the Jenkins implementation you demoed today does something similar to this... I wonder if we can close this issue?

**Comment by lazd** [comment]
@jianliao can you comment on where build output is now?

**Comment by jianliao** [comment]
I think I might misunderstand the requirement here. Right now, we can keep the visual regression test result in adobe internal jenkins server. But this ticket is asking for keeping travis-ci build output.

**Comment by jianliao** [comment]
If keeping the build output is just for review the VR test result, the answer would be:
1. Go to adobe internal spectrum visual regression jenkins server
2. Start a job named `spectrum-css-vr-test-asset`. you can specify the repo url and branch with build parameters:
![image](https://user-images.githubusercontent.com/1207520/68423823-a594db00-0157-11ea-8a3e-a415b3039593.png)
3. After the job is done, review the VR test result in build artifact. 
![image](https://user-images.githubusercontent.com/1207520/68423912-d07f2f00-0157-11ea-8fac-98ee7205ffcf.png)

But all of these is just for Adobe employee.

**Comment by lazd** [comment]
Officially closed by #623 🎉
