### ISSUE TITLE
[Textfield]: Size Small

### ISSUE THREAD

**Issue by Andres6936** [adobe/spectrum-css#1592]
## Description
Is it possible to use a sizeS for textfields? The documentation does not mention being able to apply CSS to reduce the size of the textfield, and it currently creates inconsistency with other widgets.

## Screenshots
![localhost_5173_search(iPhone 5_SE)](https://user-images.githubusercontent.com/18540634/213876646-92fb6386-81dc-47a9-82e0-107478ef04f0.png)

**Comment by pfulton** [comment]
@Andres6936 You're correct: currently there is no way to use `--sizeS` in the TextField component. We're currently in the process of migrating our components to a new tokens system, and the updated version of TextField _will_ support t-shirt sizing after that component is migrated.

We have a PR open for that work here: https://github.com/adobe/spectrum-css/pull/1544 - we hope to have that PR merged soon.
