### ISSUE TITLE
Rename is-dragged to something else

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#160]
The state `.is-dragged` right now means that something is dragged over the element. Intuitively, `.is-dragged` sounds more like the element itself is being dragged. We need to rename this to something that makes more sense, such as `is-draggedOver` (which also might be just as bad).

This will affect Breadcrumbs and Dropzone. Note that `is-dragged` is used within Slider as well, but with the intuitive definition.

synced to jira: https://jira.corp.adobe.com/browse/SDS-7331

**Comment by misterbrownlee** [comment]
was `blocked by design`
