### ISSUE TITLE
[bug][checkbox] emphasized indeterminate checkbox has wrong color

### ISSUE THREAD

**Issue by mrtnbroder** [adobe/spectrum-css#1617]
## Description

If you uncheck an emphazied indeterminate checkbox, it shows in grey. Not entirely sure this is correct, but it looks wrong imo. Emphasized indeterminate checkboxes should stay emphasized, no matter it's checked state.

## Steps to reproduce

1. Go to [Emphasized](https://opensource.adobe.com/spectrum-css/checkbox.html#emphasized)
2. Click on Emphasized - Default - Checkbox that is indeterminate
3. Observe that it turns gray.

## Expected behavior

it should stay emphasized.

## Screenshots

![Screenshot 2023-02-09 at 16 18 21](https://user-images.githubusercontent.com/1118826/217855153-45cc44fa-d8b1-4af2-91f2-5da70e8474f6.jpg)

## Environment
 - **Spectrum CSS version:** 6.0.1
 - **Browser(s) and OS(s):** -

**Comment by jawinn** [comment]
Closing as this issue no longer exists in `main`. It most likely was fixed in version 7.0.0 (related fixes in #2052).
