### ISSUE TITLE
Should ActionBar sticky/fixed be named something else?

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#163]
Currently, ActionBar has a `--sticky` modifier to indicate that it stays the same place within the table as it scrolls, and a `--fixed` modifier that indicates it will stay the same place on the page. These are very much CSS-influenced names that are unintuitive to the unenlightened, should we name them something more descriptive?

synced to jira: https://jira.corp.adobe.com/browse/CSS-140

**Comment by GarthDB** [comment]
[ ] Check in with content strategy

**Comment by misterbrownlee** [comment]
Was `blocked by design`

**Comment by misterbrownlee** [comment]
retrying jira sync 🙄

**Comment by misterbrownlee** [comment]
Closing this, it's tracked in Jira
