### ISSUE TITLE
Drop `:invalid` input style

### ISSUE THREAD

**Issue by alexdixon** [adobe/spectrum-css#164]
### Expected Behavior
I'd like to be able to use HTML5 validation features on an <input> tag without aggressively styling the input as invalid while it's still focused.

### Actual Behavior

If I try to use HTML5 validation, the input will show as invalid as soon as it's in an invalid state.

### Reproduce Scenario

Try using a typed html field (like e-mail):
<input type="email" class="spectrum-Textfield" />

If you start typing an e-mail address in that field, it'll display the invalid styling until a valid e-mail address is in. This is because you're styling the `:invalid` state, and HTML5 is aggressive about adding that state. It'd be better to just rely on clients explicitly adding the `is-invalid` class when they want the invalid styling to apply.

**Comment by lazd** [comment]
@alexdixon I'm working on this as part of #537, and I'm working under the assumption that both `:invalid` and `:valid` have to go, in favor of `.is-invalid` and `.is-valid` respectively. Doest this match your expectation?
