### ISSUE TITLE
Header, Heading, and Title

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#167]
## Accordion

* `h3.spectrum-Accordion-itemHeading` ->`.spectrum-Accordion-itemHeader`
* `button.spectrum-Accordion-itemHeader` ->`.spectrum-Accordion-itemTitle`

## Illustrated Message

* `spectrum-IllustratedMessage-heading` -> `.spectrum-IllustratedMessage-title`

## Popover/Dialog/Coachmarks

* `title` remains as-is

## Menu

* new: `.spectrum-Menu-header`, contains `.spectrum-Menu-title`
* new: `.spectrum-Menu-sectionHeader`, contains `.spectrum-Menu-sectionTitle`

## Sidenav

* new: `.spectrum-SideNav-sectionHeader`, contains `.spectrum-SideNav-sectionTitle`
* `h2.spectrum-SideNav-heading` -> `.spectrum-SideNav-sectionTitle`

**Comment by Patil2099** [comment]
@lazd Can I work on this issue? Can you explain it a bit more?

**Comment by misterbrownlee** [comment]
This feedback for design on an contribution component.  We will work out the correct structure and names then, so we don't need this issue now to track.
