### ISSUE TITLE
TextField ValidationIcon not showing properly due to "box-sizing: border-box"

### ISSUE THREAD

**Issue by tadeualencar** [adobe/spectrum-css#1677]
## Description
TextField Validation State Icon not showing properly due to CSS 'box-sizing'. It's exactly the same problem happened to TreeView(fixed by https://github.com/adobe/spectrum-css/pull/487) where Validation Icon is not showing properly due to CSS `box-sizing: border-box` where should be "content-box".

When you add following CSS problem is solved:

`.spectrum-Textfield-validationIcon {
  box-sizing: content-box;
}`

## Steps to reproduce

1. Just add any TextField with ValidationState on any next.js app
2. Observe cropped valid and invalid icons

## Environment
 - **Spectrum CSS version:** 3.25.1
 - **Browser(s) and OS(s):** Chrome 111.0.5563.65 on Win 11

**Comment by castastrophe** [comment]
I'm not seeing any issues on our current implementation: https://opensource.adobe.com/spectrum-css/?path=/docs/components-text-field--docs&args=isInvalid:!true

Feel free to reopen if this is still a problem.
