### ISSUE TITLE
Broken Preview Link (404)

### ISSUE THREAD

**Issue by GuillaumeCleme** [adobe/spectrum-css#1698]
## Description
Both the ReadMe and Site index point to https://opensource.adobe.com/preview but this page results in a GitHub Pages 404. I would have love to contribute a PR but I was unable to locate where the preview link should point to or to find any traced of it being moved or deleted in the source.

## Link to documentation
- ReadMe: https://github.com/adobe/spectrum-css/blob/main/README.md?plain=1#L13
- Site Nav: https://github.com/adobe/spectrum-css/blob/main/site/includes/nav.pug#L24

**Comment by pfulton** [comment]
Thanks, we appreciate you raising this issue! We've resolved this.
