### ISSUE TITLE
Update README, remove git.corp references

### ISSUE THREAD

**Issue by filmaj** [adobe/spectrum-css#17]
The "importing icons", "remote testing with the test server" and "learn more" sections of the README reference git.corp URLs.

**Comment by filmaj** [comment]
Just doing a further scan of the readme. What about the section around internal dependencies? It references a `spectrum-css-deps` thing. Is this still a thing?

**Comment by GarthDB** [comment]
It is but just for internal people. Public people won’t mess with the internal deps for icons and such.

**Comment by stevengill** [comment]
It is a thing! It is where internal deps got moved to. We have a build & copy step in that repo that updates the checked in `vars` and `icons` directories in this repo

**Comment by GarthDB** [comment]
@filmaj was this closed with https://github.com/adobe/spectrum-css/pull/19 ?

**Comment by filmaj** [comment]
Hmm, we didn't remove the internal links, but we did annotate them. Not sure if worth keeping this issue open until we axe those internal links, or if annotating them is good enough. Your call.

**Comment by GarthDB** [comment]
We are going to leave mentions of internal stuff.
