### ISSUE TITLE
Custom property that passes through and changes font-family

### ISSUE THREAD

**Issue by iooi** [adobe/spectrum-css#1703]
## Description

Use a custom property that passes through and changes font-family. This may need to happen on the Spectrum CSS side. instead of changing font-family in [the code here](https://github.com/adobe/spectrum-css/blob/113b059d6d536ada79286a8ecc36d5aaa5e079d9/components/typography/font.css#L41), they could defined `--spectrum-current-font-family`, and then any element that sets font-family can refer to that variable.

**Comment by castastrophe** [comment]
We offer `--spectrum-sans-font-family-stack` and `--spectrum-serif-font-family-stack` that allows for customization.
