### ISSUE TITLE
Is this project "usable"?

### ISSUE THREAD

**Issue by MohaElder** [adobe/spectrum-css#1720]
## Description

I tried following both [Adobe's Getting Started](https://opensource.adobe.com/spectrum-css/get-started.html) and [Getting Started in this Repo](https://github.com/adobe/spectrum-css#readme). Neither of them works. Css does load correctly, but only **partially** correctly. There is tons of variables that cannot be found(e.g: var(--system-spectrum-button-accent-background-color-default)), preventing even the Getting Started code to show corretly. 

I love how Spectrum CSS works, especially how well its guideline tells people to design ARIA friendly websites. But right now I am confused on setting up even the Getting Started website :( Not sure if this issue only happens with me.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/get-started.html
2. Follow along the demo code which would get you 
```
<html class="spectrum spectrum--light spectrum--medium">
  <head>
    <link rel="stylesheet" href="node_modules/@spectrum-css/vars/dist/spectrum-global.css">
    <link rel="stylesheet" href="node_modules/@spectrum-css/vars/dist/spectrum-medium.css">
    <link rel="stylesheet" href="node_modules/@spectrum-css/vars/dist/spectrum-light.css">
    <link rel="stylesheet" href="node_modules/@spectrum-css/page/dist/index-vars.css">
    <link rel="stylesheet" href="node_modules/@spectrum-css/button/dist/index-vars.css">
  </head>
  <body>
    <button class="spectrum-Button spectrum-Button--fill spectrum-Button--accent spectrum-Button--sizeM">
      <span class="spectrum-Button-label">Button</span>
    </button>
  </body>
</html>
```
4. You will see that this index.html actually does not render correctly: the button has **no** color because the color variable is not found.

## Expected behavior

The button's color should be showing up correctly.

## Screenshots

<img width="521" alt="image" src="https://user-images.githubusercontent.com/20946504/229566124-d945c8bd-0a83-47a7-b971-ab0181d199a5.png">

## Environment
 - **Spectrum CSS version:** 3.0.0
 - **Browser(s) and OS(s):** Chrome on Win11

**Comment by jpamarohorta** [comment]
Hello, I was having the same issue and `<link rel="stylesheet" href="node_modules/@spectrum-css/tokens/dist/index.css">` solved it. I hope it helps!

**Comment by MohaElder** [comment]
Thanks for the comment! Unfortunately because of this issue I eventually decided to use Bootstrap ;(. But thanks for the solution! I'm sure that this will work as including the token following ReadMe.md does result in file not found issue. Many thanks!
