### ISSUE TITLE
Error Resolving dependency tree with accordion

### ISSUE THREAD

**Issue by mscherotter** [adobe/spectrum-css#1790]
## Description
Running NPM update I get an error resolving the dependency tree.

PS D:\Source\Repos\gallery\web> npm update
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: galeryst@1.0.3
npm ERR! Found: @spectrum-css/vars@8.0.5
npm ERR! node_modules/@spectrum-css/vars
npm ERR!   @spectrum-css/vars@"^8.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @spectrum-css/vars@">=9.0.0" from @spectrum-css/icon@3.0.38
npm ERR! node_modules/@spectrum-css/icon
npm ERR!   @spectrum-css/icon@"^3.0.23" from the root project
npm ERR!   peer @spectrum-css/icon@"^3.0.0" from @spectrum-css/accordion@3.0.39
npm ERR!   node_modules/@spectrum-css/accordion
npm ERR!     @spectrum-css/accordion@"^3.0.24" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\syner\AppData\Local\npm-cache\eresolve-report.txt for a full report.

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Click on ...
3. Observe ...

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** 

## Additional context

# npm resolution error report

2023-04-19T16:19:03.604Z

While resolving: galeryst@1.0.3
Found: @spectrum-css/vars@8.0.5
node_modules/@spectrum-css/vars
  @spectrum-css/vars@"^8.0.0" from the root project

Could not resolve dependency:
peer @spectrum-css/vars@">=9.0.0" from @spectrum-css/icon@3.0.38
node_modules/@spectrum-css/icon
  @spectrum-css/icon@"^3.0.23" from the root project
  peer @spectrum-css/icon@"^3.0.0" from @spectrum-css/accordion@3.0.39
  node_modules/@spectrum-css/accordion
    @spectrum-css/accordion@"^3.0.24" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "@spectrum-css/vars",
    "version": "8.0.5",
    "whileInstalling": {
      "name": "galeryst",
      "version": "1.0.3",
      "path": "D:\\Source\\Repos\\gallery\\web"
    },
    "location": "node_modules/@spectrum-css/vars",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "prod",
        "name": "@spectrum-css/vars",
        "spec": "^8.0.0",
        "from": {
          "location": "D:\\Source\\Repos\\gallery\\web"
        }
      }
    ]
  },
  "currentEdge": {
    "type": "prod",
    "name": "@spectrum-css/vars",
    "spec": "^8.0.0",
    "from": {
      "location": "D:\\Source\\Repos\\gallery\\web"
    }
  },
  "edge": {
    "type": "peer",
    "name": "@spectrum-css/vars",
    "spec": ">=9.0.0",
    "error": "INVALID",
    "from": {
      "name": "@spectrum-css/icon",
      "version": "3.0.38",
      "whileInstalling": {
        "name": "galeryst",
        "version": "1.0.3",
        "path": "D:\\Source\\Repos\\gallery\\web"
      },
      "location": "node_modules/@spectrum-css/icon",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "prod",
          "name": "@spectrum-css/icon",
          "spec": "^3.0.23",
          "from": {
            "location": "D:\\Source\\Repos\\gallery\\web"
          }
        },
        {
          "type": "peer",
          "name": "@spectrum-css/icon",
          "spec": "^3.0.0",
          "from": {
            "name": "@spectrum-css/accordion",
            "version": "3.0.39",
            "whileInstalling": {
              "name": "galeryst",
              "version": "1.0.3",
              "path": "D:\\Source\\Repos\\gallery\\web"
            },
            "location": "node_modules/@spectrum-css/accordion",
            "isWorkspace": false,
            "dependents": [
              {
                "type": "prod",
                "name": "@spectrum-css/accordion",
                "spec": "^3.0.24",
                "from": {
                  "location": "D:\\Source\\Repos\\gallery\\web"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false
}

**Comment by castastrophe** [comment]
This appears to be an outdated issue.  If you run into this issue again, please feel free to open a new issue with details and we can look into it further from there!
