### ISSUE TITLE
Error resolving dependency tree with typography

### ISSUE THREAD

**Issue by mscherotter** [adobe/spectrum-css#1792]
## package.json
{
  "name": "spectrum-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@spectrum-css/accordion": "^3.0.39",
    "@spectrum-css/actionbutton": "^3.0.29",
    "@spectrum-css/actiongroup": "^3.0.30",
    "@spectrum-css/asset": "^3.0.35",
    "@spectrum-css/button": "^9.1.4",
    "@spectrum-css/buttongroup": "^6.0.32",
    "@spectrum-css/card": "^5.0.17",
    "@spectrum-css/checkbox": "^6.0.17",
    "@spectrum-css/clearbutton": "^1.2.25",
    "@spectrum-css/dialog": "^6.0.34",
    "@spectrum-css/divider": "^2.0.28",
    "@spectrum-css/fieldlabel": "^6.0.18",
    "@spectrum-css/icon": "^3.0.38",
    "@spectrum-css/logicbutton": "^1.2.24",
    "@spectrum-css/menu": "^4.0.20",
    "@spectrum-css/page": "^5.0.22",
    "@spectrum-css/pagination": "^6.0.3",
    "@spectrum-css/picker": "^3.0.5",
    "@spectrum-css/popover": "^6.0.32",
    "@spectrum-css/progressbar": "^3.0.20",
    "@spectrum-css/progresscircle": "^2.0.28",
    "@spectrum-css/quickaction": "^3.0.41",
    "@spectrum-css/radio": "^7.0.17",
    "@spectrum-css/search": "^5.0.3",
    "@spectrum-css/searchwithin": "^4.0.5",
    "@spectrum-css/site": "^3.0.12",
    "@spectrum-css/slider": "^3.1.20",
    "@spectrum-css/splitbutton": "^5.0.31",
    "@spectrum-css/switch": "^3.0.22",
    "@spectrum-css/table": "^4.0.35",
    "@spectrum-css/tabs": "^3.2.37",
    "@spectrum-css/tag": "^5.0.17",
    "@spectrum-css/taggroup": "^3.3.30",
    "@spectrum-css/textfield": "^4.1.8",
    "@spectrum-css/thumbnail": "^2.0.30",
    "@spectrum-css/toast": "^9.0.17",
    "@spectrum-css/tokens": "^8.1.0",
    "@spectrum-css/treeview": "^6.0.35",
    "@spectrum-css/typography": "^5.0.1",
    "@spectrum-css/vars": "^9.0.2"
  }
}

## Steps to reproduce

1. copy package.json to local system
2. run npm install
3. Observe error message

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @spectrum-css/card@5.0.17
npm ERR! Found: @spectrum-css/typography@5.0.1
npm ERR! node_modules/@spectrum-css/typography
npm ERR!   @spectrum-css/typography@"^5.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @spectrum-css/typography@"^4.0.0" from @spectrum-css/card@5.0.17
npm ERR! node_modules/@spectrum-css/card
npm ERR!   @spectrum-css/card@"^5.0.17" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @spectrum-css/typography@4.0.31
npm ERR! node_modules/@spectrum-css/typography
npm ERR!   peer @spectrum-css/typography@"^4.0.0" from @spectrum-css/card@5.0.17
npm ERR!   node_modules/@spectrum-css/card
npm ERR!     @spectrum-css/card@"^5.0.17" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\syner\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\syner\AppData\Local\npm-cache\_logs\2023-04-19T17_16_56_906Z-debug-0.log

## Environment
- NPM Version 9.6.4 on Windows 11

**Comment by castastrophe** [comment]
This appears to be an outdated issue.  If you run into this issue again, please feel free to open a new issue with details and we can look into it further from there!
