### ISSUE TITLE
Tabs TooMany has the wrong focus ring

### ISSUE THREAD

**Issue by snowystinger** [adobe/spectrum-css#187]
### Expected Behavior
Should have a border the entire way around

### Actual Behavior
Only has a border on the bottom

#### Spectrum-CSS version
2.12.0

#### Screenshots (if applicable)
<img width="117" alt="Screen Shot 2019-05-29 at 11 16 23 AM" src="https://user-images.githubusercontent.com/698229/58581029-6905a080-8203-11e9-8583-346668757114.png">
<img width="157" alt="Screen Shot 2019-05-29 at 11 15 57 AM" src="https://user-images.githubusercontent.com/698229/58581030-6905a080-8203-11e9-9c8b-f19e7d601563.png">

**Comment by lazd** [comment]
Yeah, I see what you mean. In addition, the example here is totally broken because the tab indicator overlaps the focus underline: http://opensource.adobe.com/spectrum-css/2.12.0/docs/#tabs---too-many

@NateBaldwinDesign can you comment on this? We're using a Quiet Dropdown here, and it seems that it needs to be some kind of dropdown that we don't actually have.

**Comment by dannify** [comment]
Can we just have this behave the same as a quiet dropdown instead of inventing a new dropdown focus state just for this?

**Comment by NateBaldwinDesign** [comment]
Something else broken in that example is that the height does not match the variant of tabs that it is demonstrating. Standard Tabs are 48px tall, but the example is inheriting the height of the dropdown component. If the dropdown is wrapped in `spectrum-Tabs-item`, the height is inherited correctly for standard and compact variants. The `spectrum-Tabs-item` has the appropriate focus state. Could we simply wrap the dropdown button in a Tabs-item class? (Note, if we do this, the child `spectrum-Dropdown-trigger` class will need to also have `display: block;` to correct alignment)
![image](https://user-images.githubusercontent.com/13972198/58639983-5b105800-82b5-11e9-900e-3258593a3efb.png)

**Comment by snowystinger** [comment]
@NateBaldwinDesign I've updated the PR if you want to play with it

**Comment by lazd** [comment]
This will be fixed when #190 is fixed. Thanks for the report!

**Comment by lazd** [comment]
This was fixed, and then we removed the Tabs too Many example anyway.
