### ISSUE TITLE
[picker] "block" => "inline" mismatch?

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1880]
https://github.com/adobe/spectrum-css/blob/f5262ea9a7d1968223dfcaf90a2af4100f7092b7/components/picker/index.css#L203

Here we see `min-inline-size` set to `block-size`, is that expected?

**Comment by castastrophe** [comment]
@Westbrook I can double check but as I understand it, we're calculating the minimum width based on the size of the height * the multiplier. I believe that's on purpose however I do notice there's no override for min-inline-size either.  Perhaps:

```css
 min-inline-size: var(--mod-picker-inline-size, calc(var(--spectrum-picker-minimum-width-multiplier) * var(--mod-picker-block-size, var(--spectrum-picker-block-size)))); 
```

**Comment by Westbrook** [comment]
I think that makes sense. _If_ the calculation is expected, a `--mod-*` value to ensure we still have full control over the `width` without altering the `height` should cover the bases.

Aside: oy, it is hard to think outloud in logical properties. 🙃
