### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#1896]
Would you consider this a typo?

https://github.com/adobe/spectrum-css/blob/73400d88b4aa7afd535a161eba81a644baf7235f/components/expressvars/custom.css#L24

When spelled `slider` this value would be removed by tooling from the code SWC delivers, but it will stick around in this state.

**Comment by pfulton** [comment]
Yes, that certainly looks like a typo, which is most likely coming from the vars/expressvars data source.

**Comment by castastrophe** [comment]
Ah, it's sourced from our manually curated custom.css vars. I opened a small PR for this but since we already migrated our slider component to the new token system, it's kind of a moot update.
