### ISSUE TITLE
Quiet Dropdown and Quiet Textfield should have a ring on focus, not an underline

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#190]
Based on discussion spurred by #187, the design has changed on these components to have a ring.

**Comment by dannify** [comment]
Is there a timeline for this change? Is there any way we can have this go in for just the dropdown in Tabs-too-many for now?
Alternative for us is to put this css in tabs-too many in react-spectrum as an "override" until it is released in css.

**Comment by lazd** [comment]
@dannify I'd be OK with an override for now, unless @NateBaldwinDesign and friends say it's OK to just make the change in Spectrum CSS before the rest of the UI kits/website are updated to reflect it.

**Comment by lazd** [comment]
It turns out this has some design implications and isn't actually possible for Textfield since we can't use pseudo-elements... We need to think on this more:
![image](https://user-images.githubusercontent.com/201344/59053945-6d573c80-8847-11e9-97fe-79b748faa6b5.png)

Textfield is a disgusting hack that is basically adding padding and using negative margin so it can draw the box-shadow in the right place. The Dropdown simply uses `:before` and draws the box-shadow on that. Disgusting hacks are here: https://github.com/adobe/spectrum-css/tree/quietring

**Comment by lazd** [comment]
This was fixed with the Textfield refactor as part of #615
