### ISSUE TITLE
Update Coach Mark animation

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#194]
Coach Mark's animation tokens were updated: https://paper.dropbox.com/doc/5-Components-DNA-Bits--AeIee7KEyIDGy~tFu0cV6RsUAg-MJOqI3AfGQ6qaDaWfbIrs#:uid=232756176883081984736155&h2=Quick-Actions

https://git.corp.adobe.com/pages/psteele/tool-time/coach.html

**Comment by GarthDB** [comment]
Same as https://github.com/adobe/spectrum-css/issues/195

**Comment by pfulton** [comment]
@GarthDB to look into this. It's possible that the animation values may be hard-coded, instead of their values coming from DSS/core tokens.

**Comment by pfulton** [comment]
We looked into this and it is using the correct values.
