### ISSUE TITLE
Update Quick Actions animation

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#195]
Quick Action's animation tokens were updated: https://paper.dropbox.com/doc/5-Components-DNA-Bits--AeIee7KEyIDGy~tFu0cV6RsUAg-MJOqI3AfGQ6qaDaWfbIrs#:uid=232756176883081984736155&h2=Quick-Actions

https://git.corp.adobe.com/pages/psteele/tool-time/quickaction.html

synced to jira: https://jira.corp.adobe.com/browse/CSS-144

**Comment by GarthDB** [comment]
Decrufting. Seems like it's still an issue. We'll take a look at chat with @LiveMethod.
