### ISSUE TITLE
[Coachmark][a11y]: subtle animation should support prefers-reduced-motion media query

### ISSUE THREAD

**Issue by majornista** [adobe/spectrum-css#1952]
## Description
Coachmark continues to animate subtly despite the prefers-reduced-motion user preference.

## Steps to reproduce

1. Using Chrome, go to https://opensource.adobe.com/spectrum-css/coachmark.html
2. Open Developer Tools > Rendering
3. Under Emulate CSS media feature prefers-reduced-motion, select "prefers-reduced-motion: reduce"

<img width="592" alt="Screen shot of  Developer Tools > Rendering panel with Emulate CSS media feature prefers-reduced-motion picker" src="https://github.com/adobe/spectrum-css/assets/154077/4b0bab1b-0853-4002-b016-6bd371a9e535" />

## Expected behavior

Coachmark elements should not continue to vibrate.

## Screenshots
![Screen Recording showing continuous animation](https://github.com/adobe/spectrum-css/assets/154077/fe54db44-816a-42fb-b8dd-ea3efd30b461)

## Environment

- **Spectrum CSS version:** @spectrum-css/coachmark@5.0.48
- **Browser(s) and OS(s):** Chrome 114.0.5735.106 (Official Build) (arm64) on macOS

## Additional context

- https://www.w3.org/WAI/WCAG21/Understanding/animation-from-interactions
- https://www.w3.org/WAI/WCAG21/Techniques/css/C39

**Comment by pfulton** [comment]
@majornista thank you! We're actively working to migrate this component to the new Spectrum Tokens system, and @jenndiaz is working on it in our current sprint. I added a note in her Jira ticket for the migration, so we'll be sure to get this update in with that work.

**Comment by majornista** [comment]
Thanks!

**Comment by jenndiaz** [comment]
@majornista Do you have a alternative behavior you'd recommend for the element? 
Does just stopping the animation (screenshot) lose too much of the original design or do you think this is okay? 

![Screenshot 2023-06-21 at 2 57 17 PM](https://github.com/adobe/spectrum-css/assets/63808889/15b345be-9c56-4a54-8646-073923a1adca)

**Comment by pfulton** [comment]
@majornista any additional thoughts here with regard to @jenndiaz's comment [above](https://github.com/adobe/spectrum-css/issues/1952#issuecomment-1601674798)? We're getting close to merging and releasing this component and want to be sure that we've addressed everything.

**Comment by jenndiaz** [comment]
Prefers reduced motion styling added to the coach indicator in the S1 migration for Coach Mark 

https://github.com/adobe/spectrum-css/pull/2323/files#diff-8b0768275144772a003e7c7254ed48176d187ad85fd7dcd23c89039529ab54e7R95
