### ISSUE TITLE
Add Toast animation

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#196]
Toast never had animation, and it should: https://git.corp.adobe.com/pages/psteele/tool-time/toast.html

synced to jira: https://jira.corp.adobe.com/browse/CSS-145

**Comment by pfulton** [comment]
We'll look into this one to be sure that it's using the correct token values from DSS (and/or core tokens)

**Comment by misterbrownlee** [comment]
Closing this, it's tracked in jira
