### ISSUE TITLE
Add landing page to website

### ISSUE THREAD

**Issue by stevengill** [adobe/spectrum-css#2]
Let's look at adding a landing page to the website. We should also add some getting started documentation

**Comment by filmaj** [comment]
100% agree.

What would be a minimal hello world example? How do we go from cloning the repo to using it in a basic html page?

**Comment by stevengill** [comment]
Yeah, I think so. I'm looking into publishing spectrum-css to npm right now. So steps for getting started would probably be:
1) npm install @adobe/spectrum-css
2) create a simple `index.html` page that includes the css file
3) add a spectrum component

Any examples of good landing pages we should have? Maybe https://getbootstrap.com/?

**Comment by filmaj** [comment]
Maybe also https://materializecss.com/getting-started.html ?

**Comment by b3u** [comment]
It says you need help. Any design ideas, or do I have free reign here?

**Comment by GarthDB** [comment]
@b3u we are actually working on this right now with an internal designer at Adobe. It should launch in the next couple of weeks.

**Comment by b3u** [comment]
Okay, let me know if there's anything I can do

**Comment by GarthDB** [comment]
@b3u I really appreciate it. Normally I’d push to have the designer post things publicly, but it’s in connected effort with another project that is not yet public.

**Comment by b3u** [comment]
Gotcha

**Comment by filmaj** [comment]
@GarthDB mysterious and exciting!

**Comment by lazd** [comment]
Hey look, we have a landing page: https://opensource.adobe.com/spectrum-css/2.14.0/docs/index.html

There's no real content there, but it's definitely a page. Future releases will have actual content. Closing this!
