### ISSUE TITLE
Migrate issues from internal repo to here

### ISSUE THREAD

**Issue by filmaj** [adobe/spectrum-css#20]
Is that desired?

Also may be blocked by #5 first.

**Comment by stevengill** [comment]
We do want to do this. It is part of the internal [open source migration plan](https://git.corp.adobe.com/Spectrum/spectrum-css/issues/644). I think we are waiting on a review of existing issues (to close ones that aren't going to be copied over). The issue copy script won't copy existing comments on issues sadly.

**Comment by GarthDB** [comment]
I'll do a run through on the internal issues. Larry will jump in as well.

**Comment by GarthDB** [comment]
@stevengill what about issue numbers used in commit messages internally? is that linking all lost forever?

**Comment by stevengill** [comment]
That linking will be lost unfortunately.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GarthDB** [comment]
Shame :(

**Comment by filmaj** [comment]
Using a tool like [git_mover](https://github.com/filmaj/git_mover) works but:

1. you lose old issue numbers / get assigned new random ones
2. you lose all comments
3. whichever personal access key you use to run the script will be the author of the issues

That said, could probably expand the tool to try to address some of this, at least #2 somewhat.
