### ISSUE TITLE
loadIcons script missing

### ISSUE THREAD

**Issue by jenstroeger** [adobe/spectrum-css#204]
According to [the docs](https://github.com/adobe/spectrum-css#importing-icons):

> To get icons, you'll need to use the `loadIcons()` function. This function lives in the `loadicons` project as well as `icons/loadIcons.js` and has the following signature:

Alas, the script is missing in the icons folder. You’re talking about the [adobe/loadIcons]( https://github.com/adobe/loadIcons) script, correct? I think that if you pull that script from the NodeJS repo, that the UMD pattern could be removed.

**Comment by lazd** [comment]
Hey @jenstroeger, yes, https://github.com/adobe/loadIcons is required to pull down the SVG files. The script is redistributed in the `dist/icons/loadIcons.js` file for historical reasons, it seems the docs should be corrected to refer to the `dist/` folder. You can see it here: 
 http://opensource.adobe.com/spectrum-css/2.12.0/icons/loadIcons.js

We could remove the UMD pattern from it, but I don't think it's hurting anything and it makes simplified usage in the browser easy enough.
