### ISSUE TITLE
[Tokens] Value in "Spectrum" theme missing in "Express" theme

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#2162]
`--spectrum-picker-border-width` is available [here](https://unpkg.com/browse/@spectrum-css/tokens@11.3.4/dist/css/spectrum/global-vars.css#L13), but not in the [Express version of this file](https://unpkg.com/browse/@spectrum-css/tokens@11.3.4/dist/css/express/global-vars.css#L12).

If the value is shared between both themes, then shouldn't it exist in [this file](https://unpkg.com/browse/@spectrum-css/tokens@11.3.4/dist/css/global-vars.css) so that it can be discovered in both context?

Currently, when an application is delivered without both themes on the same page, the Express Picker delivers as follows:
<img width="264" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/4a13c6db-39d0-4f0a-8c16-dbf59f97a99f">
Due to the fact that the math in:
https://github.com/adobe/spectrum-css/blob/dec16329ab9e241df6188223485791f986a2dea3/components/picker/index.css#L411
Cannot be completed.

**Comment by pfulton** [comment]
Tracking this in Jira here: https://jira.corp.adobe.com/browse/CSS-595
