### ISSUE TITLE
[Menu][Submenu]: Disabled menu item with submenu does not display correct visuals

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-css#2176]
## Description

When a menu item with a submenu is disabled, the chevron should also appear disabled. 

## Steps to reproduce

1. Go to [Menu storybook](https://opensource.adobe.com/spectrum-css/preview/?path=/story/components-menu--drill-in-submenu&args=isDisabled:!true)
2. Inspect the submenu element in devtools and set `disabled` to `"true"`
3. Observe that while the text of the menu item is greyed out, the chevron remains "active". 

## Expected behavior

The chevron should be greyed out, too. 

## Screenshots

![image](https://github.com/adobe/spectrum-css/assets/44980010/243b9e7d-29ff-4221-aeec-0a674ef41288)
CSS storybook example

![image](https://github.com/adobe/spectrum-web-components/assets/44980010/5bab65b4-ba4c-4ff3-9ad7-efd00a1c09e8)
SWC storybook example

Live [example](https://studio.webcomponents.dev/edit/collection/fO75441E1Q5ZlI0e9pgq/FikFeTXNsYhxAVmCz2f4/src/index.ts?branch=submenu-disabled%40yOBt1947wIZCL9LXYVLsyGBLOok1&p=stories) on Webcomponents.dev

## Environment
Chrome 116.0.5845.187 on Mac OS Ventura 13.5.2

## Additional context
Reported by Stefan Puchta of PSWeb

**Comment by pfulton** [comment]
Tracking this issue in Jira: https://jira.corp.adobe.com/browse/CSS-594
