### ISSUE TITLE
Picker Control is showing checkboxes for all items

### ISSUE THREAD

**Issue by mscherotter** [adobe/spectrum-css#2180]
## Description
The Picker control 7.0.11 is showing a checkbox to the left of each option, even when the is-selected class is not present on the spectrum-Menu-item

## Steps to reproduce
1, Go to <https://opensource.adobe.com/spectrum-css/picker.html#variants>
Notice that all options have a blue checkbox to the left of the text.

## Expected behavior
only options with the is-selected class should show the checkbox.

## Screenshots

![image](https://github.com/adobe/spectrum-css/assets/641702/6e913176-0e81-4d72-89a2-b8227caaf2c7)

## Environment

- **Version of the impacted component(s):** 
- **Browser(s) and OS(s):** 

## Additional context

This can be fixed with the addition of this CSS:

```
ul.spectrum-Menu li.spectrum-Menu-item[role=option] .spectrum-Menu-checkmark{
  visibility: hidden;
}

ul.spectrum-Menu li.spectrum-Menu-item[role=option].is-selected .spectrum-Menu-checkmark{
  visibility:visible;
}

```

**Comment by pfulton** [comment]
This should be resolved via #2226
