### ISSUE TITLE
Slider focused style should support forced-colors: active / WHCM

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-css#2200]
## Description

Passing along a [bug report](https://github.com/adobe/spectrum-web-components/issues/3328) filed in SWC by @majornista. 

 The slider's `focused` style does not match the Spectrum specification.

From [Spectrum's docs site](https://spectrum.corp.adobe.com/page/slider/#Keyboard-focus) (expected): 
![image](https://github.com/adobe/spectrum-css/assets/44980010/28bb3376-707a-4eab-99d4-1d9f3c6c3463)

From [Spectrum CSS](https://opensource.adobe.com/spectrum-css/slider.html) (actual): 
![image](https://github.com/adobe/spectrum-css/assets/44980010/2fbb8945-658d-42fc-aa21-33aec9404fe0)

Additionally, the focus ring does not render with `forced-colors: active` or WHCM. We should also use `highlight` color appropriately for `track`, `fill-color`, and `focused` state. 

In Spectrum's specification for WHCM/`forced-colors: active`: 
![image](https://github.com/adobe/spectrum-css/assets/44980010/52cfd254-1817-47e6-98ee-c73d332bcb24)

In Spectrum CSS for WHCM/`forced-colors: active`:
![image](https://github.com/adobe/spectrum-css/assets/44980010/a5083f8e-aedf-43a2-8ed6-e09677977a51)

**Comment by castastrophe** [comment]
This appears to be corrected in the latest release: https://opensource.adobe.com/spectrum-css/?path=/story/components-slider--default&globals=testingPreview:!true

<img width="925" alt="Screenshot 2024-12-10 at 5 50 13 PM" src="https://github.com/user-attachments/assets/27f614aa-d126-494f-8d84-2b75bc1d4dfd">
