### ISSUE TITLE
fix(treeview) Performance improvement - use display: none instead of visibility: hidden

### ISSUE THREAD

**Issue by lpardosixtosMs** [adobe/spectrum-css#2201]
I'm using spectrum-treeView to write a browser benchmark and noticed that it is using `visibility: hidden` instead of
`display: none` for elements without the `.is-open` class. As far as I know, `display:none` takes the element out of the of the layout, which is better for browser performance, but I'd like to know if you have other reasons to prefer `visibility: hidden`.

**Comment by castastrophe** [comment]
Hi @lpardosixtosMs & welcome! I don't have any history on the decision-making behind the original code you mentioned but we can certainly add a ticket to our backlog to take a look and improve it. Thank you for highlighting this for us, very helpful!

**Comment by pfulton** [comment]
Tracking this in Jira, via [CSS-603](https://jira.corp.adobe.com/browse/CSS-603)

**Comment by pfulton** [comment]
Closed via the merging of #2218
