### ISSUE TITLE
[In-field Button]: Focus loupe does not conform to the shape of the button

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#2232]
## Description
When using any of the position modifying classes with the In-field Button the various configurations lead to the border radius changing in various ways. This alteration to the border radius is not mirrored in the focus loupe for the element.

## Steps to reproduce

1. Go to [<http://opensource.adobe.com/spectrum-css/>](https://opensource.adobe.com/spectrum-css/infieldbutton.html#stacked)
2. Tab around to focus on the non-quiet buttons. This is most visibly disruptive in the stacked buttons that have more border radii altered
3. Observe the button having _some_ square corners but the focus loupe having none.

## Expected behavior
The focus loupe should have the same general shape as the item being focused.

## Screenshots

Not focused:
<img width="96" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/3e394273-b9f9-48d8-92eb-1730e76a3e4d">

Focused:
<img width="136" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/b32a28cc-5e8b-431d-8240-94707526a2f5">

---

Not focused:
<img width="104" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/81f3c0e4-2e80-4221-95d3-c72551c17ec3">

Focused:
<img width="86" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/6220f6c6-e378-40ed-abd5-3e5f40cd5ce0">

**Comment by pfulton** [comment]
Tracking this in Jira via [CSS-632](https://jira.corp.adobe.com/browse/CSS-632)
