### ISSUE TITLE
[Stepper]: Selectors reach into classes/element that it does not own

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#2234]
## Description
As seen in https://github.com/adobe/spectrum-css/blob/main/components/stepper/index.css#L216-L224 the CSS for Stepper reaches into the DOM/classes of In-field Button to customize it, rather than leveraging the `--mod-` APIs.

## Steps to reproduce

1. Go to [code](https://github.com/adobe/spectrum-css/blob/main/components/stepper/index.css#L216-L224)

## Expected behavior
Patterns should leverage the `--mod-` APIs surfaced by other patterns rather than reaching into DOM/classes that they do not own.

**Comment by pfulton** [comment]
Tracking this in Jira via [CSS-630](https://jira.corp.adobe.com/browse/CSS-630)
