### ISSUE TITLE
[Stepper]: When "Express" in-field buttons in a Stepper expect no border

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#2235]
## Description
See this code: https://github.com/adobe/spectrum-css/blob/main/components/stepper/themes/express.css#L15

This adds a fatter border to the Express output rather than a thinner one, as seen in the design specs for this pattern

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/stepper.html
2. Switch the "Vars Version" to "Express"
3. Observe the far border on the in-field buttons within the Stepper.

## Expected behavior
Express should exhibit no border on these elments.

## Screenshots

Current:
<img width="161" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/e8c4404c-44e9-4532-b04f-b5b45d256d45">

Expected:
<img width="185" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/22075cfe-1e00-4cef-82b8-2036c3ece815">

**Comment by pfulton** [comment]
Tracking this in Jira at: [CSS-625](https://jira.corp.adobe.com/browse/CSS-625).
