### ISSUE TITLE
[Avatar]: When a "link" displays the same in HCM when default and disabled

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#2236]
## Description
Both the default and disabled variants of the Avatar leverage a yellow outline when delivered in HCM. 

Feels like this would be related to the fact that `<a>` elements can't be `disabled`, so we'd need to delivery synthetic rules to this effect rather than relying on native rules as we might have with a `<button>`.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/avatar.html
2. Turn on high contrast mode
3. Observe both active and disabled avatars have yellow outlines (or the outline appropriate to your version of HCM when a link is active)

## Expected behavior
Likely that the disabled Avatar uses the disabled text color, which is green in other contexts. 
<img width="282" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/eecf0567-3dac-4c15-a4e1-619f5779383e">

## Screenshots

<img width="214" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/bb715d90-a51d-45be-a664-df0aa76ded3b">

**Comment by Westbrook** [comment]
@jnurthen do you have any suggestions in this area?

**Comment by jnurthen** [comment]
If it is disabled it should probably not be rendered as a link. The fact that it takes keyboard focus and changes the hover style is just as much of an issue as the high contrast colour. I don't see any need to change the high contrast colour unless the other issues are also addressed.

**Comment by pfulton** [comment]
@Westbrook @jnurthen Spectrum CSS can remove the link markup from the disabled examples, but downstream consumers would also need to update their markup for this. Does that make sense for us to do, @Westbrook?

**Comment by Westbrook** [comment]
Sounds like a good path here, then there'd be no interactive border and no focus acceptance. Ship it!

**Comment by pfulton** [comment]
Tracking this in Jira via [CSS-627](https://jira.corp.adobe.com/browse/CSS-627)
