### ISSUE TITLE
[Menu]: No longer possible to force a Menu Item not to wrap and instead use ellipsis

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#2237]
## Description
Previously the `spectrum-Menu-itemLabel--wrapping` class could be added to the `spectrum-Menu-itemLabel` element in a Menu Item to prevent it from wrapping and force it to use an ellipsis instead.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/menu.html#textoverflow
2. Add the `spectrum-Menu-itemLabel--wrapping` to a `.spectrum-Menu-itemLabel` element 
3. Observe the wrapping being prevented but an ellipsis not being delivered.

## Expected behavior
Content delivered this way should have an ellipsis.

## Screenshots
<img width="264" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/985999a3-71d3-4393-a7fa-bf331a9a621b">

**Comment by pfulton** [comment]
Tracking this in Jira via [CSS-626](https://jira.corp.adobe.com/browse/CSS-626).

**Comment by Westbrook** [comment]
Seems to track back to the `.spectrum-Menu-itemLabel` element not being `display: block;`?
