### ISSUE TITLE
Combobox focus state is incorrect

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#224]
### Expected Behavior
![image](https://user-images.githubusercontent.com/201344/61840610-9ad36600-ae46-11e9-953d-43b1eacd2c4c.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/201344/61840622-a161dd80-ae46-11e9-89f5-fb35b4ce8a84.png)

#### Spectrum-CSS version

2.13.0

**Comment by TomerPacific** [comment]
@lazd , is this issue still available?

**Comment by lazd** [comment]
@TomerPacific yup! This would be a good first issue to work on.

**Comment by TomerPacific** [comment]
@lazd, if I understand correctly, the issue here with the dropdown is that the first element in the list is blue?

**Comment by lazd** [comment]
@TomerPacific no, it's that there is a blue left border on the button. It should be gray.

**Comment by TomerPacific** [comment]
@lazd, ok. I'll go ahead and fix it.

**Comment by lazd** [comment]
@TomerPacific Hmm, I haven't seen that issue before. I assume you're viewing in Chrome?

**Comment by TomerPacific** [comment]
@lazd , yes

**Comment by lazd** [comment]
Looks like this is no longer an issue -- the design changed to 
![image](https://user-images.githubusercontent.com/201344/76568730-b7242180-646e-11ea-9372-9cebd2013b2c.png)
