### ISSUE TITLE
Table row dropzone examples show extra blue when using custom properties

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#225]
### Expected Behavior

![image](https://user-images.githubusercontent.com/201344/61886781-30a5da00-aeb5-11e9-879e-1b456f21b026.png)
![image](https://user-images.githubusercontent.com/201344/61886786-33a0ca80-aeb5-11e9-83d5-c18a9c0d255a.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/201344/61886770-297ecc00-aeb5-11e9-86e1-ac1ffa4621d2.png)

### Spectrum-CSS version

2.13.0

### Sample Code that illustrates the problem

https://codepen.io/lazd/pen/zgBgmO?editors=1100

### Notes

Problem is only present for custom properties usage:
Correct: http://opensource.adobe.com/spectrum-css/2.13.0/docs/#table---dropzone
Broken: http://opensource.adobe.com/spectrum-css/2.14.0-alpha.8/docs/table-dropzone.html#table-rowdropzonequiet

**Comment by GarthDB** [comment]
Still a confirmed issue.
