### ISSUE TITLE
Rename Underlay to Overlay

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#227]

**Comment by devongovett** [comment]
Why?

**Comment by lazd** [comment]
@devongovett because that's what designers seem to refer to it as. I like "underlay" because it lays beneath the dialog, but they like "overlay" because it lays over the content...

**Comment by GarthDB** [comment]
So we now have `underlay` and `overlay` components. We should work with the Design/Content Strategy to figure out naming these 2 distinct things.

**Comment by devongovett** [comment]
Hmm we also already have an Overlay component in React Spectrum that we use as the basis for all of our overlays (modals, popovers, trays).

**Comment by misterbrownlee** [comment]
Since we have both, we can't rename.  This isn't causing a problem, closing.
