### ISSUE TITLE
Rename Warning button to Negative

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#228]

**Comment by rafaeelaudibert** [comment]
I could handle this! Is every "warning" component going to be renamed, or only the button one?

**Comment by lazd** [comment]
@rafaeelaudibert This is specific to the Button. That said, we're not ready to jump on issues with the `breaking change` tag just yet.

**Comment by GarthDB** [comment]
I will update with #813

**Comment by misterbrownlee** [comment]
This is done! 🎉
