### ISSUE TITLE
Move visual regression testing to be out in the open

### ISSUE THREAD

**Issue by timkim** [adobe/spectrum-css#23]
The visual regression tool still currently lives in the corporate side of this repo. Now that we are all open source, we can move to using a CI that offers free services to open source projects. I'm thinking Travis CI or Circle CI. 

I have more experience with Circle CI but I think I may explore using Travis.

**Comment by GarthDB** [comment]
I don't see any problem with either of them. The benefit of using circle is the speed of getting other tests through travis and circle taking the time to run the regression tests.

**Comment by filmaj** [comment]
I would like to discuss this visual regression testing as I believe the tooling used in it is what pulls down phantomjs and that project is dead and headless chrome is a million times better and more relevant anyways.

**Comment by lazd** [comment]
Fixed by @jianliao's great work as part of #271
