### ISSUE TITLE
[Slider] Focus loupe in RTL is incorrect.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#2329]
## Description
When you view the slider pattern in a RTL context the focus loupe is placed before the handle rather than around it.

## Steps to reproduce

1. Go to [here](https://opensource.adobe.com/spectrum-css/slider.html#standard)
2. Change the text direction to `rtl`
3. Tab to move the focus onto one of the sliders
4. See the misplaced focus loupe.

## Expected behavior
The loupe should be around the handle as we see in `lrt` contexts.
<img width="329" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/4659fb75-b01b-48f8-b4ad-7b2c08c5d4dd">

## Screenshots
<img width="349" alt="image" src="https://github.com/adobe/spectrum-css/assets/1156657/1a5b6e4e-555d-413e-998c-0b19d22583fb">

**Comment by pfulton** [comment]
Tracking this in Jira via [CSS-644](https://jira.corp.adobe.com/browse/CSS-644).

**Comment by Chetax** [comment]
@Westbrook In lrt contexts also loupe are not around the handle
![Screenshot 2023-12-02 215830](https://github.com/adobe/spectrum-css/assets/99749401/e4d30838-0b98-495f-95e3-6c1945086523)
