### ISSUE TITLE
Rename Dropdown to Picker

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#234]
This came out of the V3 API discussions. Though I doubt this could be considered blocking to React, this was a big point of contention and the resolution was never implemented as it’s a breaking change.

**Comment by Patil2099** [comment]
@lazd Can I work on this issue?

**Comment by lazd** [comment]
hey @Patil2099, we're not ready to make this or other breaking changes yet.

Check out the issues here and pick one up if you like: https://github.com/adobe/spectrum-css/projects/10 Thanks!

**Comment by GarthDB** [comment]
[SDS-3478](https://jira.corp.adobe.com/browse/SDS-3478)
