### ISSUE TITLE
Remove remaining importants

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#238]
There are a couple of remaining `!important`s.

- [ ] ./components/calendar/index.css:71 :  border-bottom: none !important; /* override abbr styling from normalize.css */
- [ ] ./components/calendar/index.css:76 :  text-decoration: none !important; /* override abbr styling from normalize.css */
- [x] ./components/checkbox/skin.css:76 :    /* Use important to override hover states */
- [x] ./components/checkbox/skin.css:77 :    border-color: var(--spectrum-checkbox-box-border-color-disabled) !important;
- [x] ./components/checkbox/skin.css:90 :    /* Since the specificity of .focus-ring is less than :hover, we need important */
- [x] ./components/checkbox/skin.css:91 :    border-color: var(--spectrum-checkbox-box-border-color-key-focus) !important;
- [x] ./components/checkbox/skin.css:93 :    box-shadow: 0 0 0 1px var(--spectrum-checkbox-box-border-color-key-focus) !important;
- [x] ./components/checkbox/skin.css:97 :    color: var(--spectrum-checkbox-text-color-key-focus) !important;
- [x] ./components/inputgroup/skin.css:121 :      box-shadow: none !important;
- [x] ./components/inputgroup/skin.css:148 :      border-color: var(--spectrum-dropdown-border-color-error) !important;
- [x] ./components/radio/skin.css:108 :    border-color: var(--spectrum-radio-circle-border-color-disabled) !important;
- [x] ./components/radio/skin.css:112 :    color: var(--spectrum-radio-text-color-disabled) !important;
- [x] ./components/site/index.css:135 :  color: rgb(255, 2, 1) !important;
- [x] ./components/site/index.css:319 :  padding: 0 !important;
- [x] ./components/site/index.css:320 :  min-height: 0 !important;
- [x] ./components/site/index.css:324 :  margin-left: 0 !important;
- [x] ./components/site/index.css:355 :  color: rgb(255, 2, 1) !important;
- [x] ./components/site/index.css:356 :  background-color: rgba(255, 2, 1, 0.1) !important;
- [x] ./components/site/index.css:360 :  background-color: rgba(0, 0, 0, 0.1) !important;
- [x] ./components/site/index.css:367 :    background-color: rgba(245, 245, 245, 0.1) !important;
- [x] ./components/site/index.css:373 :  background-color: rgba(203, 56, 55, 0.1) !important;
- [x] ./components/site/index.css:410 :  margin-bottom: var(--spectrum-cssexample-heading-margin-bottom) !important;
- [x] ./components/site/index.css:468 :  position: relative !important;
- [x] ./components/site/index.css:469 :  transform: none !important;
- [x] ./components/slider/skin.css:266 :        background: var(--spectrum-slider-color-track-color-disabled) !important;
- [ ] ./components/stepper/index.css:56 :  margin: 0 !important;
- [ ] ./components/stepper/index.css:63 :    margin: 0 !important;
- [ ] ./components/tooltip/index.css:161 :    /* Required for animations to work, !important for diff scaling to work */
- [ ] ./components/tooltip/index.css:162 :    visibility: visible !important;
- [ ] ./components/treeview/index.css:100 :  pointer-events: all !important;

synced to jira: https://jira.corp.adobe.com/browse/CSS-210

**Comment by tacoelho** [comment]
Where @GarthDB ?

**Comment by tacoelho** [comment]
I´ll do that, thanks :)

**Comment by GarthDB** [comment]
I updated the list to reflect our current list of `!importants`

**Comment by pfulton** [comment]
Let's do a sweep during our refactoring to be sure that we're not using any `!important`s, which should make sure that this one's closed out.

That said, I'm going to close this.
