### ISSUE TITLE
Button label in `a` tag is not centered

### ISSUE THREAD

**Issue by devongovett** [adobe/spectrum-css#239]
### Expected Behavior

Button label should always be centered.

### Actual Behavior

Button label is not centered when it is an `<a>` tag instead of a `<button>`.

![image](https://user-images.githubusercontent.com/19409/62814046-14b05400-bac3-11e9-8f79-8fc145162476.png)

#### Steps to Reproduce

1. Go to http://lfbuild.corp.adobe.com:8080/job/adobe/job/react-spectrum/job/spectrum_css_upgrade_2.13.0/4/Report_20adobe_20public_2fstorybook/
2. Go to button element: a story
3. Notice the text isn't centered

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)

All

#### Spectrum-CSS version

2.13.0

#### Possible fix

Looks like removing `width: 100%` on the button label fixes it. Flex should keep it centered.

**Comment by lazd** [comment]
`width: 100%` was added as a Safari 10 fix, so we can't remove it, but `text-align: center` does the trick.
