### ISSUE TITLE
Menu disclosure chevron is not centered

### ISSUE THREAD

**Issue by devongovett** [adobe/spectrum-css#240]
### Expected Behavior

Disclosure chevron should be centered

### Actual Behavior

Disclosure chevron is not centered.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/19409/62814192-1fb7b400-bac4-11e9-81be-2aa102d5ea2e.png">

#### Steps to Reproduce

https://opensource.adobe.com/spectrum-css/2.13.0/docs/#menu-nested

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)

All

#### Spectrum-CSS version

2.13.0

**Comment by lazd** [comment]
Seems like this was introduced by #176; the checkmark was given a vertical centering/wrapping treatment, but not the chevron.
