### ISSUE TITLE
Will Spectrum CSS adopt Spectrum 2 styles

### ISSUE THREAD

**Issue by joebudi** [adobe/spectrum-css#2400]
Will Spectrum CSS adopt Spectrum 2 styles? If so, is there a rough timeline?

**Comment by pfulton** [comment]
Hi @joebudi!

Yes! We're hard at work on it right now and we'll be working on it throughout 2024. Unfortunately, I can't share any timelines right now, but you'll probably start to see "foundational" things landing first (colors, etc.) and then individual component updates after that.

**Comment by joebudi** [comment]
Awesome - thanks for the update. Best of luck!
