### ISSUE TITLE
Button receives dotted outline on focus in Firefox

### ISSUE THREAD

**Issue by devongovett** [adobe/spectrum-css#241]
### Expected Behavior

Button should not get dotted outline in Firefox.

### Actual Behavior

Button gets dotted outline in Firefox. Applies to all buttons, not just CTA.

<img width="93" alt="image" src="https://user-images.githubusercontent.com/19409/62814311-e59ae200-bac4-11e9-97dc-e47b442abc51.png">

#### Steps to Reproduce

1. Go to https://opensource.adobe.com/spectrum-css/2.13.0/docs/#button---cta
2. Tab to a button.
3. See dotted outline.

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)

Firefox

#### Spectrum-CSS version

2.13.0

**Comment by lazd** [comment]
Duplicates #161
