### ISSUE TITLE
[Picker Button]: No styling for `invalid` state

### ISSUE THREAD

**Issue by najikahalsema** [adobe/spectrum-css#2422]
## Description

The CSS for the picker button doesn't seem to have any styling specification for an `invalid` state. While [Spectrum doesn't document this usage specifically for a picker button](https://spectrum.adobe.com/page/picker/#Error), I would wager that an `invalid` picker styling also begets an `invalid` style for the picker button, too, for components like [Combobox](https://opensource.adobe.com/spectrum-css/combobox.html#invalid) or a [Date Picker](https://spectrum-contributions.corp.adobe.com/page/date-picker-beta/#Error). 

## Steps to reproduce

1. Go [here](https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/picker-button--invalid)
2. Observe that though `<sp-picker-button>` has the `invalid` attribute, the styling is the same as it would be by default.

## Expected behavior

The picker button should have a red border when it's `invalid`:

![image](https://github.com/adobe/spectrum-css/assets/44980010/b7c80b2a-f6ee-4654-9ffb-d219c4c423ae)
image from [spectrum contributions](https://spectrum-contributions.corp.adobe.com/page/date-picker-beta/#Error)

![image](https://github.com/adobe/spectrum-css/assets/44980010/051dd1fa-72ce-4637-94ac-676d52384c60)
Image from [Spectrum CSS Combobox documentation](https://opensource.adobe.com/spectrum-css/combobox.html#invalid). Here, the picker button has a class of `Combobox-button`.

## Screenshots

![image](https://github.com/adobe/spectrum-css/assets/44980010/cd672342-f751-486c-8c3c-610dc398a561)
from @paulodetarsofm 

## Environment

-   **Version of the impacted component(s):** 
-   **Browser(s) and OS(s):**

**Comment by pfulton** [comment]
@najikahalsema just circling back to this and the comment from @jenndiaz above. Is there something else we could do for you here?

**Comment by najikahalsema** [comment]
This works, but there's another inconsistency. I came across re: the styling of the textfield and the picker button when focusing the combobox. I just haven't been able to articulate it yet. I can make another issue when the time comes, though! Thanks for pinging me.
