### ISSUE TITLE
Checkbox css relies on global typography styles.

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-css#243]
### Expected Behavior
The checkbox css should be self-contained.

### Actual Behavior
The text label is picking up line-height and font-style from the global typography styles.

#### Steps to Reproduce

If you inspect the checkbox css at https://opensource.adobe.com/spectrum-css/2.13.0/docs/#checkbox you'll see line-height & font-style styles getting picked up from the `.spectrum, .spectrum-Body` define.

#### Spectrum-CSS version

2.13.0

#### Screenshots (if applicable)

<img width="747" alt="web-inspector" src="https://user-images.githubusercontent.com/48841507/62890437-1f5c2a80-bd09-11e9-92dd-8979e1524ed2.png">

synced to jira: https://jira.corp.adobe.com/browse/SDS-7324

**Comment by Westbrook** [comment]
This appears to persist in v2.14.0 as documented at https://opensource.adobe.com/spectrum-css/2.14.0/docs/checkbox.html:
![image](https://user-images.githubusercontent.com/1156657/67118716-7a9c1480-f1b3-11e9-8733-27a0683add37.png)
