### ISSUE TITLE
Rating stars overlap in IE 11

### ISSUE THREAD

**Issue by LFDanLu** [adobe/spectrum-css#245]
### Expected Behavior
Rating stars should never overlap

### Actual Behavior
Rating stars if there are 10+ stars

![rating](https://user-images.githubusercontent.com/9661127/62900938-55e97380-bd10-11e9-95e1-ffa38b7c3edc.PNG)

#### Steps to Reproduce
1. Navigate to http://lfbuild.corp.adobe.com:8080/job/adobe/job/react-spectrum/job/spectrum_css_upgrade_2.13.0/4/Report_20adobe_20public_2fstorybook/ in IE 11
2. Go to the Rating -> Max story

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
IE 11

#### Spectrum-CSS version
2.13.0

**Comment by lazd** [comment]
Oh man, I don't know if we're supposed to have more than 5 stars, but if we did, I'd want it to look this cool.

Let's loop in Design and see what they say.

**Comment by lazd** [comment]
Design says 5 stars only :'( So we'll close this for now.
