### ISSUE TITLE
Breadcrumbs should ellipse on overflow

### ISSUE THREAD

**Issue by ericdolson** [adobe/spectrum-css#247]
### Expected Behavior
Breadcrumbs should shorten/truncate/ellipse if overflows container

### Actual Behavior
The breadcrumb text gets cut off at the end

#### Screenshots (if applicable)
<img width="271" alt="Screen Shot 2018-11-05 at 10 18 22 AM" src="https://user-images.githubusercontent.com/2644529/63123302-e967b200-bf65-11e9-912d-9e7e32625e76.png">
<img width="292" alt="Screen Shot 2018-11-05 at 10 18 27 AM" src="https://user-images.githubusercontent.com/2644529/63123303-e967b200-bf65-11e9-9608-aad4bfd53a70.png">

**Comment by lazd** [comment]
@ericdolson can you provide a codepen that reproduces the issue, also note which version of Spectrum CSS, and which browser you're on? Thanks.

**Comment by GarthDB** [comment]
We need to check with Design to see the intended behavior. We might need to remove middle elements or have a dropdown list for items when there isn't enough space.

**Comment by GarthDB** [comment]
Design has provided a solution for overflow https://spectrum.adobe.com/page/breadcrumbs/#Overflow
