### ISSUE TITLE
[ACCESSIBILITY] Dropdown placeholder text ships with low contrast color.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#252]
### Expected Behavior
Placeholder text in a dropdown features text with accessible contrast.

### Actual Behavior
The color rates at 3.13:1 as opposed to the target 4.5:1

### Reproduce Scenario (including but not limited to)
I'd like to use a dropdown in my application

#### Steps to Reproduce
Build a dropdown from the provided CSS

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
all

#### Spectrum-CSS version
2.13.0

#### Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/1156657/63530069-c09a6c00-c4d3-11e9-833c-ed608357fcdd.png)

**Comment by lazd** [comment]
@NateBaldwinDesign can you check this out?

**Comment by NateBaldwinDesign** [comment]
@Westbrook @lazd The text in question is **placeholder text**, which is to be shown if there is no default selection on the dropdown. Placeholder text does not need to meet the minimum contrast requirements for WCAG https://www.w3.org/WAI/tutorials/forms/instructions/#styling.

**Comment by lazd** [comment]
Thanks @NateBaldwinDesign, we can go ahead and close this. Thanks for the report, @Westbrook !
