### ISSUE TITLE
tabs' label's font-size has the wrong mod token

### ISSUE THREAD

**Issue by lehelen19** [adobe/spectrum-css#2585]
## Description

The tabs' label's font-size is set by `var(--mod-tabs-font-weight)` instead of a font size mod token.

## Steps to reproduce

1. Look at https://github.com/adobe/spectrum-css/blob/main/components/tabs/index.css#L436

## Expected behavior

We should be able to set a mod token for font-size that doesn't change font-weight.

## Environment

-   **Version of the impacted component(s):** 
-   **Browser(s) and OS(s):**

**Comment by castastrophe** [comment]
Great catch @lehelen19!
