### ISSUE TITLE
Replace auto-updating-hash on docs site with anchor links

### ISSUE THREAD

**Issue by filmaj** [adobe/spectrum-css#26]
This suggestion came out of the performance investigation on the docs site in #6.

It's still unclear what perf impact the updating hash functionality has, but regardless of that, @ericdrobinson brought up a good point in #6 that updating the hash as you scroll through the page 100% messes up browsing history. As soon as you scroll on the docs site, the back button stops working.

@ericdrobinson's suggestion was to replace that functionality with anchor links that are copyable - like how headings in READMEs on GitHub are linked, can be copied, and render a little anchor icon to give users a hint that you may want to link/share to this. I like that suggestion.

**Comment by filmaj** [comment]
Gonna familiarize myself with how the docs are generated and give a shot at a pull request for this. I'm also thinking of splitting up the docs page so that we have one-component-per-page - I think that may address some of the performance problems identified in #6.

**Comment by GarthDB** [comment]
It will. Involved in all of this is figuring out how to keep data persistent between the pages for the theme and scaling selection. Ben was working on it as a single page and loading in the components and using the history api

**Comment by GarthDB** [comment]
I don’t know where he left his work

**Comment by filmaj** [comment]
I'm gonna guess @benjamind's fork 😄 https://github.com/benjamind/spectrum-css/tree/docs-site-spa

**Comment by filmaj** [comment]
Benjamin's branch seems to work pretty well! I made some tweaks on [my own branch](https://github.com/filmaj/spectrum-css/tree/docs-site-spa) (to hook in some gulp bits like watching and added a couple of null checks to fix some JS errors), and compared scrolling through the various alert component variants on the old docs page (all components on one page) vs. doing the same on this branch based on Ben's work. The perf graph is way less busy on the one-component-per-page setup.

Old docs site perf graph:

<img width="1680" alt="screen shot 2018-11-23 at 4 22 38 pm" src="https://user-images.githubusercontent.com/52645/48961777-07573780-ef3d-11e8-8db7-9078e29c5b19.png">

Out of 7.25 seconds scrolling through alert variants, ~3 seconds were spent rendering.

New docs site perf graph:

<img width="1680" alt="screen shot 2018-11-23 at 4 22 54 pm" src="https://user-images.githubusercontent.com/52645/48961821-6157fd00-ef3d-11e8-9775-25b853c44b10.png">

Out of 8 seconds scrolling through alert variants, 50ms was spent rendering.

You can also see that the FPS while scrolling is _way_ higher on the new docs page: the number of green bars in the "Frames" row is much higher during the scroll events compared to the old docs site.

**Comment by filmaj** [comment]
Cool, thanks for this!
