### ISSUE TITLE
Support dynamic font subsetting for CCJK languages - Separate kits for each language

### ISSUE THREAD

**Issue by Hemanthharnad7** [adobe/spectrum-css#263]
I think we need to create separate font kits for each language and choose font kit based on language selection.

There are only 2 kits used here,
https://github.com/adobe/spectrum-css/blob/06688fa13a974920e5f44c8f9b18db098c6ecb2f/site/resources/js/typekit.js#L12

Something similar to this - https://wiki.corp.adobe.com/display/harnad/Guideline+for+Fonts

**Comment by GarthDB** [comment]
@Hemanthharnad7 Spectrum CSS doesn't handle the typekit for you. You should manage your own typekits outside of our project.
