### ISSUE TITLE
IE11: Content clipped on CSS-only show-on-hover Tooltip

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#264]
### Expected Behavior

Fits the text

### Actual Behavior

Is very tiny

![image](https://user-images.githubusercontent.com/201344/63741349-92a58680-c849-11e9-8528-d5079044c9df.png)

#### Steps to Reproduce

1. Mouse over tooltip example here https://opensource.adobe.com/spectrum-css/2.14.0-alpha.14/docs/tooltip.html#showonhover
2. Observe
3. Weep, quietly

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)

IE 11

#### Spectrum-CSS version

2.13.0 & 2.14.0-alpha14

**Comment by xitter** [comment]
I gave this a try and `display:inline-flex` seems to be broken on IE. Possible solutions:
1.  `display:inline-block`
2. keep a `min-width`

**Comment by GarthDB** [comment]
We are dropping support for IE11
