### ISSUE TITLE
Bug: icon on multiline textarea is distorted

### ISSUE THREAD

**Issue by Rajdeepc** [adobe/spectrum-css#2668]
## Description

`valid` and `invalid` icons on multiline textarea is distorted

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/textarea.html ---> Valid
2. Click on the textarea and add few words and press enter. 
3. Observe the scrollbar and the icon is overlapping the scrollbar

## Expected behavior

`valid` and `invalid` icons on multiline textarea should not overlap the scrollbar

## Screenshots
![Screenshot 2024-04-17 at 5 43 00 PM](https://github.com/adobe/spectrum-css/assets/8790510/b0fe2ab0-4a5c-4e56-8f27-94c1655987e5)

## Environment

-   **Version of the impacted component(s):** 
-   **Browser(s) and OS(s):** 
All browsers

**Comment by castastrophe** [comment]
On current implementation: https://opensource.adobe.com/spectrum-css/?path=/story/components-text-area--default&args=isValid:!true

- Safari: no scrollbar
- Chrome: no overlap with scrollbar
- Firefox: no overlap with scrollbar

Going to close this as it seems resolved but let me know if we need to reopen it!
