### ISSUE TITLE
[Popover] Unreasonable complex selectors with duplicate classes generated

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#2705]
https://github.com/adobe/spectrum-css/blob/3c7de5e07d34ca6ca1ae873ff32f4e7a02d1f0ad/components/popover/index.css#L319-L346

This will generate selectors like `.spectrum-Popover--withTip.spectrum-Popover--left.spectrum-Popover--left .spectrum-Popover-tip` wherein the `spectrum-Popover--left` is duplicated.

Can this be smoothed out? It creates additional difficult when processing the output downstream.

**Comment by pfulton** [comment]
Tracking this in Jira via [CSS-750](https://jira.corp.adobe.com/browse/CSS-750)
