### ISSUE TITLE
[Alert banner] Fixed width causes truncation on small devices

### ISSUE THREAD

**Issue by loredanaspataru** [adobe/spectrum-css#2715]
## Description

The alert banner has a fixed width of 832px (M)/ 680px (L). This is set by `--spectrum-alert-banner-width` variable in [spectrum-css tokens](https://github.com/adobe/spectrum-css/blob/main/tokens/dist/index.css#L1859). This introduces an issue for small screens because the alert banner gets truncated on mobile devices.

Since the fixed sizes were introduced to prevent having alert banners that are too wide and hard to read, we should use the fixed sizes as `max-width` instead of width. This way the alert banner would occupy all the available space until it reaches its maximum allowed width of `832px/680px`, depending on the theme size.

## Steps to reproduce

1. Go to <https://opensource.adobe.com/spectrum-css/alertbanner.html/>
2. Open dev tools and toggle device toolbar
3. Choose a mobile device from the list of available options
4. Observe that alert banner content gets truncated

## Expected behavior

The alert banner should be fully visible even on small devices.

## Screenshots

![Screenshot 2024-04-30 at 13 56 54](https://github.com/adobe/spectrum-css/assets/37333191/c110cea6-0451-4bb7-b089-34c66be39aaf)

**Comment by pfulton** [comment]
Tracking this in Jira via [CSS-748](https://jira.corp.adobe.com/browse/CSS-748)
