### ISSUE TITLE
Breadcrumb CSS has some css with limited browser support

### ISSUE THREAD

**Issue by ktabors** [adobe/spectrum-css#274]
## Description

Farian Wenzel ran a postcss on react spectrum (shouldn't have be done) which turned up that breadcrumb.css has `justify-content: start;`

`justify-content: start;` is used in breadcrumb css which has limited browser support. https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

```Compiled with warnings.
./node_modules/@react/react-spectrum/spectrum-css/breadcrumb/index.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/@react/react-spectrum/spectrum-css/breadcrumb/index.css)
Warning
(30:7) start value has mixed support, consider using flex-start instead
./node_modules/@react/react-spectrum/spectrum-css/breadcrumb/index.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/@react/react-spectrum/spectrum-css/breadcrumb/index.css)
Warning
(5:7) start value has mixed support, consider using flex-start instead
./node_modules/@react/react-spectrum/spectrum-css/breadcrumb/index.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/@react/react-spectrum/spectrum-css/breadcrumb/index.css)
Warning
(60:7) start value has mixed support, consider using flex-start instead
```

## Steps to reproduce

1. Go to http://opensource.corp.adobe.com/spectrum-css/
2. Click on ...
3. Observe ...

## Expected behavior

Use `flex-start` instead

## Environment
 - Spectrum CSS version: 2.14.0-alpha.16
 - OS: See below
 - Browser: All browsers listed here https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

**Comment by vincentpurcell** [comment]
We're also experiencing this issue using react-spectrum in our cc-spark-edu application.

**Comment by ktabors** [comment]
Any status on this?

**Comment by snowystinger** [comment]
@vincentpurcell and Farian, I think you can solve this by changing your postcss config to match browser support?

**Comment by snowystinger** [comment]
Team has verified that excluding us from their postcss loader and putting it into a simple css-loader solved the issue for them, @lazd please feel free to close

**Comment by elodierafali** [comment]
Hi @snowystinger, @lazd is there a workaround for this issue please when using `create-react-app`? Above fix will not work in that case, yet it's a widely used config used by many. Is there a reason not to change `start`to `flex-start`? If no workaround I'd like to open an issue for it. Thanks.
