### ISSUE TITLE
Dropdown selected item text should be gray

### ISSUE THREAD

**Issue by labrowne** [adobe/spectrum-css#288]
## Description
the selected text in a dropdown used to be blue, but recently changed to gray 800 (matches the other text in the list)

**Comment by TomerPacific** [comment]
@labrowne , is this issue still relevant?

**Comment by lazd** [comment]
@labrowne looks like it's fixed, yes? https://opensource.adobe.com/spectrum-css/2.14.0/docs/menu.html#standard

**Comment by labrowne** [comment]
i dont see blue text, which is good, but shouldnt there be a blue checkmark next to the selected item still?

**Comment by lazd** [comment]
Yup, that's what we've got: 
![image](https://user-images.githubusercontent.com/201344/68338484-699a4100-0097-11ea-815a-9fa361828c1f.png)

See http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.14.0/docs/dropdown.html#standard

I'll go ahead and close this issue.
