### ISSUE TITLE
Add utility class to any component for receiving the Spectrum :focus look

### ISSUE THREAD

**Issue by bernhard-adobe** [adobe/spectrum-css#292]
## Description
As a user I want to be able to set a focus state on any element so it follows the look and feel of Spectrum. Currently only some components like input fields, tabs and links seem to inherit the desired look. Other elements will receive the default browser behavior.

## Why do you need this feature or component?
For accessibility reasons some items that are not pure form elements will be focused / tabbed-on. This is clashing with the Spectrum style. 

## Additional context
[
postcss-focus-ring](https://www.npmjs.com/package/postcss-focus-ring) might be used to generate an utility class like `.u-isFocused`

Current behavior:
![Screen Shot 2019-09-24 at 11 38 54](https://user-images.githubusercontent.com/52184321/65555106-62044b80-dee0-11e9-9b72-b50cd98807fa.png)

Future behavior with added class:
![Screen Shot 2019-09-24 at 15 30 05](https://user-images.githubusercontent.com/52184321/65555104-5fa1f180-dee0-11e9-805b-2c9142f757c8.png)

**Comment by lazd** [comment]
Should this be a class that adds focus styles on interactivity, i.e. it has `:focus` pseudo-selectors and `.focus-ring` classes for the polyfill, or should it be a class that adds focus styles when the class is added (i.e. it's added by JS inside of a focus listener)?

**Comment by bernhard-adobe** [comment]
maybe both cases could be covered so this could be applied to any kind of components.

**Comment by GarthDB** [comment]
We will add these as design is provided by the design team.
