### ISSUE TITLE
Calendar weekdays need to be summarized to single letter

### ISSUE THREAD

**Issue by labrowne** [adobe/spectrum-css#294]
## Description
Calendar used to abbreviate weekdays to two letters (SU, MO, TU, WE etc), but in order to be more localization friendly (and per request from React), we've decided to abbreviate to a single letter (S, M, T, W etc). The calendar in contributions has been updated to reflect this change. 

## Link to documentation
https://spectrum-contributions.corp.adobe.com/submissions/calendar

**Comment by birtony** [comment]
Hey! This seems to be an interesting issue, but the link to documentation does not work, unfortunately.

**Comment by lazd** [comment]
@birtony correct, that's an internal Adobe server. Luckily, this is a simple documentation-only change that doesn't require much detail.

@labrowne, in the future can you upload the XD file to xd.adobe.com or upload a PDF on the issue so non-Adobe people can see the designs?

**Comment by labrowne** [comment]
yep.
