### ISSUE TITLE
Chrome regression caused text inputs to be unusable

### ISSUE THREAD

**Issue by snowystinger** [adobe/spectrum-css#295]
## Description
See here https://github.com/adobe/react-spectrum/issues/596

## Additional context
We have solved this temporarily with https://github.com/adobe/react-spectrum/pull/601 but it might be a good idea to just do it this way in spectrum-css as well.

**Comment by lazd** [comment]
Thanks for the heads up. I don't think we can make that `text-indent` change as it resulted in text that overlaps the search icon.
![image](https://user-images.githubusercontent.com/201344/65787778-8f364100-e10e-11e9-85f8-c921d32a354e.png)

**Comment by snowystinger** [comment]
sad days

**Comment by snowystinger** [comment]
chrome 78 has released and it seems to be fixed, hooray!
