### ISSUE TITLE
Prototype updated Rating component (stars)

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#30]
Design is provided by Mathieu Badimon from the Adobe Design Team.

**Comment by lazd** [comment]
Prototype happening here: https://codepen.io/lazd/pen/WYggmO

The opensource.adobe.com domain is misconfigured so https doesn't work, so you have to visit https://opensource.adobe.com/spectrum-css/2.6.0/docs/ first, click Advanced, Proceed.

**Comment by lazd** [comment]
Prototype approved by @majornista as far as accessibility!

@NateBaldwinDesign, what do you think about the tokens in the prototype? Are they organize/named properly? If so, I can send a PR to DNA.

**Comment by NateBaldwinDesign** [comment]
@lazd the token names look good except the following:
`--spectrum-rating-icon-spacing` should be `--spectrum-rating-icon-gap`
`--spectrum-rating-indicator-offset` should probably be `--spectrum-rating-indicator-gap` (although this one would be fine either way)

Side note, `--spectrum-rating-indicator-height` should be global, not scale dependent (it's treated like a border).

**Comment by GarthDB** [comment]
@NateBaldwinDesign, fixing the tokens, what would design want to see/do before we start working on a released version of rating?
