### ISSUE TITLE
Missing punctuation in documentation

### ISSUE THREAD

**Issue by leeclench** [adobe/spectrum-css#304]
## Description
Missing punctuation in CONTRIBUTING, CODE_OF_CONDUCT and READMEs.

## Link to documentation
CONTRIBUTING, CODE_OF_CONDUCT and READMEs.

## Additional context
Just some punctuation needs adding into the documentation.

**Comment by moisesjsanchez** [comment]
Hello, I am a first-time contributor. Would it be okay for me to work on this?

**Comment by GarthDB** [comment]
@moisesjsanchez absolutely. Make a pr

**Comment by Manvi07** [comment]
Hi @GarthDB is this issue resolved?

**Comment by Sweta271097** [comment]
@leeclench I believe CODE_OF_CONDUCT.MD was updated with the punctuation so, I corrected the rest of the files.

**Comment by Sumindar** [comment]
hi i am a first time contributor please guide how could i work on it?

**Comment by lazd** [comment]
@Sumindar we already have several pull requests open for this, there's no need to work on it. Please take a look at other open issues, such as these https://github.com/adobe/spectrum-css/projects/10

**Comment by lazd** [comment]
I'm closing this issue as we have too many open pull requests addressing it, and had 3 more related PRs coming in today.
