### ISSUE TITLE
Actionbar with content relative popover width.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#319]
## Description
When using the `.spectrum-ActionBar` pattern, the `.spectrum-ActionBar-popover` therein is given `width: 100%`, which can leave small amounts of content awkwardly placed:
![image](https://user-images.githubusercontent.com/1156657/66414554-a35c2700-e9c7-11e9-852d-dfeff566e405.png)
I'd like to suggest to addition of a `.spectrum-ActionBar--content-relative` (name FPO) style pattern that would allow the width to be dictated by the content therein:
![image](https://user-images.githubusercontent.com/1156657/66414661-dbfc0080-e9c7-11e9-9a27-7f2b11f67bee.png)

## Why do you need this feature or component?
Allows for a more flexible delivery of the ActionBar pattern without overlaying as much whitespace content over the actual interaction canvas you are acting against with this UI.

## Additional context
This should be achievable with the addition of:
```
.spectrum-ActionBar--flexible .spectrum-ActionBar-popover {
    width: auto;
}
```

**Comment by lazd** [comment]
Hmm, perhaps setting width should be entirely on the JS implementation... @jianliao?

**Comment by jianliao** [comment]
I am fine with it.

**Comment by Westbrook** [comment]
Also a viable option.

I'd also be interesting https://github.com/adobe/spectrum-css/blob/master/components/actionbar/index.css#L76 being updated to `width: car(--spectrum-actionbar-width);` or similar...

**Comment by sambhavkaul** [comment]
I would like to take this

**Comment by lazd** [comment]
After talking with Downtown @labrowne, we decided it would be best to add a `flexible` variant instead of controlling it with CSS variables.

**Comment by labrowne** [comment]
lollll 😎
