### ISSUE TITLE
Prototype color slider/area/circle components

### ISSUE THREAD

**Issue by buddhari** [adobe/spectrum-css#32]
Link to specs: https://xd.adobe.com/view/d91cf3b2-e1fd-4a78-61dc-72ad67be77cb-af2d/
XD file: https://www.dropbox.com/s/u5aipqpi69xoqrk/Color-Picker_2018-11-29_PJ.xd?dl=0

**Comment by lazd** [comment]
Prototype happening here: https://codepen.io/lazd/pen/jQdGVq

The opensource.adobe.com domain is misconfigured so https doesn't work, so you have to visit https://opensource.adobe.com/spectrum-css/2.6.0/docs/ first, click Advanced, Proceed.

**Comment by GarthDB** [comment]
Prototype is close to complete, but some design ideation still happening with swatches.

**Comment by lazd** [comment]
Calling this one done. The proposed designs for Swatches have been implemented, and though we're still finalizing and tweaking them, the work is done.
