### ISSUE TITLE
[Avatar] Opacity is processed at NaN

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#340]
## Description
The opacity code available at https://github.com/adobe/spectrum-css/blob/master/components/avatar/skin.css#L14-L18 renders to `opacity: NaN;` in the published package.

## Steps to reproduce

1. `yarn add @spectrum-css/avatar`
2. `cd node_modules/@spectrum-css/avatar/dist`
3. `vim index-vars.css`

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by lazd** [comment]
Oh lawd. Nice catch, looks like a PostCSS function issue. Will investigate.
