### ISSUE TITLE
[Accessibility] StepList keyboard focus ring has been updated in Spectrum

### ISSUE THREAD

**Issue by majornista** [adobe/spectrum-css#342]
## Description
Spectrum has updated the focus ring styling of StepList to better comply with WCAG 2.1

## Steps to reproduce

1. Open https://opensource.adobe.com/spectrum-css/2.14.0/docs/steplist.html#withlabelinteractive
2. Press tab key twice to set focus to the current step in the "StepList: With label (interactive)" example.
3. The circle marker element will change color to indicate keyboard focus

## Expected behavior
The circle marker should display a round 2px focus outline per Spectrum design spec: https://spectrum-contributions.corp.adobe.com/submissions/steplist

## Screenshots
<img width="418" alt="Screen shot showing keyboard focus styles for StepList in Adobe XD" src="https://user-images.githubusercontent.com/154077/67130099-5bf74700-f1ce-11e9-9ebb-e9c0ac46dbc6.png" />

## Environment
 - **Spectrum CSS version:**  2.14.0 
 - **Browser(s) and OS(s):** Chrome 77.0.3865.120 on macOS, but 

## Additional context

This is important for Accessibility.

**Comment by misterbrownlee** [comment]
We don't have keyboard focus in steplist; when we take steplist out of contribution we will include this work.
