### ISSUE TITLE
Mention SUIT in contributing docs

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#354]
## Description

Currently, we mention SUIT on a one-off wiki page: https://github.com/adobe/spectrum-css/wiki/Class-Naming-Conventions

We should be talking about this upfront in our CONTRIBUTING document.

## Link to documentation

https://github.com/adobe/spectrum-css/wiki/Class-Naming-Conventions
https://github.com/adobe/spectrum-css/blob/master/.github/CONTRIBUTING.md

## Additional context

https://twitter.com/giuseppegurgone/status/1186703007355932672

synced to jira: https://jira.corp.adobe.com/browse/CSS-211

**Comment by frunkad** [comment]
Hi @lazd 

Could you guide me on the tone of how this should be added in the CONTRIBUTING documentation?

- Will a sibling of Security (Under Questions heading) look good?
- "We use SUIT naming conventions as further described in [Class Naming Conventions](https://github.com/adobe/spectrum-css/wiki/Class-Naming-Conventions)" How does it sound?

Thanks

**Comment by lazd** [comment]
@frunkad hmm, seems like we might need a more general section `Conventions` that contains a couple of headings detailing the architecture. I'd say leave this one be for a bit, we'll be revising our technical documentation with the content strategy team in the future and can handle this then.

**Comment by misterbrownlee** [comment]
We reviewed this issue 9/9, keeping it in the backlog and will assess as sprint bandwidth opens up
