### ISSUE TITLE
Revert Checkbox/Radio/Switch default (non-emphasized) to be blue again

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#355]
## Description

The change to a grey (non-emphasized) Checkbox/Radio/Switch is shocking, so we need to roll it back.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/checkbox/#Standard
3. Observe shocking change: Checkbox/Radio/Switch are grey

## Expected behavior

Checkbox/Radio/Switch are blue.

## Screenshots

![image](https://user-images.githubusercontent.com/201344/67320357-f69fa080-f4c2-11e9-9bdb-cfa0b2db7eb5.png)

## Environment
 - **Spectrum CSS version:** 2.14
 - **Browser(s) and OS(s):** all

## Additional context

Feedback from React Spectrum team.

**Comment by GarthDB** [comment]
![xhy81P](https://user-images.githubusercontent.com/125516/67320551-9cefa400-f4cb-11e9-9ee7-fbeee026fbbf.gif)
