### ISSUE TITLE
Combobox dropdown showing horizontal scrollbar for longer texts on IE11

### ISSUE THREAD

**Issue by horiavarlan** [adobe/spectrum-css#358]
We're currently using the Spectrum Combobox to display a number of plans. In IE11, for those which are longer than the actual width of the component, the dropdown part gets a horizontal scrollbar which, when trying to be clicked simply closes the dropdown. In all the other browsers it gets displayed as expected, with the longer content simply wrapping to the next line.

## Steps to reproduce
https://jira.corp.adobe.com/browse/E2E-8798

## Expected behavior
We would expect to have the content wrap just like it does in all the other browsers.

## Screenshots
![image](https://user-images.githubusercontent.com/2861138/67416275-6a9d7f80-f57b-11e9-9967-4a75b9d92099.png)

## Environment
 - **Spectrum CSS version:** 2.6.0
 - **Browser(s) and OS(s):** IE11 on Win 10 in BrowserStack

**Comment by GarthDB** [comment]
We are dropping support for IE11
