### ISSUE TITLE
Doc search text overlapping

### ISSUE THREAD

**Issue by agnelnieves** [adobe/spectrum-css#359]
## Description
The document site search bar text is overlapping with the search icon. Some styles in the date-picker and text field components are affecting the search bar.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/datepicker/
2. Observe the search bar styles
3. Click on Cycle Button
4. Observe how the style changes

## Screenshots
![Screen Shot 2019-10-23 at 1 18 39 PM](https://user-images.githubusercontent.com/5799157/67417996-fb825400-f597-11e9-95d8-1785395b9c89.png)
![Screen Shot 2019-10-23 at 1 18 47 PM](https://user-images.githubusercontent.com/5799157/67417997-fc1aea80-f597-11e9-8a71-019ce55a9278.png)

## Environment
 - Chrome 78.0.3904.70  on MacOS Mojave [10.14.5 (18F203)]

## Additional context
--

**Comment by lazd** [comment]
This was fixed by https://github.com/adobe/spectrum-css/pull/382
