### ISSUE TITLE
Larger Avatar Size

### ISSUE THREAD

**Issue by bradee** [adobe/spectrum-css#368]
## Description
It doesn't seem like the large size avatar is in alignment with spectrum documentation.

## Why do you need this feature or component?
Our app frame header looks silly and the avatar size is too tiny to even be recognizable.

## Additional context
https://spectrum-contributions.corp.adobe.com/submissions/avatars

**Comment by lazd** [comment]
Yup, we only have the small size in stock.

@NateBaldwinDesign, can we get some tokens for the medium/large sizes?

**Comment by GarthDB** [comment]
Tokens are coming for T-shirt sizing in Avatar.

**Comment by GarthDB** [comment]
Sizing has been added to [avatar](https://opensource.adobe.com/spectrum-css/avatar.html).
