### ISSUE TITLE
docs(readme): url workflow icons results in 404 not found

### ISSUE THREAD

**Issue by donroyco** [adobe/spectrum-css#370]
## Description

In the README.md file, the URL to the Workflow icons results in a 404 error: page not found.

<img width="498" alt="Screenshot 2019-10-30 at 21 19 23" src="https://user-images.githubusercontent.com/1763537/67895702-46353a80-fb5b-11e9-9303-9f995d884f19.png">
URL consulted: https://opensource.adobe.com/spectrum-css/icons/

Correct URL: https://spectrum.adobe.com/page/icons/

## Link to documentation

README.md file: https://github.com/adobe/spectrum-css/blob/master/README.md

## Additional context

URL links to the incorrect page.

**Comment by lazd** [comment]
Good catch, this page was removed and replaced by https://spectrum.adobe.com/page/icons/
