### ISSUE TITLE
docs(readme-legacy): text references example, but none exists

### ISSUE THREAD

**Issue by donroyco** [adobe/spectrum-css#372]
## Description

[At the very end](https://github.com/adobe/spectrum-css/blame/master/README-legacy.md#L142) of the legacy Readme file, there's stated:
> Note that the Spectrum CSS UI icons must change as well, see below for a full example.

But 'below' is nothing, neither code, an image or explanation.

## Link to documentation

README-legacy.md: https://github.com/adobe/spectrum-css/blob/master/README-legacy.md

## Additional context

I am not sure what the example should look like.

**Comment by lazd** [comment]
Ah, the text was re-ordered and split out. The referenced example was this: https://github.com/adobe/spectrum-css#using-components

**Comment by donroyco** [comment]
Fixed in #385
