### ISSUE TITLE
Document how to update DNA

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#388]
## Description

Jira ticket: https://jira.corp.adobe.com/browse/SDS-4424

As reported by @bernhard-adobe, right now, there is minimal documentation that show show to update DNA, but it doesn't work due to `optionalDependencies` being ignored.

## Link to documentation

https://github.com/adobe/spectrum-css/blob/master/components/vars/README.md#updating-from-dna

## Additional context

One way around this:

```
npx lerna clean
rm -rf node_modules/
rm .yarnrc
yarn install
cd components/vars
npm run update
cd ../../
git checkout .yarnrc
gulp dev
```

Another way:

```
npx lerna clean
rm -rf node_modules/
yarn install
yarn add -W -O @spectrum/spectrum-dna
cd components/vars
npm run update
cd ../../
gulp dev
```

**Comment by bernhard-adobe** [comment]
my steps to success were:

 **update correct @a4u artifactory settings:**
(removed `-local`) from https://wiki.corp.adobe.com/display/AdobeDesign/Setting+up+the+development+environment#Settingupthedevelopmentenvironment-AddSpectrumArtifactorySources(forallrepositories)
(I updated the Wiki)

**Maybe optional:**
```
npx lerna clean
rm -rf node_modules/
rm .yarnrc
```

**definitely needed for DNA updates:**
```
yarn install 
yarn add -W -O @spectrum/spectrum-dna
cd components/vars
npm run update
```

running development:
```
cd ../../
gulp dev
```
