### ISSUE TITLE
Slider track missing on documentation site

### ISSUE THREAD

**Issue by NateBaldwinDesign** [adobe/spectrum-css#397]
## Description

Slider track is not visible on the documentation site. Has not been tested in implementation; only reporting what is seen on the website

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/slider/
2. Observe No track behind the sliders

## Expected behavior

Expect to see the slider tracks.

## Screenshots

![image](https://user-images.githubusercontent.com/13972198/68515393-03035780-023e-11ea-9e35-074efe2d0182.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** 78.0.3904.87 (Official Build) (64-bit) Mac

## Additional context

synced to jira: https://jira.corp.adobe.com/browse/SDS-7332

**Comment by lazd** [comment]
Weird, seems to appear fine on the dev docs: http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.15.1/docs/slider.html#standard

Paging Dr @GarthDB.

**Comment by GarthDB** [comment]
Slider tracks are back.
