### ISSUE TITLE
Add note about the move to individual versioning, where to find bundles to main README

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#398]
## Description

We should describe why we moved to individual versioning, mentioning bundles and linking to the legacy README for more details.

## Link to documentation

https://github.com/adobe/spectrum-css

**Comment by ericdrobinson** [comment]
This would be a very welcome addition and save people looking for a monolithic bundle a lot of time.

**Comment by GarthDB** [comment]
Done with #579
