### ISSUE TITLE
Date picker field style bugs

### ISSUE THREAD

**Issue by labrowne** [adobe/spectrum-css#399]
## Description
Doing an audit of the react components, and am finding a few mistakes with the date picker that i believe are coming from CSS. 

1. (Pink) The spacing between the left edge of the field and the text is too big. Looks like its about 14-15 px but should be 12 px. 
2. (Green) The button should be 34 px wide (and soon we will be changing that to 32 px wide to make it a square... but for now im told this should match DNA which still says 34 px.)
3. (Blue) The color of the icon is too dark. it should be gray 700. 

## Screenshots

Top image is spectrum's combo box (which should look the same as the date picker minus the chevron icon. Bottom is the CSS date picker. 
![image](https://user-images.githubusercontent.com/49041637/68816664-f747d480-0633-11ea-82e4-b889c8a4ad94.png)

Here's the same image with some spaces highlighted corresponding with the feedback above. 
![image](https://user-images.githubusercontent.com/49041637/68816793-5e658900-0634-11ea-8ce8-85bc18257a97.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by lazd** [comment]
@labrowne there are no tokens in DNA for this, but your comment seems to imply that there are? Can you double check? 

https://git.corp.adobe.com/Spectrum/spectrum-dna/blob/master/data/elements/combobox/ComboboxDefault.mjs

**Comment by lazd** [comment]
@labrowne I hardcoded a value for the width (34px wide _including_ the border). When it's added to DNA, we can revisit this.

Meanwhile, the left padding comes from Textfield and is, in fact, 12px, so no bug there. Yay!
