### ISSUE TITLE
Migrate release notes

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#4]
Release notes for the older versions should be migrated from internal Adobe github.

**Comment by GarthDB** [comment]
@filmaj @stevengill do you have a script to automate this?

**Comment by filmaj** [comment]
You mean the annotations attached to releases as listed over in https://git.corp.adobe.com/Spectrum/spectrum-css/releases ?

**Comment by filmaj** [comment]
Hmm those seem to have been migrated over just fine? https://github.com/adobe/spectrum-css/releases

**Comment by GarthDB** [comment]
It is just showing release notes for the latest versions added manually.

**Comment by filmaj** [comment]
Ah yes, I see. @trieloff [has blogged about how to move issues/labels/milestones](https://medium.com/adobetech/how-to-move-your-project-from-github-enterprise-to-open-github-1ca37fe77748) on our very own tech blog. In there we reference this project: https://github.com/ahadik/git_mover

I could take a look at adding migrating release notes support to it?

**Comment by GarthDB** [comment]
I'll run it

**Comment by GarthDB** [comment]
Done. Thanks @filmaj
