### ISSUE TITLE
Button with icon: Icon sizing and space between icon off

### ISSUE THREAD

**Issue by JacobDFrank** [adobe/spectrum-css#400]
## Description

The Icons used are smaller than those from the [icons](https://spectrum.corp.adobe.com/page/icons/) site. The spacing between the icons and the text is also too close when compared to the designs.

I have taken a screenshot and recreated how the buttons should actually look in Xd.

## Steps to reproduce

1. Go to http://opensource.corp.adobe.com/spectrum-css/
2. Click on ...
3. Observe ...

## Screenshots

![image](https://user-images.githubusercontent.com/11824340/68899714-1b182280-06e7-11ea-8156-86704a7faaed.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** 
Found in https://reactspectrum.blob.core.windows.net/reactspectrum/20e5131cfc8f65620868f16dc32defaedd215aaf/index.html?path=/story/button--variant-cta

Chrome on MacOS Catalina

**Comment by lazd** [comment]
@JacobDFrank can you please verify this against http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.15.1/docs/button-primary.html#variants ?

**Comment by JacobDFrank** [comment]
the labels are one pixel lower than they should be on desktop and all the labels are two pixels lower

**Comment by JacobDFrank** [comment]
Seems to be a react-spectrum rather than a css one.
