### ISSUE TITLE
Radio button: Text a few pixels too high up

### ISSUE THREAD

**Issue by JacobDFrank** [adobe/spectrum-css#402]
## Description

When compared to the designs the Label for radio buttons on mobile seems to be two pixels above where the designed label is. On desktop the text is 1 pixel above where it should be.

## Steps to reproduce

1. Go to http://opensource.corp.adobe.com/spectrum-css/
2. Click on ...
3. Observe ...

## Screenshots

###Mobile screenshot
![image](https://user-images.githubusercontent.com/11824340/68902995-9f21d880-06ee-11ea-98c9-268266053f34.png)

###Desktop screenshot
![image](https://user-images.githubusercontent.com/11824340/68902995-9f21d880-06ee-11ea-98c9-268266053f34.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** 
Found on https://reactspectrum.blob.core.windows.net/reactspectrum/20e5131cfc8f65620868f16dc32defaedd215aaf/index.html?path=/story/radio--default

**Comment by lazd** [comment]
@JacobDFrank can you please verify this against http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.15.1/docs/radio.html ?

**Comment by JacobDFrank** [comment]
the labels are one pixel lower than they should be on desktop and all the labels are two pixels lower
