### ISSUE TITLE
Switch label spacing slightly off

### ISSUE THREAD

**Issue by JacobDFrank** [adobe/spectrum-css#403]
## Description

This is the same problem as on the [Radio button component label bug](https://github.com/adobe/spectrum-css/issues/402). On the the Label for switches on mobile it seems to be two pixels above where the designed label is. On desktop the text is 1 pixel above where it should be.

## Steps to reproduce

1. Go to http://opensource.corp.adobe.com/spectrum-css/
2. Click on ...
3. Observe ...

## Screenshots

Desktop 
![image](https://user-images.githubusercontent.com/11824340/68904868-e494d480-06f3-11ea-8993-b53ce0df04fa.png)

Mobile
![image](https://user-images.githubusercontent.com/11824340/68904898-00987600-06f4-11ea-900a-889488e85d0f.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** 

https://reactspectrum.blob.core.windows.net/reactspectrum/20e5131cfc8f65620868f16dc32defaedd215aaf/index.html?path=/story/switch--default

**Comment by lazd** [comment]
@JacobDFrank can you please verify this against http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.15.1/docs/toggle.html ?

**Comment by JacobDFrank** [comment]
the labels are one pixel lower than they should be on desktop and all the labels are two pixels lower
