### ISSUE TITLE
Calendar day of the week letterspacing

### ISSUE THREAD

**Issue by NateBaldwinDesign** [adobe/spectrum-css#407]
## Description

Day of the week abbreviations are not using proper letterspacing. This typographic component should be inheriting style from the Typographic component "Detail", which offers proper letterspacing of `0.06em` from Spectrum DNA

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Click on Calendar component
3. Observe inspect `spectrum-Calendar-dayOfWeek` abbreviations. No letterspacing defined

## Expected behavior

Should have `letterspacing: 0.06em` 

## Screenshots

When displaying more than one character: 
![image](https://user-images.githubusercontent.com/13972198/68959345-19a03600-078b-11ea-9198-1bd99ada970c.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by lazd** [comment]
Hmm, we're not composing it using Detail, so that explains why it's not there.

That said, I would expect this to be a token in DNA. I don't see it here: https://git.corp.adobe.com/Spectrum/spectrum-dna/blob/master/data/elements/calendar/CalendarDefault.mjs#L36
