### ISSUE TITLE
Search field icon color on hover/active incorrect

### ISSUE THREAD

**Issue by pudjeeb** [adobe/spectrum-css#409]
## Description
Search field icon color should be `gray-800` on hover/active/key-focus, but it's currently not changing (stays `gray-700`)

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/search/#Standard
2. Hover/click on search field
3. Observe that icon color does not change

## Expected behavior
Icon color should turn from `gray-700` to `gray-800` on hover/key-focus/active. Not sure if this is a DNA thing (because it's still a contribution), but there's an alias token for icon colors that could be used here.

## Environment
 - **Spectrum CSS version:** @spectrum-css/search@2.0.0
 - **Browser(s) and OS(s):** Chrome Version 77.0.3865.120 on macOS 10.14.5

## Additional context
View XD file here: https://spectrum-contributions.corp.adobe.com/submissions/dynamic-search

**Comment by lazd** [comment]
@pudjeeb you're right, the color needs to change on hover/down/focus. However, it seems like it needs to be `gray-900`. I went ahead and used the DNA tokens, and that's the value I got. Looks like it comes from https://git.corp.adobe.com/Spectrum/spectrum-dna/blob/master/data/mixins/elements/field.mjs#L105
