### ISSUE TITLE
Combobox mouse focus weight

### ISSUE THREAD

**Issue by snowystinger** [adobe/spectrum-css#410]
## Description
Combobox with mouse focus switches between having slightly more weight on the top and on the bottom
https://opensource.adobe.com/spectrum-css/components/combobox/

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/combobox/
2. Click into a combobox, the first one will do
3. Grab the entire window to move it, start dragging it down slowly 1px at a time
4. Watch the top and bottom blue mouse focus
5. They will appear to gain and lose weight alternating, some half pixel calculation?

## Expected behavior
They should stay the same weight

## Environment
 - **Spectrum CSS version:** @spectrum-css/inputgroup@2.0.0
 - **Browser(s) and OS(s):** Chrome 78, FF latest

**Comment by GarthDB** [comment]
@snowystinger I'm having trouble reproducing it. I've tried in chrome latest on retina (5k iMac) and non retina displays. Also, there are no calculations being made that I can see. It is a `1px` border using the `border` property. There's no shadow hack, positioning, or anything else I can see that would be the likely culprit.
