### ISSUE TITLE
[CircleLoader] Style fidelity across zoom levels.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#411]
## Description
It may be a little out of the scope of the designs here, but when the zoom of the browser is altered, the delivery of the CircleLoader styles can degrade.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/circleloader/
2. Change the zoom via `command + +`
3. Observe degradation of design delivery.

## Expected behavior
Styles are consistent across zoom levels.

## Screenshots
![image](https://user-images.githubusercontent.com/1980008/69192228-023db180-0ad9-11ea-8063-9539687dd97f.png)
![image](https://user-images.githubusercontent.com/1980008/69192372-48931080-0ad9-11ea-934d-9ba2038a3bb8.png)

## Environment
 - **Spectrum CSS version:** 2.15.1
 - **Browser(s) and OS(s):** Chrome 78, MacOS

synced to jira: https://jira.corp.adobe.com/browse/CSS-137

**Comment by GarthDB** [comment]
We should update this back to a research spiked version that used SVG border animation instead of this hack now that we are dropping support for IE11.

**Comment by misterbrownlee** [comment]
Closing this, it's tracked in Jira
