### ISSUE TITLE
Label for the dropdown/select input should be illustrated as clickable

### ISSUE THREAD

**Issue by missmatsuko** [adobe/spectrum-css#417]
## Description

In [Platform Scale - Cursor hit areas](https://spectrum.adobe.com/page/platform-scale/#Cursor-hit-areas), the label for the dropdown/select input should be illustrated as clickable.

![Cursor hit areas image for desktop and mobile.](https://spectrum.adobe.com/static/images/platform-scale_areas_cursor@2x.png)

## Link to documentation

[Platform Scale - Cursor hit areas](https://spectrum.adobe.com/page/platform-scale/#Cursor-hit-areas)

## Additional context

Labels should be associated with their inputs. Labels can be clicked to move focus to their input.
https://www.w3.org/TR/WCAG20-TECHS/H44.html#H44-description
https://webaim.org/techniques/forms/controls#select

**Comment by GarthDB** [comment]
@missmatsuko Are you suggesting a cursor change over the label?

**Comment by missmatsuko** [comment]
I think the images have been updated already to fix the issue. Previously
only the checkbox and not the label were highlighted as click areas.

**Comment by misterbrownlee** [comment]
Thanks!
