### ISSUE TITLE
Meters/Bar Loaders with long labels wrap incorrectly

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#420]
## Description

It seems that something broke; meters and bar loaders with long labels wrap incorrectly.

## Steps to reproduce

1. Make a meter or barloader with a fixed width
2. Give it a long label
3. Observe the wrapping failure
4. Cry

```html
<div style="width: 168px">
  <div class="spectrum-BarLoader is-positive" value="26" role="progressbar" aria-valuenow="26" aria-valuemin="0" aria-valuemax="100">
    <div class="spectrum-BarLoader-label">Creative Cloud datennutzung insgesamt</div>
    <div class="spectrum-BarLoader-percentage">26%</div>
    <div class="spectrum-BarLoader-track">
      <div class="spectrum-BarLoader-fill" style="width: 26%;"></div>
    </div>
  </div>
</div>
```

## Expected behavior

Wraps on wraps

## Screenshots

![image](https://user-images.githubusercontent.com/201344/69998490-497d6680-150b-11ea-8bbc-b420f1ff8401.png)

## Environment
 - **Spectrum CSS version:** 2.15.1
 - **Browser(s) and OS(s):** Chrome on macOS

## Additional context

Related to work done in #176

**Comment by bernhard-adobe** [comment]
maybe the bar loader label could say something like "Creative Cloud Gesamtdatennutzung".
