### ISSUE TITLE
Popover with Menu padding incorrect

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#423]
## Description

Padding incorrect: should be using padding-x (0px) and padding-y (size-50) from DNA

See https://jira.corp.adobe.com/browse/SDS-3469?focusedCommentId=19624939&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19624939

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by jianliao** [comment]
Confirmed with Designer that the padding looks good. Nothing to fix.
