### ISSUE TITLE
Divider (Rule) vertical DNA tokens

### ISSUE THREAD

**Issue by LiveMethod** [adobe/spectrum-css#425]
Vertical variants currently get their width from the horizontal variant's height. These values are technically correct, but DNA now supports vertical variant for the Divider component.

`width: var(--spectrum-rule-large-height);` can become `width: var(--spectrum-divider-large-vertical-width);` etc

This may be blocked by https://github.com/adobe/spectrum-css/issues/193

**Comment by LiveMethod** [comment]
(not sure if I'm authorized to add the Component:Divider label)

**Comment by lazd** [comment]
Thanks @LiveMethod, it's not blocked by #193, we can use the new tokens as soon as we update DNA.

**Comment by lazd** [comment]
Note that, although this issue is closed, there is a fallback in place to work around a DNA bug (misspelling of `vertical`).
