### ISSUE TITLE
Status light text is 1px too low

### ISSUE THREAD

**Issue by LiveMethod** [adobe/spectrum-css#426]
<img width="295" alt="Screen Shot 2019-12-08 at 9 23 02 AM" src="https://user-images.githubusercontent.com/3277759/70393409-313f9880-199e-11ea-90be-181fc14dc30f.png">

Status light text baseline text is 1px too low relative to the circle

**Comment by lazd** [comment]
@LiveMethod what browser was this in, and did you happen to test in other browsers?

@bernhard-adobe was working on #402/#406/#403 and found differences between browsers in label height, so I want to make sure we're testing this all scenarios.
