### ISSUE TITLE
Switch circle doesn't slide/takes a long time to slide in Edge

### ISSUE THREAD

**Issue by LFDanLu** [adobe/spectrum-css#427]
## Description
When a user clicks on a Switch to activate it, the expected behavior is that the switch's handle slides over to the right. On Edge, this doesn't happen or takes a very long time to happen. 

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/toggle/ in Edge.
2. Click on the Switch ("Toggle Off")
3. Observe that the switch is activated, but the handle doesn't slide over to the right (

## Expected behavior
Expected behavior is that the switch's handle slides to the right

## Screenshots
![switchInEdge](https://user-images.githubusercontent.com/9661127/70466483-16415700-1a78-11ea-9898-8fb095543da2.PNG)

## Environment
 - **Spectrum CSS version:** @spectrum-css/toggle@2.0.0
 - **Browser(s) and OS(s):** Microsoft Edge 42.17/EdgeHTML 17.17 on Win 10, happens on EdgeHTML 18+ as well

## Additional context

I ran a performance check via Edge dev tools from initial click to eventual slide animation, lemme know if you want it (.diag file so can't put it here).

Replacing `var(--spectrum-switch-track-width)` and `var(--spectrum-switch-handle-size)` with `26px` and `14px` respectively gets rid of this issue locally but is a unviable fix since hardcoding those values means large scale doesn't work.
Googling reveals that there may be issues with Edge and using calc + variables, so not entirely sure what we can do here.

**Comment by lazd** [comment]
Ha, that's a fun one. Thanks for the detailed notes and diagnosis!

**Comment by lazd** [comment]
@LFDanLu is this still an issue with http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.18.0/docs/toggle.html ?

**Comment by LFDanLu** [comment]
@lazd yep still happens in Microsoft Edge 42 (Microsoft EdgeHTML 17), but this is a old version of Edge though. I can update and see if it helps

**Comment by lazd** [comment]
Just tried it locally as well, now I have the handle not sliding to "On" at all with Microsoft Edge 42.17134.1098.0 / Microsoft EdgeHTML 17.17134... I'll try updating too

**Comment by LFDanLu** [comment]
@lazd issue still happens for Microsoft Edge 44, but updating to the Chromium version of Edge fixes the issue (of course)

**Comment by lazd** [comment]
Still a problem in Microsoft Edge 44.18362.449.0 / Microsoft EdgeHTML 18.18363... I'll keep updating.

**Comment by lazd** [comment]
Yup, looks like we won't get the Chromium Edge for a little while. Once it's rolling out via Windows Update, we can close this.

**Comment by GarthDB** [comment]
@LFDanLu have you checked this in the latest Edge? Is it fixed?

**Comment by LFDanLu** [comment]
@GarthDB Yep, this is fixed in the latest chromium edge.
