### ISSUE TITLE
Commented out commons/fonts.css styles

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-css#428]
## Description

There's a "not used" comment here for some font variables:
https://github.com/adobe/spectrum-css/blob/master/components/commons/fonts.css#L16

## Expected behavior

Ideally this would at least get stripped from output. If the code shouldn't be outright deleted, a comment about when it might get used would be helpful.

## Additional context

Noticed this when updating our script to pull this in for spectrum-web-components.

**Comment by lazd** [comment]
The comments here are not present in build output in `dist/`, so we'll go ahead and close this.

It's worth noting that we're trying to kill commons, so this will die some day anyway :)
