### ISSUE TITLE
Textfield needs to support custom workflow icons

### ISSUE THREAD

**Issue by snowystinger** [adobe/spectrum-css#434]
## Description
The top position of the icons in textfields/searchfields/textarea is determined assuming that the icon is a UI Icon.
A ui icon is 16x16, however, we're supposed to be supporting people putting their own icons in there, like, refresh, that only exist as workflow icons and are 18x18.
We need a way to support both of these, most likely by having a class for each of the options.

**Comment by lazd** [comment]
DecoratedTextfield's `.spectrum-DecoratedTextfield-icon` class assumes a 18x18 icon and seems to work correctly:

```html
<div class="spectrum-DecoratedTextfield is-decorated">
  <label for="DecoratedTextField-single" class="spectrum-FieldLabel">Search</label>

  <input id="DecoratedTextField-single" placeholder="Enter your name" class="spectrum-Textfield spectrum-DecoratedTextfield-field" aria-invalid="false" type="text">

  <svg class="spectrum-Icon spectrum-Icon--sizeS spectrum-DecoratedTextfield-icon" focusable="false" aria-hidden="true" aria-label="ABC">
    <use xlink:href="#spectrum-icon-18-ABC"></use>
  </svg>
</div>
```

That said, it cannot position icons on the left (like Search etc). If we add support for left icons, would that satisfy this request?

I don't think we will ever allow Search to have a random UI icon, though. We can confirm with @badimon and friends.

**Comment by snowystinger** [comment]
All of these kinds

<img width="209" alt="Screen Shot 2019-12-10 at 9 51 24 AM" src="https://user-images.githubusercontent.com/698229/70556027-e73ceb00-1b34-11ea-88ec-d5eadb57efd9.png">
<img width="216" alt="Screen Shot 2019-12-10 at 9 50 43 AM" src="https://user-images.githubusercontent.com/698229/70556028-e73ceb00-1b34-11ea-9e40-73176420f48a.png">
<img width="210" alt="Screen Shot 2019-12-10 at 9 51 15 AM" src="https://user-images.githubusercontent.com/698229/70556029-e73ceb00-1b34-11ea-9a7e-cf2dce0e39f5.png">
<img width="210" alt="Screen Shot 2019-12-10 at 9 51 05 AM" src="https://user-images.githubusercontent.com/698229/70556030-e7d58180-1b34-11ea-8f18-0ecc14619da9.png">

**Comment by snowystinger** [comment]
I think I can close this because it's something we're in the process of contributing, so i don't think it's a bug on your side right now because you only have the search icon version
