### ISSUE TITLE
Icons page broken in dev site

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#435]
## Description

The icons page in the dev docs fails to fetch icons and CSS

## Steps to reproduce

1. Go to http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.15.1/icons/
2. It's quite broken

## Expected behavior

We see da icons

## Screenshots

![image](https://user-images.githubusercontent.com/201344/70554641-5a912d80-1b32-11ea-9699-65849e665848.png)

## Environment
 - **Spectrum CSS version:** 2.15.1
 - **Browser(s) and OS(s):** Chrome on macOS

## Additional context

Looks like we need to remap the URLs.

**Comment by GarthDB** [comment]
Icons page has been removed.
