### ISSUE TITLE
Disabled Text area should have disabled drag handle

### ISSUE THREAD

**Issue by matthewdeutsch** [adobe/spectrum-css#443]
## Description
Disabled Text area should have disabled drag handle

## Steps to reproduce

1. go to https://opensource.adobe.com/spectrum-css/components/textarea/

## Expected behavior
Should not be able change the size of a Disabled Text area 

## Screenshots
![image](https://user-images.githubusercontent.com/700930/70583572-ff335f80-1b72-11ea-9dde-d76b9bd169de.png)

## Environment
 - **Spectrum CSS version:** latest
 - **Browser(s) and OS(s):** all

**Comment by lazd** [comment]
I don't think we can make it appear disabled, but we can go ahead and hide it when disabled.
