### ISSUE TITLE
Table should support a non-interactive mode

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#450]
## Description

There should be an option to disable the hover/active states of table rows.

## Why do you need this feature or component?

There are cases where a table will contain non-interactive data that does not require a hover state.

## Additional context

This was requested by a React Spectrum consumer.

**Comment by mitchell-foote-adobe** [comment]
Here is the context and use case. 

We have a table that holds data, but doesn't have any interactive action to it. When a user hovers or clicks, it shows a clicking cursor, and they will expect interactive behavior. We don't provide such interactive behavior. Customers would be confused at the lack of this behavior. 

![Screen Shot 2019-12-12 at 1 18 02 PM](https://user-images.githubusercontent.com/50968569/70745789-da112f00-1ce1-11ea-91f3-505342337730.png)

We need the ability to turn off the interactivity to improve the experience.

**Comment by lazd** [comment]
I wonder if this should be the default, and you have to add `--interactive` to get the row highlight and cursor... Perhaps you can add it on a per-row basis or on the table itself... Thoughts?

**Comment by bernhard-adobe** [comment]
my my POV that decision could be made by asking
What is the more common use case?
What might be more common in the future?

**Comment by GarthDB** [comment]
More than a `noninterative` mode we should probably make a new component that has similar styling as table.

**Comment by misterbrownlee** [comment]
This is an ongoing conversation with React, but we don't need to track the work here.  Outcomes from that conversation will turn into tasks in Jira. Closing this.
