### ISSUE TITLE
Search icon is too close to field text in large scale

### ISSUE THREAD

**Issue by LFDanLu** [adobe/spectrum-css#457]
## Description
The padding between the field's text and the icon looks too small in large scale. This is because the padding between the field's text remains static between medium and large scale.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/search/
2. Switch to Large scale
3. See that the padding between the search icon and the text is pretty small

## Screenshots

Large
![image](https://user-images.githubusercontent.com/9661127/71136064-6b881180-21b8-11ea-8136-b90c6dfc34b9.png)

vs

Medium
![image](https://user-images.githubusercontent.com/9661127/71136087-7b9ff100-21b8-11ea-9780-d27cc5c7589f.png)

## Environment
 - **Spectrum CSS version:** @spectrum-css/search@2.0.0
 - **Browser(s) and OS(s):** 

## Additional context
I've made changes here: https://github.com/adobe/react-spectrum-v3/pull/135/files that mimics the css styling for decorated Textfields and TextAreas (see https://excelerate-team.slack.com/archives/G8R3V30FL/p1576270697011700?thread_ts=1576179094.077500&cid=G8R3V30FL). Lemme know if the vars are ok

**Comment by jianliao** [comment]
@lazd, 
If you look into how @LFDanLu fix this issue in  RSPv3, he is using `padding-inline-start` and `padding-inline-end` instead of `padding-left` and `padding-right`. I checked the [document](padding-inline-start). These two css properties provide better support for right-to-left or vertical text orientation. Should we also consider using them ?

Here is the browser supporting status: https://caniuse.com/#search=padding-inline-start
![image](https://user-images.githubusercontent.com/1207520/72461705-6ea8fa00-3784-11ea-9a3f-4091d16a4d7a.png)

**Comment by lazd** [comment]
@jianliao not yet, we will use those properties when we add RTL support.

**Comment by jianliao** [comment]
The fix had been merged to the master branch of spectrum-dna project. Waiting for a DNA release and spectrum-css update to fix the issue.

**Comment by lazd** [comment]
@jianliao now that we have updated DNA, can we finish this issue?

**Comment by jianliao** [comment]
@lazd Only `5.24.0` and above contains the fix for this issue, but we're still on `5.23.0`.

**Comment by lazd** [comment]
@jianliao ok, let's upgrade and fix it. @GarthDB, I thought this would come in from the focus-ring updates?

**Comment by jianliao** [comment]
Do you mean this change? https://github.com/adobe/spectrum-css/commit/d87e9a54dd822146faccc5df9c69ac56aa1ce790#diff-0f7ca5a046722e4b2b8eb1321ee79a53

**Comment by lazd** [comment]
@jianliao yes, the script was ran, but the dep was not saved into `package.json` accidentally. Can you check the `vars/` folder in master and see if your variable update is present?

**Comment by jianliao** [comment]
Confirmed. The variable update for `spectrum-search.css` is not there.

**Comment by lazd** [comment]
Ok, then can you work with @GarthDB to make sure his `6.x` beta branch is updated?

**Comment by lazd** [comment]
@jianliao I also wonder if the work in #615 fixes this issue? If so, you can go ahead and close it.

**Comment by jianliao** [comment]
@lazd I just verified it on the branch of #615. Now medium and large are consistent, but the width of gap between Magnifier and Text is wrong. It is too close now.
