### ISSUE TITLE
Support for Types CSS Custom Properties in exported Packages?

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#459]
## Description
Spectrum CSS exports a large number of CSS Custom Properties that can be difficult to grok and parse directly out of the CSS, particularly when there are literally 100s for a single component. As such, we're looking at extended ways to document the Spectrum Web Components so that users understand more clearly how to customize their look.

To this end, I'm interested in learning whether or not the Spectrum CSS team has interest in exporting types of for their CSS Custom Properties, a la https://web.dev/css-props-and-vals/ At this time, we don't really have a large need for these to be used in live code, which is great due to the current support of this feature. However, at the tooling level, this could go a long way to better supporting the documentation that we'd like to be building for our components.

Being able to parse this more cleanly (and have actual type information available) would allow for comments along the lines of:
![](https://user-images.githubusercontent.com/1156657/70911376-cb779000-1fdf-11ea-8d02-2fd4fa2f6929.png)
or external documentation the likes of:
![](https://user-images.githubusercontent.com/1156657/70911478-fb269800-1fdf-11ea-899b-f1434be1a6d3.png)

synced to jira: https://jira.corp.adobe.com/browse/CSS-134

**Comment by lazd** [comment]
This would be pretty cool, but we would need this data to be captured at the DNA level. I filed https://jira.corp.adobe.com/browse/SDS-4747 to track this.

**Comment by misterbrownlee** [comment]
Blocked by DNA.
