### ISSUE TITLE
Circle Loader Breaks Using dir="rtl"

### ISSUE THREAD

**Issue by jcmitch** [adobe/spectrum-css#46]
### Expected Behavior
Loader doesn't break under dir="rtl"
### Actual Behavior
Animation/layout of Circle Loader is broken
### Reproduce Scenario (including but not limited to)
Add `dir="rtl"` to any ancestor of Circle Loader
#### Steps to Reproduce
Add `dir="rtl"` to any ancestor of Circle Loader
#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
Chrome 70
#### Spectrum-CSS version
Current
#### Sample Code that illustrates the problem
N/A 
#### Screenshots (if applicable)
![rtl](https://user-images.githubusercontent.com/6447475/49808280-0847e180-fd11-11e8-8216-d6e992968dda.gif)

**Comment by GarthDB** [comment]
@jcmitch great find - would you want to work on a pull request?

**Comment by jcmitch** [comment]
@GarthDB Sure I can do that. 

What do you think about just adding `direction: ltr;` to the `spectrum-CircleLoader` class? I can't think of a reason it would be a problem to do so. Easy fix that should pretty much me break-proof to any layout changes in the future.

**Comment by GarthDB** [comment]
@jcmitch seems like a great and simple solution.
