### ISSUE TITLE
Rename Toggle to Switch

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#460]
## Description
`ToggleSwitch` is named in the file structure as `toggle`, while it's described as `Switch` Besides missing a common naming convention, this causes the component to not be in alphabetical order in the SideNav. I think it should have a consistent naming. To me, `Toggle`, `Switch` or `ToggleSwitch` are all good names.

## Link to documentation
https://opensource.adobe.com/spectrum-css/components/toggle/

**Comment by lazd** [comment]
@Harbs agreed, we need to rename the component package itself for this to happen. It should be named [Switch to match Spectrum](https://spectrum.adobe.com/page/switch/).

**Comment by GarthDB** [comment]
In progress with #855
