### ISSUE TITLE
Spectrum CSS NextJS Website should use Custom Properties approach

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#461]
## Description

Currently, the NextJS website uses the multistop strategy, which is legacy. We should be using Custom Properties (see [legacy usage](https://github.com/adobe/spectrum-css/blob/master/README-legacy.md#legacy-usage)).

## Link to documentation

https://opensource.adobe.com/spectrum-css/

**Comment by misterbrownlee** [comment]
@GarthDB schedule a meeting with me to help me understand the concern here, and lets figure where we go from there.  Thanks

**Comment by GarthDB** [comment]
We had a rendering issue on the nextjs react components that stopped me from using the custom properties approach originally.
