### ISSUE TITLE
Quiet Link component not showing focus state in IE or Edge navigating with keyboard

### ISSUE THREAD

**Issue by majornista** [adobe/spectrum-css#462]
## Description
IE and Edge do not support CSS Level 3 text-decoration-style prop: https://caniuse.com/#feat=mdn-css_properties_text-decoration-style. To achieve the same effect we would need to provide a workaround like this: https://codepen.io/mijordan/pen/ExaoeMV

## Steps to reproduce

1. Using IE11, Edge, or Edge Canary, go to https://opensource.adobe.com/spectrum-css/components/link/
2. Use Tab key to navigate through the Link component examples paying particular attention to the rendered focus style for the [Link - Quiet](https://opensource.adobe.com/spectrum-css/components/link/#Link---Quiet) and [Link - Over Background](https://opensource.adobe.com/spectrum-css/components/link/#Link---Over-Background)  variants.
3. The double underline focus style does not display for Quiet or Over Background link variant examples in either IE, Edge or Edge Canary.

## Expected behavior
Links should render the focused style using a double-underline in the Quiet or Over Background variants.

## Environment
 - **Spectrum CSS version:** [@spectrum-css/link@2.0.3](https://github.com/adobe/spectrum-css/releases/tag/%40spectrum-css%2Flink%402.0.3)
 - **Browser(s) and OS(s):** Windows IE 11.476.18362.0, Edge 44.18326.449.0, Edge Canary 81.0.385.0

## Additional context
Relates to https://jira.corp.adobe.com/browse/CCD-9411 and https://github.com/adobe/react-spectrum/issues/729

**Comment by GarthDB** [comment]
@majornista `text-decoration-style: double;` is supported by Edge since they switched to Chromium. https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style#Browser_compatibility
We're also dropping support for IE, so I'm going to close this issue.
