### ISSUE TITLE
Icon missing from popover dialog example

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#464]
## Description
Icon missing from popover dialog example

## Link to documentation
https://opensource.adobe.com/spectrum-css/components/popover/#Popover---Dialog-style

## Additional context
The success dialog has the following markup:
````
  <div class="spectrum-Dialog-header">
    <div class="spectrum-Dialog-title">Success Popover</div>
    <div class="spectrum-Dialog-typeIcon"></div>
  </div>
````
The `typeIcon` obviously does not show because there's no content.

**Comment by lazd** [comment]
Hmm yeah, looks like it needs the SVG in there for the Error example.

The Success version no longer exists in Spectrum, so that can be removed.

**Comment by lazd** [comment]
Blocked by #492
