### ISSUE TITLE
Reference to spectrum-Dialog--success

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#465]
## Description
I'm not sure if there's supposed to be a success variant for Dialog, but there seems to be an inference that there is.

## Link to documentation
https://opensource.adobe.com/spectrum-css/components/popover/

## Additional context
The "success popover" has the following markup:
````
<div class="spectrum-Popover spectrum-Popover--dialog spectrum-Popover--top spectrum-Dialog--success is-open" style="max-width:320px">
````
I'm assuming the idea is that `spectrum-Dialog--success` would color the header text similar to the `spectrum-Dialog--error` variant, but there's no CSS which does anything with the `spectrum-Dialog--success` selector.

**Comment by lazd** [comment]
The Success version no longer exists in Spectrum, so that example should be removed. Looks like we never removed the success version when that happened. Thanks for the report!
