### ISSUE TITLE
Spinner is appearing distorted at Resolution: 1366*768 in Chrome.

### ISSUE THREAD

**Issue by shitizag** [adobe/spectrum-css#466]
## Description

Spinner should not be distorted at Resolution: 1366*768 in Chrome. Since CCD is a CEF based application, this issue is visible in CCD also.

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Click on ...
3. Observe ...

## Expected behavior

Spinner should not be distorted

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**  Chrome

## Additional context

Original Issue Link : https://jira.corp.adobe.com/browse/CCD-4264

**Comment by lazd** [comment]
Sounds fun @shitizag.

1. Can you upload a picture or a screen recording ?
1. Does it only happen at exactly that resolution?
1. Can you paste the code you're using?

**Comment by shitizag** [comment]
Please check the video as well as screen shot in https://jira.corp.adobe.com/browse/CCD-4264

Usage of Wait in code :  https://git.corp.adobe.com/ccd/ccd-component-cloud-sync/blob/develop/src/web/fileSyncTile/syncStatusIcon.tsx#L28

**Comment by GarthDB** [comment]
We currently aren't supporting CEF in Spectrum CSS.
