### ISSUE TITLE
Some CSS variables are defined as "[object Object]"

### ISSUE THREAD

**Issue by achicu** [adobe/spectrum-css#469]
There are a few variables that are defined as "[object Object]". I am guessing this is a side effect of a generator being used. Should we remove or fix these values?

https://github.com/adobe/spectrum-css/blame/master/components/vars/css/scales/spectrum-large.css#L100

**Comment by lazd** [comment]
Hey @achicu good catch. Looks like there was a mistake in DNA where an object was ending up in the output that should have been resolved against the scale being processed. That made its way down into Spectrum CSS and manifested as the `[object Object]` error.

Here's the fix in DNA: https://git.corp.adobe.com/Spectrum/spectrum-dna/pull/346/files#diff-09f6d1357db57beb20f16020473f0c3eR32

Once we update DNA, this issue will be fixed.

**Comment by lazd** [comment]
@GarthDB since you're working on tokens and will be updating them in CSS soon, I'll go ahead and assign this issue to you.

**Comment by lazd** [comment]
Fixed in the latest release.
