### ISSUE TITLE
Docs site should use <code> tags for Typograph-Code example instead of <p> tags

### ISSUE THREAD

**Issue by filmaj** [adobe/spectrum-css#47]
### Expected Behavior

The sample markup for Typography-Code uses `<code>` tags.

### Actual Behavior

The sample markup for Typography-Code uses `<p>` tags.

**Comment by GarthDB** [comment]
We’re currently using p tags!? :facepalm:

**Comment by filmaj** [comment]
Might be nice to add multi-line markup for code, too, i.e. `<pre><code></code></pre>`, I think, is what e.g. markdown triple-ticks get converted to HTML as. Thoughts?

**Comment by GarthDB** [comment]
Yes, that’s the common practicd
