### ISSUE TITLE
Flexible Action Bar unclear or not working

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#470]
## Description
The Action Bar page has two variations: Standard and Flexible. There is no apparent difference between the two on the documentation page.

## Link to documentation
https://opensource.adobe.com/spectrum-css/components/actionbar/

**Comment by lazd** [comment]
Something seems to be wrong with the way it's rendered on the NextJS site. @GarthDB can you look into this?

You can see the difference on the dev site: http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.15.2/docs/actionbar.html

**Comment by GarthDB** [comment]
Fixed.
