### ISSUE TITLE
Disabled Avatar isn't

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#471]
## Description
The disabled avatar should have a lower opacity

## Link to documentation
https://opensource.adobe.com/spectrum-css/components/avatar/

## Additional context
It looks like the opacity is set to NaN. I'm guessing this is a React bug.

**Comment by lazd** [comment]
Duplicate of #340, already fixed. See http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.15.2/docs/avatar.html

**Comment by Harbs** [comment]
Ah. That explains why it worked for me... ;)

**Comment by lazd** [comment]
Sure does! Thanks for the report!
