### ISSUE TITLE
Documentation site out of date

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#473]
## Description

Components on the Next.js documentation site are out of date; many have had two releases since the launch, and the site still shows the October 2.0.0 releases.

## Link to documentation

https://opensource.adobe.com/spectrum-css/components/button-cta/

## Additional context

Bugs are being reported that have already been fixed because of this:

* #471 
* #470

**Comment by GarthDB** [comment]
I updated the site to the latest release, I'll open a new issue to handle the metadata changes in typography.

**Comment by lazd** [comment]
@GarthDB it's not just metadata changes, the new Typography is not loading at all: https://opensource.adobe.com/spectrum-css/components/typography/

**Comment by GarthDB** [comment]
@lazd I listed that in https://github.com/adobe/spectrum-css/issues/534 . I'm looking into it today, including updating typekit.
