### ISSUE TITLE
Use a separate class for components with a default variant

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#474]
## Description

When a component has 2 or more variants and one is considered default, we end up putting properties for that variant in the component class (i.e. `.spectrum-Rule` has the height/width from the `horizontal` variant). Then, when we want to implement the other variant, we end up overriding the code from the default variant (i.e. the `vertical` variant needs to explicitly override the height/width from the horizontal variant.

A simpler approach would be have a separate modifier class, `.spectrum-Rule--horizontal`, that is *required* for a horizontal rule. That would mean that only including `.spectrum-Rule` results in something that doesn't render at all (or looks funny), but that's currently the case for `.spectrum-Button` sooo...

This would result in a breaking change for all components that have a "default" variant.

## Why do you need this feature or component?

This simplifies the CSS and removes the overrides required in subsequent variants.

## Additional context

@snowystinger brought this up in https://github.com/adobe/spectrum-css/pull/456#issuecomment-573811428.

synced to jira: https://jira.corp.adobe.com/browse/CSS-141

**Comment by misterbrownlee** [comment]
@lazd will this still be needed after we refactor for the new token and API changes?

**Comment by lazd** [comment]
Yes, this will still be an issue. This is an overall API design decision for CSS classnames -- whether to have a "default" or to require that you define the value of each possible API option using a classname. For t-shirt sizing, we went with the latter - you MUST define `whatever--sizeM` to get the "default" of medium sized buttons. I think that's the right thing to do.
