### ISSUE TITLE
Vertical Rule should not set a 100% height

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#475]
## Description

The current Rule implementation assumes a non-flex context and specifies a height of 100%, which must be overridden to use a flex context. This doesn't lend itself nicely to the most common use cases.

Since this changes the default rendering behavior, this is a breaking change.

## Steps to reproduce

1. Put a vertical Rule in a flex container
2. Observe doesn't fill vertical space

## Expected behavior

It fills vertical space.

## Environment
 - **Spectrum CSS version:** 2.15.2
 - **Browser(s) and OS(s):** all

## Additional context

See #456 

synced to jira: https://jira.corp.adobe.com/browse/CSS-133

**Comment by GarthDB** [comment]
We still need to dust off this discussion and address this.

**Comment by misterbrownlee** [comment]
Closing this, it's tracked in Jira
