### ISSUE TITLE
Small Card description

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#478]
## Description
The small card description does not look right:

> Small cards should not be used without --quiet.

The card is in fact used without `--quiet` and adding `--quiet` messes up the styling

## Link to documentation
https://opensource.adobe.com/spectrum-css/components/card/

**Comment by lazd** [comment]
Hmm, you're right. Paging Dr. Downtown Lindsay Browne @labrowne, what's the scoop on Small Quiet cards?

**Comment by labrowne** [comment]
Quiet cards can be standard or quiet 🙂

**Comment by lazd** [comment]
There you have it, we need to remove the bit of documentation that says they must be `--quiet`, and we need to add a `--quiet` example.

**Comment by GarthDB** [comment]
Add example to the docs.
