### ISSUE TITLE
Stepper up/down buttons cause form submit

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#485]
## Description
When clicking on the stepper button, the form is submitted and the web page is reloaded with a new link.

## Link to documentation
https://opensource.adobe.com/spectrum-css/components/form/

## Additional context
This is likely a bug in the implementation of the stepper component (if there is one). The button in the stepper is resolved by the browser as the default submit button, so clicking on the button submits the form. The click event should have preventDefault() on it to prevent the form from being submitted. Alternately, there might be a designated submit button.

I'm not sure whether this should be defined as an actual documentation bug, but it was definitely annoying/puzzling to me when I encountered it.

**Comment by lazd** [comment]
@Harbs sounds like we need to add `type="button"` to the Stepper markup. Thanks!

**Comment by GarthDB** [comment]
Stepper uses button elements now so this should be fixed.
