### ISSUE TITLE
Ability to hide certain examples

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#491]
## Description

Some examples that are required for testing corner-cases, such as ultra-long words, very large or very small widths, etc are not suitable for general examples for the components, yet are still required in order to validate fixes and test for regressions.

It should be possible to hide those examples from the public site, so that we don't have to have weird scenarios present that may confuse users.

## Link to documentation

https://opensource.adobe.com/spectrum-css/components/radio/#Standard
![image](https://user-images.githubusercontent.com/201344/72919280-0914ba80-3cfc-11ea-8f38-dc5a913807ff.png)

## Additional context

https://github.com/adobe/spectrum-css/pull/482#pullrequestreview-346761288

**Comment by misterbrownlee** [comment]
Let's just separate tests from documentation
