### ISSUE TITLE
Rating selection marker out-of-place

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#493]
## Description
When hovering over the Rating component, there is an underline which highlights the selected star. It's too high and is obscured by the fill until moving to the left and then it just looks odd.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/rating/#Selected
2. Place your mouse cursor over the first star.
3. Observe a strike-through on the middle star.

## Expected behavior
The strike-through should be an underline as described here: https://spectrum.adobe.com/page/rating/#Behaviors

## Screenshots
Too lazy to grab screenshots... ;)

synced to jira: https://jira.corp.adobe.com/browse/SDS-7335

**Comment by lazd** [comment]
This does not seem to be an issue on the dev site: http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.18.0/docs/rating.html

**Comment by misterbrownlee** [comment]
We don't support CEF, closing.
