### ISSUE TITLE
DecoratedTextfield icon misaligned

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#494]
## Description

It seems the decorated textfield's icons are slightly misaligned. They use an older `icon-frame` variable for positioning, which seems to be wrong.

## Steps to reproduce

1. Go to http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.15.2/docs/decoratedtextfield.html
2. Go to http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.15.2/docs/textfield.html
3. Observe icon alignment doesn't match for both Text area and Text field

## Expected behavior

It should match!

## Screenshots

DecoratedTextfield: 
![image](https://user-images.githubusercontent.com/201344/72955472-e82a8480-3d50-11ea-802b-1b4757593e9f.png)

Textfield:
![image](https://user-images.githubusercontent.com/201344/72955486-f7a9cd80-3d50-11ea-9144-3da5951404ee.png)

The same is true for the multiline (text area).

## Environment
 - **Spectrum CSS version:** 2.15.2
 - **Browser(s) and OS(s):** Chrome on macOS

## Additional context

Discovered while testing #490

**Comment by lazd** [comment]
We need mocks for what a textarea looks like when it's multiline, has a height greater than one line, and has an icon. @NateBaldwinDesign @badimon?

**Comment by NateBaldwinDesign** [comment]
![image](https://user-images.githubusercontent.com/13972198/73083411-5aea4b80-3e88-11ea-9055-3ef28aabea17.png)

Same tokens that you use in `textfield` would be available and used in the same context for `textarea`, ie, `text**area**-icon-margin-left` shown in this image.

**Comment by lazd** [comment]
Oh so we're doing this totally wrong then, in both Textfield:

![image](https://user-images.githubusercontent.com/201344/73092185-f54e8d00-3e90-11ea-81ef-538e528fe875.png)

and Decorated Textfield:

![image](https://user-images.githubusercontent.com/201344/73092197-fd0e3180-3e90-11ea-9e3d-0be51d3f2567.png)
