### ISSUE TITLE
Components are not rendering in Electron js 

### ISSUE THREAD

**Issue by Elvincth** [adobe/spectrum-css#501]
## Description
Only button can be render , others components  e.g. action bar, check box are not rendering or well styling.

## Screenshots

![image](https://user-images.githubusercontent.com/6602723/73116611-2f448f80-3f74-11ea-8d4e-8c344c58ea64.png)
![image](https://user-images.githubusercontent.com/6602723/73116615-4aaf9a80-3f74-11ea-9748-917734659f24.png)
![image](https://user-images.githubusercontent.com/6602723/73116620-569b5c80-3f74-11ea-8e38-db65f9358ce9.png)
![image](https://user-images.githubusercontent.com/6602723/73116624-61ee8800-3f74-11ea-8abb-9892bf3f27c4.png)

## Environment
 - **Spectrum CSS version:Latest
 - **Browser(s) and OS(s):We are using Node.js 12.8.1, Chromium 78.0.3904.130, and Electron 7.1.10.

**Comment by GarthDB** [comment]
Are you building the CSS as described in the README documentation? There are others who have successfully used Spectrum
CSS in electron so I don’t think it’s being compiled correctly in this case.

**Comment by Elvincth** [comment]
> Are you building the CSS as described in the README documentation? There are others who have successfully used Spectrum
> CSS in electron so I don’t think it’s being compiled correctly in this case.

Thanaks a lot for you quick reply!
Yes I did follow the README, and installed all the css and icons through npm.

**Comment by Elvincth** [comment]
Problem fixed Make sure you are not stupid as me remember to inculded the gobal var of the compontes you wanted to use e.g. 

<link rel="stylesheet" href="node_modules\@spectrum-css\spectrum-css\dist\components\accordion\index-vars.css">
