### ISSUE TITLE
Long dropdown in Search Within shrinks Search field to unacceptable size

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#503]
## Description
When the dropdown of a "Search Within" has very long text, there's no room for the search field.

## Steps to reproduce

1. Add a dropdown item: "A very very very very very very long item"
2. Select it.
3. Observe that there's no room to type in search text.

## Expected behavior
There should be a maximum relative size to the dropdown so there's room for the search field.

## Screenshots
![Screenshot 2020-01-27 11 19 12](https://user-images.githubusercontent.com/395968/73162650-f2ed6c80-40f6-11ea-8b27-64702afcb338.png)

synced to jira: https://jira.corp.adobe.com/browse/CSS-130

**Comment by lazd** [comment]
@harbs it does look like we need a sensible `min-width` on the search field here. Thanks!

**Comment by GarthDB** [comment]
Still an issue

**Comment by Harbs** [comment]
FWIW, my suggested fix is here: https://github.com/adobe/spectrum-css/issues/880#issuecomment-685673492
