### ISSUE TITLE
Spectrum DNA 5.22.0 1px offset issues

### ISSUE THREAD

**Issue by bernhard-adobe** [adobe/spectrum-css#507]
## Description

After updating to Spectrum DNA 5.22.0 a lot of components are off by 1px. 

Example VR test is: https://spectrum-visual-regression.ci.corp.adobe.com/job/spectrum-css-vr-test-asset/186/artifact/spectrum-css/backstop_data/html_report/index.html

This came up with the visual testing on #408

## Steps to reproduce

Update DNA to 5.23.0. 
run:

```
yarn install 
yarn add -W -O @spectrum/spectrum-dna

cd components/vars
npm run update
```

a test branch is `SDS-2513-dna-test` has the package.json updates already. 

## Expected behavior
no visual changes

## Screenshots

one of the 77 examples: 

![](https://user-images.githubusercontent.com/52184321/73322915-95dadf00-41fa-11ea-95d8-17d26e35b5f9.png)

## Environment
Every browser independent of Spectrum CSS version

**Comment by bernhard-adobe** [comment]
VR test for DNA  `5.22.0` reduces the issues down from 70 to 40: https://spectrum-visual-regression.ci.corp.adobe.com/job/spectrum-css-vr-test-asset/190/artifact/spectrum-css/backstop_data/html_report/index.html

**Comment by bernhard-adobe** [comment]
This is a bug that got introduced in DNA 5.22.0 by removing the following tokens:

```  --spectrum-alias-heading-display1-text-size: var(--spectrum-global-dimension-font-size-1100);
  --spectrum-alias-heading-xxxl-text-size: var(--spectrum-global-dimension-font-size-1100);
  --spectrum-alias-heading-display1-margin-top: var(--spectrum-global-dimension-font-size-1000);
  --spectrum-alias-heading-xxxl-margin-top: var(--spectrum-global-dimension-font-size-1000);
  --spectrum-alias-heading-display2-text-size: var(--spectrum-global-dimension-font-size-1000);
  --spectrum-alias-heading-xxl-text-size: var(--spectrum-global-dimension-font-size-1000);
  --spectrum-alias-heading-display2-margin-top: var(--spectrum-global-dimension-font-size-900);
  --spectrum-alias-heading-xxl-margin-top: var(--spectrum-global-dimension-font-size-900);
  --spectrum-alias-heading1-text-size: var(--spectrum-global-dimension-font-size-900);
  --spectrum-alias-heading-xl-text-size: var(--spectrum-global-dimension-font-size-900);
  --spectrum-alias-heading1-margin-top: var(--spectrum-global-dimension-font-size-800);
  --spectrum-alias-heading-xl-margin-top: var(--spectrum-global-dimension-font-size-800);
  --spectrum-alias-heading2-text-size: var(--spectrum-global-dimension-font-size-700);
  --spectrum-alias-heading-l-text-size: var(--spectrum-global-dimension-font-size-700);
  --spectrum-alias-heading2-margin-top: var(--spectrum-global-dimension-font-size-600);
  --spectrum-alias-heading-l-margin-top: var(--spectrum-global-dimension-font-size-600);
  --spectrum-alias-heading3-text-size: var(--spectrum-global-dimension-font-size-500);
  --spectrum-alias-heading-m-text-size: var(--spectrum-global-dimension-font-size-500);
  --spectrum-alias-heading3-margin-top: var(--spectrum-global-dimension-font-size-400);
  --spectrum-alias-heading-m-margin-top: var(--spectrum-global-dimension-font-size-400);`

**Comment by bernhard-adobe** [comment]
filed issue in Spectrum-DNA: 
https://git.corp.adobe.com/Spectrum/spectrum-dna/issues/365

**Comment by lazd** [comment]
Oh snap, accidental breaking change. I wonder how the DNA token checks didn't catch this.

**Comment by bernhard-adobe** [comment]
this turns out to be not coming from DNA. (see comment in https://git.corp.adobe.com/Spectrum/spectrum-dna/issues/365). I would suspect the `npm run update` script is breaking here. @jianliao

**Comment by bernhard-adobe** [comment]
I closed https://git.corp.adobe.com/Spectrum/spectrum-dna/issues/365 as that seems to be not hte case.

**Comment by jianliao** [comment]
> this turns out to be not coming from DNA. (see comment in https://git.corp.adobe.com/Spectrum/spectrum-dna/issues/365). I would suspect the `npm run update` script is breaking here. @jianliao

@lazd Could you please shed some light on this ?

**Comment by jianliao** [comment]
I think it might relate to this PR: https://git.corp.adobe.com/Spectrum/spectrum-dna/pull/329

**Comment by lazd** [comment]
After tons of investigation, this was closed some time back. Yay!
