### ISSUE TITLE
Global sizes in CSS dimension globals are out of order

### ISSUE THREAD

**Issue by alangwilson** [adobe/spectrum-css#512]
## Steps to reproduce

1. Go to /components/vars/css/globals/spectrum-dimensionGlobals.css
2. 3 should come before 4.

**Comment by lazd** [comment]
This is interesting, I'm not sure why generated output wouldn't be in order here... Maybe we can just sort the keys before dumping them out...

**Comment by misterbrownlee** [comment]
This is fixed now
