### ISSUE TITLE
Overridden variables with calculated values calculate twice

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#514]
## Description

So this was very weird. If I overrode the same variable name, i.e.:

```css
--spectrum-textarea-padding-top: calc(var(--spectrum-textarea-padding-top) - var(--spectrum-textarea-border-size));
```

The output was:

```css
calc(
  var(--spectrum-textfield-padding-top, var(--spectrum-global-dimension-size-75))
  - var(--spectrum-textfield-border-size, var(--spectrum-alias-border-size-thin))
  - var(--spectrum-textfield-border-size, var(--spectrum-alias-border-size-thin))
)
```

But if I changed the name to `--spectrum-textarea-padding-top-adjusted`:

```css
--spectrum-textarea-padding-top-adjusted: calc(var(--spectrum-textarea-padding-top) - var(--spectrum-textarea-border-size));
```

I got the expected output:

```css
calc(
  var(--spectrum-textfield-padding-top, var(--spectrum-global-dimension-size-75))
  - var(--spectrum-textfield-border-size, var(--spectrum-alias-border-size-thin))
)
```

I'm not sure why this is happening, we should probably investigate further... It might be that the fallback variable substitution is happening incorrectly...

## Steps to reproduce

1. Define a variable that overrides itself with a calculation based on its previous value
2. Observe the output does the calculation twice
3. Cry

## Expected behavior

The calculation is done once

## Environment
 - **Spectrum CSS version:** 2.16.0
 - **Browser(s) and OS(s):** n/a

## Additional context

See https://github.com/adobe/spectrum-css/pull/490#discussion_r369305579 and https://github.com/adobe-private/react-spectrum-v3/pull/162#discussion_r369323201

synced to jira: https://jira.corp.adobe.com/browse/CSS-212

**Comment by lazd** [comment]
I also noticed that sometimes, during lots of dev, the overridden variables in `components/button/skin.css` don't take effect, specifically `--spectrum-actionbutton-quiet-border-size-key-focus`. `Control + C` and running `gulp dev` again seems to fix it.

Curious...

**Comment by misterbrownlee** [comment]
@lazd is this still a problem, and can we address as part of the work for the new token and API changes?

**Comment by lazd** [comment]
It will no longer be an issue when we move to core tokens as the substitution doesn't happen any longer.

**Comment by pfulton** [comment]
Let's try to look into this as we do our migration.
