### ISSUE TITLE
Warning variant of alert dialog

### ISSUE THREAD

**Issue by NateBaldwinDesign** [adobe/spectrum-css#515]
## Description

Warning variant for alert dialog. Issue for adding into DNA: SDS-5068

## Why do you need this feature or component?

Feature request from internal teams; already part of Spectrum Contributions

## Additional context

![image](https://user-images.githubusercontent.com/13972198/73697738-8b0dc780-469c-11ea-979f-015e5e86f6f4.png)

synced to jira: https://jira.corp.adobe.com/browse/CSS-213

**Comment by misterbrownlee** [comment]
There is no warning version of this, we have an alert error.  Closing because it's not needed anymore.

**Comment by pfulton** [comment]
We're out of sync with where design is at on this, and we do need to build out the warning variant. Syncing to Jira. We'll catch this during our migration and refactoring work.
