### ISSUE TITLE
Pagination Button text is 1px too high, padding is wrong

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#518]
## Description

Text and icon are 1px too high

## Steps to reproduce

1. Go to http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.16.0/docs/pagination-button-style.html
2. Screenshot the example
3. Paste into contribution XD file from https://spectrum-contributions.corp.adobe.com/submissions/pagination-button
4. Observe text is 1px too high, padding is wrong

## Expected behavior

It matches the design.

## Screenshots

![image](https://user-images.githubusercontent.com/201344/73707489-9834b180-46b0-11ea-9531-c50d2b1262c9.png)

## Environment
 - **Spectrum CSS version:** 2.16.0
 - **Browser(s) and OS(s):** Chrome on macOS

## Additional context

Found while testing #511 

synced to jira: https://jira.corp.adobe.com/browse/CSS-214

**Comment by GarthDB** [comment]
Next time we dig into pagination we should take a look to see if this is an issue still.

**Comment by GarthDB** [comment]
Looks like the icon is still 1px too high, but the text is positioned correctly checked by @lazd in 1.0.0 Xd and the current release of Spectrum CSS

**Comment by pfulton** [comment]
Hopefully, this will be taken care of during the migration to core tokens, but sync'ing it to Jira to be sure we don't miss it
