### ISSUE TITLE
Long text in Search Within overlaps clear button

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#522]
## Steps to reproduce

1. Go to http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.16.0/docs/searchwithin.html#standard
2. Type lots of text into the search field
3. Observe the text overlaps the clear button

## Expected behavior

The text stops before it hits the butt, like it does here http://localhost:3001/docs/search.html

## Screenshots

![image](https://user-images.githubusercontent.com/201344/73961347-3e570600-48c1-11ea-8c1c-30691dd50ca1.png)

## Environment
 - **Spectrum CSS version:** 2.16.0
 - **Browser(s) and OS(s):** Chrome on macOS

**Comment by GarthDB** [comment]
Looks fixed in the currently released version.
