### ISSUE TITLE
CSS files in doc site has errors

### ISSUE THREAD

**Issue by afzali** [adobe/spectrum-css#525]
## Description
There is a problem with the css and svg of site after using "gulp dev".
in fact the browser cannot find those files.

## Solution
adding "/dist" folder to all css in "dependencies.pug"

**Comment by lazd** [comment]
Interesting, I can't seem to reproduce this. You're saying that, after a fresh clone, running the following:

```
yarn install
gulp dev
```
The resulting page opened in the browser has broken CSS/SVG? Can you send a screenshot?

**Comment by lazd** [comment]
@afzali feel free to reply with more information and re-open this issue if you're still having problems.
