### ISSUE TITLE
Slider documentation broken

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#527]
## Description
Currently the slider documentation is not being delivered correctly.

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/slider/

## Expected behavior
You see the slider track.

## Screenshots

![image](https://user-images.githubusercontent.com/1156657/74064334-76913e00-49c0-11ea-8a9a-92ca89936a0d.png)

## Environment
 - **Spectrum CSS version:** Current
 - **Browser(s) and OS(s):** Chrome on Mac

**Comment by lazd** [comment]
Hey @Westbrook, this is actually just an error with the Next.js docs site, the dev site and the implementation itself doesn't have this problem: http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.17.0/docs/slider.html

We've already got #397 filed to track this. Thanks!
