### ISSUE TITLE
Tables with checkboxes have hardcoded top/bottom padding

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#528]
## Description

Looks like we're missing some CSS for table cells with checkboxes in them, as the docs have hardcoded padding.

## Steps to reproduce

1. Go to http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.16.0/docs/actionbar.html#tablewithactionbar
2. Look at the markup for table
3. Observe is has `<div class="spectrum-Table-cell spectrum-Table-checkboxCell" style="padding-top: 8px; padding-bottom: 8px">`

## Expected behavior

Kinda feels like `<div class="spectrum-Table-cell spectrum-Table-checkboxCell">` should be all that's required

## Screenshots

Removing padding results in incorrect positioning:
![image](https://user-images.githubusercontent.com/201344/74068129-ac79f680-49af-11ea-97fd-e316a1762f29.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** 

## Additional context

Discovered while testing #526

**Comment by GarthDB** [comment]
Looks like it's fixed in the [latest released version.
