### ISSUE TITLE
Stop maintaining 2 documentation websites

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#533]
## Description
We are currently maintaining 2 documentation websites.
I propose moving to use one for public-facing documentation and we can maintain a minimal html/css version for visual regression testing. That VR site doesn't need navigation or other documentation guidelines.

## Why do you need this feature or component?
reduce efforts

**Comment by misterbrownlee** [comment]
I'm going to close this for now and defer a conversation on how to separate testing code from documentation code when we get clear of the v3 work.  Thanks, @GarthDB
