### ISSUE TITLE
VRT improvements and documentation

### ISSUE THREAD

**Issue by misterbrownlee** [adobe/spectrum-css#536]
## Description
Finish visual testing improvements and make sure there's enough documentation in all the places.

## Link to documentation
TODO: what link goes here?

**Comment by lazd** [comment]
@jianliao given we have publicly accessible results, complete with the docs site, can we call this done? Do we need more docs?

**Comment by jianliao** [comment]
Hi @misterbrownlee @lazd 
I will document it as part of the README.md on adobe/spectrum-css-vr-test-results repo.

**Comment by jianliao** [comment]
This is blocked by the #630 .

**Comment by misterbrownlee** [comment]
This huge bucket is being planned internally, closing this
