### ISSUE TITLE
Popover arrows in large scale do not display correctly

### ISSUE THREAD

**Issue by matthewdeutsch** [adobe/spectrum-css#541]
## Description
Arrows in `Popover - Dialog style` large scale overlap with Dialog border

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/popover/
2. Click on Large Scale
3. Observe `Popover - Dialog style`

## Expected behavior
Arrow should not overlap with Dialog border

## Screenshots
![image](https://user-images.githubusercontent.com/700930/74987566-5154f480-53f0-11ea-9b8d-53f41a39fc94.png)

## Environment
 - **Spectrum CSS version:** 2.0.0
 - **Browser(s) and OS(s):** All

## Additional context

synced to jira: https://jira.corp.adobe.com/browse/CSS-131

**Comment by GarthDB** [comment]
We've dug into this before and I'm not sure it is possible to fix or worth fixing. The way we draw the tip and dealing with shadows and bg colors makes it hard to position correctly every time.

**Comment by misterbrownlee** [comment]
Let's research how to render popover arrows better

**Comment by misterbrownlee** [comment]
Closing this, it's tracked in Jira
