### ISSUE TITLE
[vars] Add support for Prefers Reduced Motion in "animationGlobals"

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#599]
## Description
I'm interested in seeing support for [Prefers Reduced Motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) added to the variables that are exposed for `animationGlobals`. It's something that could be relatively neatly added to the current custom properties that are included like so:
```
:root {
  --spectrum-global-animation-duration-4000: 2000ms;
}

/* becomes */

:root {
  --spectrum-global-prefers-motion: 1;
  --spectrum-global-animation-duration-4000: calc(var(--spectrum-global-prefers-motion) * 2000ms);
}

@media (prefers-reduced-motion: reduce) {
    :root {
        --spectrum-global-prefers-motion: 0;
    }
}
```

For actual "reduce" users it may make better sense to apply this as not absolute 0 so that some motion still occurs...

## Why do you need this feature or component?
- better support users who prefer reduced motion when interacting with a Spectrum based web application
- allow the use of this custom property in visual regression testing to make capturing "in usage" screenshots more reliable. For example, the SWC implementation of the Dropdown patter has visual regression for the "closed" state, but it would be great to have the "opened" state coverage as well. Currently, the animation time for the dropdown to actually open makes this specific screenshot irregular, so while custom handling could be developed to capture it, having this setting would allow for this case to be addressed as if it were no different than any other.

## Additional context
https://github.com/adobe/spectrum-css/blob/master/components/vars/css/globals/spectrum-animationGlobals.css#L2-L18

synced to jira: https://jira.corp.adobe.com/browse/CSS-129

**Comment by Westbrook** [comment]
Bump to review as part of the new 3.0 versions. A breaking change is a great moment to add a feature like this.

**Comment by misterbrownlee** [comment]
We will do a research spike on this

**Comment by misterbrownlee** [comment]
Closing this, it's tracked in Jira
