### ISSUE TITLE
Poor Scrolling Performance on CSS Demo/Documentation Page in Chrome/Safari

### ISSUE THREAD

**Issue by ericdrobinson** [adobe/spectrum-css#6]
### Expected Behavior
Scrolling through demos/documentation should be buttery smooth.

### Actual Behavior
Scrolling is very jerky, making for a poor experience.

### Reproduce Scenario (including but not limited to)
Visit [the documentation](http://opensource.adobe.com/spectrum-css/) and scroll in certain browsers.

#### Steps to Reproduce
1. Open the documentation using Chrome or Safari.
1. Navigate to the [demo/documentation](http://opensource.adobe.com/spectrum-css/) page.
1. Scroll the page at high speed.

**\*** Firefox 63 does not exhibit this issue, though its Performance developer tools may provide further insights when investigating.

#### Browser name/version/os
* Chrome Version 70.0.3538.77 (Official Build) (64-bit)
* Safari Version 12.0.1 (14606.2.104.1.1)

Both tested on macOS 10.14.1.

#### Spectrum-CSS version
2.5.1

#### Sample Code that illustrates the problem
N/A

#### Screenshots (if applicable)
N/A

**Comment by filmaj** [comment]
Indeed, can confirm this is an issue.

I did a quick-n-dirty Chrome devtools performance recording while scrolling. Here's a screencap:

<img width="1679" alt="screen shot 2018-11-20 at 3 08 48 pm" src="https://user-images.githubusercontent.com/52645/48802988-5485a000-ecd6-11e8-8f98-7601c51fa277.png">

It seems like the [docs.js set-hash-from-scroll scroll event handler](https://github.com/adobe/spectrum-css/blob/master/tasks/resources/docs/js/docs.js#L258-L271) is causing the slowdown. I'll take a look at possibly optimizing this.

**Comment by ericdrobinson** [comment]
I don't believe that you've quite narrowed down the issue correctly. The performance issue on my machine is **NOT** a CPU issue. It's a **Rendering** issue. Take a look at this screenshot:

<img width="1268" alt="chromeperf" src="https://user-images.githubusercontent.com/9142587/48857006-bee91f80-ed6c-11e8-8291-9974bcec2c41.png">

I'm on a 2018 15" MBP laptop. My CPU speed is not an issue.

The issue _may_ be related to updating the URL hash. If that were the case then I would expect it to be browser-dependent: Chrome, for instance, may trigger a repaint when the hash is changed. **If** that turns out to be the case then a valid approach to fixing this may be to only update the hash when [scrolling ends](https://gomakethings.com/detecting-when-a-visitor-has-stopped-scrolling-with-vanilla-javascript/).

I would highly recommend digging into what could cause Rendering issues here. [This](https://developers.google.com/web/tools/chrome-devtools/rendering-tools/#paint_and_composite) may be a good starting point.

That said, why aren't you guys using the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) [[polyfill](https://github.com/w3c/IntersectionObserver/tree/master/polyfill)] for this?

Also, as a bit of extra feedback, updating the history as you do is a usability issue in-and-of itself. You **break** the browser's back button in this manner. Not only does hitting the back button **NOT** jump you back to the section in question, but you have to actually hit the back button a whole lot to get back to the page that linked you to the documentation if you did any serious scrolling. This is why most pages don't update the hash automatically but provide links that allow you to copy that specific location in case you need to send someone there from an external location. The [ExpressJS API](https://expressjs.com/en/api.html) page is a shining example of just such a setup.

**Comment by ericdrobinson** [comment]
As a side note, I've noticed that scrolling in Chrome is super speedy when the page is **first rendered**. It only slows down _dramatically_ once the Markup is loaded.

Wouldn't you know it? The Markup appears at the same instant that the URL hash updating turns on. Hopefully this is helpful in tracking down the source of the issue.

**Comment by benjamind** [comment]
There are a couple of issues at play here. @filmaj has done some work to reduce the use of the scroll hash updating until after 100ms after scrolling is complete which definitely helps a little as the update was causing a relayout through use of offsetTop. This is a good step, but I do agree with you @ericdrobinson that the hash should not update during scrolling as it pollutes the browser history.

I did some other preliminary analysis of rendering performance and it appears that most time is spent in Update Layer Tree during scroll. This step in the rendering pipeline appears to be taking a long time because the layer tree is very large with so many DOM nodes on the page. This is actually made worse once the markup loads since it involves a lot more DOM to render the styled markup.

Ultimately the docs site will probably need to be split up into sections to help alleviate this, or some kind of virtual scrolling needs to be implemented so everything can remain on the  single page, but the number of DOM nodes is reduced.

**Comment by filmaj** [comment]
Thanks @ericdrobinson ! I am just getting my feet wet with the devtools performance stuff. I appreciate all the links and tips you gave, I will do some more exploring, and with @benjamind's experience and help here, I think we can get to a solution.

**Comment by ericdrobinson** [comment]
@benjamind I disagree. I think the fix is extremely simple:

**Remove the `setURLParams` function.**

I just did this in the console while on the site:

```js
setURLParams = function () {};
```

Then I went back and began scrolling in Chrome. The performance issues **completely disappeared**. Not only that, but the back button was usable. I can still get the links to the specific sections by clicking on their headers (or right-clicking and selecting the "Copy Link Address" option).

I would _**highly**_ recommend removing the auto-hash update "feature" and replace it with a link icon  that users can use to grab a link to the header of their interest. This fixes two issues at once: usability and scrollability.

**Comment by ericdrobinson** [comment]
I just tested that change in Safari 12.0.1 and it doesn't seem to really improve things there. I suspect that something else on the page is causing the slowdown for that browser (whatever the cause, it may affect iOS browsers in a similar fashion...).

**Comment by filmaj** [comment]
Regardless of the impact on performance for setting the hash, I still like the suggestion of replacing auto-updating hash w/ anchor links - if only to stop messing with history. I will spin that out into its own issue.
