### ISSUE TITLE
Tooltip: Add inlineStart, inlineEnd, blockStart, blockEnd

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#604]
## Description

Tooltips currently support left, right, top, bottom, but we should support a way to automatically place them on the correct side if the language direction flips.

## Why do you need this feature or component?

In order to support RTL.

## Additional context

Related to #532

**Comment by GarthDB** [comment]
I feel like we might some use cases. I think doing this automatically could mess stuff up depending on how products are using it.

**Comment by pfulton** [comment]
@Westbrook - do you think this is something that y'all would need? We're trying to understand the amount of effort involved to support this.

**Comment by Westbrook** [comment]
We manage all this is JS already, so I wouldn’t worry about it for us.

**Comment by Westbrook** [comment]
We take into account things like if there actually room to display the tooltip in that direction via that JS as well.

**Comment by pfulton** [comment]
Awesome. Thank you. (cc: @Deanna-w1 to see Westbrook's comments above)
