### ISSUE TITLE
Slider handle background should be transparent

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#619]
## Description

/title

## Steps to reproduce

1. Go to http://spectrum-css-archives.s3-website.us-east-2.amazonaws.com/2.17.0/docs/slider.html
2. Look at handle
3. Imagine it's over a background other than the default background color
4. Realize it will still be the background color (and set a different background color on `spectrum-CSSExample-example` if you need a visual aide)
5. Know in your heart that this is wrong

## Expected behavior

It should be transparent

## Screenshots

![image](https://user-images.githubusercontent.com/201344/76015442-119e0a80-5ed0-11ea-8df1-4358b41a639d.png)

## Environment
 - **Spectrum CSS version:** 2.17
 - **Browser(s) and OS(s):** All

## Additional context

Discovered while testing #603

**Comment by jnurthen** [comment]
This appears to have broken high contrast mode for a bunch of components. Will file a new issue and link
