### ISSUE TITLE
Date range picker en dash spacing is wrong

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#640]
## Description

It's just a tad off, but there are no tokens to make it right.

## Screenshots

![image](https://user-images.githubusercontent.com/201344/76570122-e5573080-6471-11ea-9f3c-cc6ed6861f59.png)

## Environment
 - **Spectrum CSS version:** master
 - **Browser(s) and OS(s):** Chrome on macOS

## Additional context

Discovered while testing #615

**Comment by GarthDB** [comment]
Using `font-feature-settings: "tnum";` would improve the spacing consistency.

**Comment by pfulton** [comment]
@Deanna-w1 will tell design about this and discuss with regard to core tokenizing or something else.
