### ISSUE TITLE
[Tabs] Positioning of the selection indicator

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#641]
## Description
It's possible that this has been addressed in some of the beta releases, but I wanted to bring this up as we're addressing in manually in [Spectrum Web Components](https://github.com/adobe/spectrum-web-components/issues/537). Current screen shots show the selector on the right, but this issue applied to the "standard" position of the vertical selection indicator as well.

### Expected Behaviour
When set to taller than the `tab` elements and `justify-content: center` the indicator is positioned correctly.
<img height="200" src="https://user-images.githubusercontent.com/1156657/76568755-e98e4880-6487-11ea-9ed1-073a934d3372.png" />

### Actual Behaviour
In this case the indicator is actually positioned from the "centered" position, instead of the top.
<img height="200" src="https://user-images.githubusercontent.com/1156657/76568728-daa79600-6487-11ea-8ae6-a66f565a7777.png" />

## Proposal
Let's add `top: 0` to the `vertical` and `vertical-right` variants to correct this!

**Comment by Westbrook** [comment]
Looking at this a little closer, this might also come from the way that the current Spectrum CSS implementation relied on direct application of `top` where as Spectrum Web Components uses `translateY`...
![image](https://user-images.githubusercontent.com/1156657/76633783-a8e00f00-651b-11ea-8f69-146ff498b626.png)
`translateY` would allow for performant animation of the indicator, but might not be in the Spectrum spec at current...if the indicator should _never_ be animated, I could see moving our implementation to a specific `top` value, which would close this issue.

**Comment by GarthDB** [comment]
Is this still an issue @Westbrook ? Re-open if it is. I tried to recreate it but not sure how your example is set up.
