### ISSUE TITLE
Align build system to single docs solution

### ISSUE THREAD

**Issue by misterbrownlee** [adobe/spectrum-css#643]
We have a bit of a fork in our docs solution right now.  Given the noise that's creating, and the fact that we don't have bandwidth from either the CSS team or the published docs team to improve the shared code situation, let's temporarily utilize the testing docs as public docs and revisit shared code when we get more time.

**Comment by misterbrownlee** [comment]
Oh... I guess this is maybe a duplicate.

**Comment by GarthDB** [comment]
We moved away from sharing code with the spectrum website.
