### ISSUE TITLE
Associated JavaScript components

### ISSUE THREAD

**Issue by brucou** [adobe/spectrum-css#654]
## Description

> Adobe maintains separate JavaScript libraries written with React, Angular, and web components that use Spectrum CSS to create fully interactive Spectrum components. These libraries will be open sourced soon.

Any estimate when would that be? Looking forward (specially the web component part).

## Why do you need this feature or component?
Sleak design system that I wish to use in my open-source work

**Comment by GarthDB** [comment]
Web components are in progress, but they are available to use https://github.com/adobe/spectrum-web-components
