### ISSUE TITLE
[Textfield] "multiline" variant getting wrong height when "quiet"

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#655]
## Description
Currently the `multiline` version gets the following CSS:
```
.spectrum-Textfield--multiline {
  height: auto;
  min-height: var(--spectrum-global-dimension-size-700);
  padding: calc(var(--spectrum-textarea-padding-top, var(--spectrum-global-dimension-size-75)) - var(--spectrum-textarea-border-size, var(--spectrum-alias-border-size-thin))) calc(var(--spectrum-textarea-padding-x, var(--spectrum-global-dimension-size-150)) - var(--spectrum-textarea-border-size, var(--spectrum-alias-border-size-thin))) calc(var(--spectrum-textarea-padding-bottom, var(--spectrum-global-dimension-size-115)) - var(--spectrum-textarea-border-size, var(--spectrum-alias-border-size-thin))) calc(var(--spectrum-textarea-padding-x, var(--spectrum-global-dimension-size-150)) - var(--spectrum-textarea-border-size, var(--spectrum-alias-border-size-thin)));
  overflow: auto;
}
```
Notice the `min-height` here "resolves" to `--spectrum-global-dimension-size-700`.

However, when you add `quiet` to the element as well the following styles are applied:
```
.spectrum-Textfield--quiet.spectrum-Textfield--multiline {
    height: var(--spectrum-textfield-height, var(--spectrum-alias-single-line-height));
    min-height: var(--spectrum-textfield-height, var(--spectrum-alias-single-line-height));
}
```
Which causes the "resolved" `min-height` to be `--spectrum-alias-single-line-height` or the same as the standard (non-`multiline`) variant.

It does't look like this is happening in the public documentation site https://opensource.adobe.com/spectrum-css/components/textarea/, but these styles are direct copies from `v2.0.6`.

Separately, I can follow up next week with whether this persists in the beta releases or not, but it would be great to see a mainly release with a bug fix for this!

**Comment by Westbrook** [comment]
The same persists in the recent beta 2 release in `dist/index-vars.css`:
```
.spectrum-Textfield.spectrum-Textfield--quiet.spectrum-Textfield--multiline .spectrum-Textfield-input {
    height: var(--spectrum-textfield-height, var(--spectrum-alias-single-line-height));
    min-height: var(--spectrum-textfield-height, var(--spectrum-alias-single-line-height));
  }
```
`--spectrum-alias-single-line-height` seems incorrect here.

**Comment by GarthDB** [comment]
So this is kind of designed to act this way because we don't want a large box with only a visual bound on the bottom side.

We can double-check with Design on this. It really should just grow as you type.

**Comment by GarthDB** [comment]
Yes, this is the guidance from the Design team: https://spectrum.adobe.com/page/text-area/#Dont-use-quiet-style-for-fixed-height-text-areas
