### ISSUE TITLE
Invalid CSS for @keyframes pulse, pulse--quiet and indeterminate-loop in large scale

### ISSUE THREAD

**Issue by icaraps** [adobe/spectrum-css#656]
## Description
The large scale for barloader and coackmark includes a specific keyframe definition but the produced CSS is invalid:
```
.spectrum--large {
@keyframes pulse {
  0% {
    -webkit-transform: scale(1);
    opacity: 0;
  }
  50% {
    -webkit-transform: scale(1.5);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(2);
    opacity: 0;
  }
}
@keyframes pulse--quiet {
  0% {
    -webkit-transform: scale(0.8);
    opacity: 0;
  }
  50% {
    -webkit-transform: scale(1.5);
    opacity: 1;
  }
  100% {
    -webkit-transform: scale(2);
    opacity: 0;
  }
}

}
```

```
.spectrum--large {
@keyframes indeterminate-loop {
  100% {
    transform: translate(452px);
  }
}

}
```

## Steps to reproduce

1. `npm i @adobe/spectrum-css@2.18.0`
2. Look for `dist/spectrum-core-diff.css` or in : 
* `dist/components/barloader/index-diff.css`
* `dist/components/coachmark/index-diff.css`

## Environment
 - **Spectrum CSS version:**  2.18.0

**Comment by GarthDB** [comment]
This is only an issue in the `diff` build.

**Comment by GarthDB** [comment]
Diff build is deprecated so we won't be fixing this.
