### ISSUE TITLE
Prototype New UI Icon Sizes

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#659]
synced to jira: https://jira.corp.adobe.com/browse/SDS-7658

**Comment by jianliao** [comment]
[VR result](http://opensource.adobe.com/spectrum-css-vr-results/6b7f98a-result-2020-04-09_00-02-33/html_report/) and [Dev Site](http://opensource.adobe.com/spectrum-css-vr-results/6b7f98a-result-2020-04-09_00-02-33/dist/docs/)

**Comment by GarthDB** [comment]
Sure. Can we create issues for the misalignments?

**Comment by jianliao** [comment]
The issue contains a list of misalignment components created. See #699

**Comment by GarthDB** [comment]
We have to update to the latest DNA to really fix this.

**Comment by castastrophe** [comment]
Completed 22 Oct 2020
