### ISSUE TITLE
Steplist@3.0.0-beta1 first step doesn't render properly

### ISSUE THREAD

**Issue by filmaj** [adobe/spectrum-css#663]
## Description
When I go to copy the basic steplist example from the docs site, and tweak it so that it matches the 'initial state' of a multi-step process (i.e. step 1 is selected, no steps are complete), it renders weird (see screenshot below). Seems like step 1 is scrunched up. If I downgrade to steplist@2.0.5, the issue is gone.

## Steps to reproduce

So I cannot reproduce this on the docs site, probably because the issue doesn't exist on steplist v2. But using the 3.0 beta, definitely can reproduce it with the basic examples.

## Expected behavior
Looks the same as in v2.

## Screenshots

<img width="257" alt="Screen Shot 2020-04-03 at 11 23 45" src="https://user-images.githubusercontent.com/52645/78377433-9a769780-759d-11ea-8721-da51f4a2c865.png">

The above scrunched up first step renders like this regardless of whether the step is selected or complete.

## Environment
This is in a react app with the following package.json `dependencies`:
```
    "@spectrum-css/button": "^3.0.0-beta.1",
    "@spectrum-css/fieldlabel": "^3.0.0-beta.2",
    "@spectrum-css/page": "^2.0.6",
    "@spectrum-css/steplist": "^3.0.0-beta.1",
    "@spectrum-css/typography": "^2.1.2",
    "@spectrum-css/vars": "^2.2.0",
```

 - **Browser(s) and OS(s):** Chrome 80.0.3987.163 on mac os 10.15.4

## Additional context
I didn't look into it super deeply, but I did poke around the css (not my forté, though), and I noticed two differences right off the bat when I was comparing steplist@3 to steplist@2:

- the right padding on the first element is 0 in v3, whereas it is 40px in v2.
- the `segment` class, which I think is the dashed-or-solid line (depending on state) that connects between the steps, had its `display` set to `none` on the `first-child`. That didn't make much sense to me and seemed off.

**Comment by lazd** [comment]
Have you add `dir="ltr"` to a parent element?

**Comment by lazd** [comment]
I'm able to reproduce this if I omit the `<html dir="ltr">` attribute: 
![image](https://user-images.githubusercontent.com/201344/79156673-2780d400-7d88-11ea-9797-74916eba16a8.png)

Note that all 3.x betas require you to have the `dir` attribute, see https://github.com/adobe/spectrum-css#language-support

I'll go ahead and close this, thanks!
