### ISSUE TITLE
Erroneous selector in Textfield beta

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#668]
## Description
When using the `index-vars.css` output of Textfield beta 2 the following selectors are available:

```
.spectrum-Textfield-input [disabled]
.spectrum-Textfield-input [disabled]::placeholder
.spectrum-Textfield--quiet .spectrum-Textfield-input [disabled]
```

As the current expectation is for the `.spectrum-Textfield-input` element to be an `<input>` there is no way for there to be a child element, let alone one that could be `[disabled]` or have a `::placeholder`.

## Steps to reproduce

1. `yarn add -D @spectrum-css/textarea@3.0.0-beta.2`
2. Checkout `dist/index-vars.css`
3. See erroneous selector

## Expected behavior
Likely what you are wanting here is something like:

```
.spectrum-Textfield-input[disabled]
.spectrum-Textfield-input[disabled]::placeholder
.spectrum-Textfield--quiet .spectrum-Textfield-input[disabled]
```

However, I can't find an equivalent selector in `dist/index.css` so there may be something deeper at play here.

## Environment
 - **Spectrum CSS version:** @spectrum-css/textarea@3.0.0-beta.2
 - **Browser(s) and OS(s):** All

**Comment by GarthDB** [comment]
No longer an issue in textarea@3.0.0-beta.4
