### ISSUE TITLE
How to use workflow icons docs in README not correct

### ISSUE THREAD

**Issue by filmaj** [adobe/spectrum-css#669]
## Description
The readme section on using workflow icons says to:

1. Load the workflow icons svg
2. 'Visit the Spectrum workflow icon list and click on any icon to get the markup.'

However, when you go to the spectrum site and click on an icon to get the markup, you get the _full_ svg for each icon. Using the full svg together with loading the workflow icons SVG file up-front seems to be redundant. I would assume we should either use the full svg and NOT load the workflow-icons.svg up front, OR load the workflow-icons.svg up front and then use the icon identifiers from inside the SVG.

Example of the icon markup you get from the spectrum site (for the "123" icon):

```
<svg xmlns="http://www.w3.org/2000/svg" height="18" viewBox="0 0 18 18" width="18">
  <defs>
    <style>
      .a {
        fill: #6E6E6E;
      }
    </style>
  </defs>
  <title>S 123 18 N</title>
  <rect id="Canvas" fill="#ff13dc" opacity="0" width="18" height="18" /><path class="a" d="M13.7585,8.564c-.061,0-.085-.0245-.085-.0855V7.2705c0-.073,0-.122.073-.122l.6085-.0055c.8545,0,1.318-.256,1.318-.8175,0-.537-.45-.891-1.3425-.891a3.75651,3.75651,0,0,0-1.806.464c-.073.0365-.085,0-.085-.05V4.6415c0-.0735-.0125-.1.061-.1345a4.51,4.51,0,0,1,2.123-.4755c1.611,0,2.6115.805,2.6115,2.0745a1.72949,1.72949,0,0,1-1.074,1.6,1.9385,1.9385,0,0,1,1.45,1.9035c0,1.5625-1.44,2.392-3.124,2.392a4.4,4.4,0,0,1-2.087-.403c-.073-.024-.073-.097-.073-.158v-1.32c0-.05.061-.073.11-.05a4.168,4.168,0,0,0,1.989.5125c1.1,0,1.5255-.45,1.5255-1.025,0-.647-.464-1-1.477-1Z" />
  <path class="a" d="M2.308,5.635a10.3485,10.3485,0,0,1-1.291.335c-.0835.012-.1075-.012-.1075-.084V4.845c0-.0595.012-.0955.0835-.1075a7.68542,7.68542,0,0,0,1.546-.61.44193.44193,0,0,1,.2035-.06H3.919c.06,0,.072.036.072.0835l-.003,6.4065h1.07c.0835,0,.1075.036.1195.108l.003,1.203c.012.0955-.024.1315-.0955.1315H1.1635c-.0835,0-.1075-.036-.0955-.1075l-.003-1.227a.1145.1145,0,0,1,.11959-.10917l.01191.00117h1.109Z" />
  <path class="a" d="M6.007,12c-.084,0-.096-.036-.096-.1075V11.031a.17.17,0,0,1,.06-.1555A29.47021,29.47021,0,0,0,8.221,8.853c.945-.921,1.3565-1.5165,1.3565-2.1865,0-.7535-.615-1.195-1.524-1.195A4.29648,4.29648,0,0,0,6.1265,6c-.072.036-.1195.012-.1195-.0715V4.742a.1355.1355,0,0,1,.0715-.1435A4.554,4.554,0,0,1,8.45,4a2.40306,2.40306,0,0,1,2.666,2.3855,3.52612,3.52612,0,0,1-1.236,2.73A18.52381,18.52381,0,0,1,8.36,10.58c.826,0,2.5265-.0225,3.2325-.0225.084,0,.0955.024.084.108l-.357,1.239a.119.119,0,0,1-.132.0955Z" />
</svg>
```

I can, instead, use the icon ID to get the right icon (based on searching through `spectrum-workflow-icons.svg`), like so:

```
<svg className="spectrum-Icon" focusable="false" aria-hidden="true">
  <use xlinkHref="#spectrum-icon-18-123" />
</svg>
``` 

Though I need to manually size the svg myself (otherwise it renders at a large size, like 300px width).

## Link to documentation

https://github.com/adobe/spectrum-css#importing-workflow-icons

**Comment by GarthDB** [comment]
We should update the docs and also add the Icons page back to the Spectrum CSS documentation site. Probably related to #435

**Comment by GarthDB** [comment]
Documentation has been updated https://github.com/adobe/spectrum-css#importing-ui-icons
