### ISSUE TITLE
Toast doc is missing the warning variant

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#67]
https://github.com/adobe/spectrum-css/blob/master/docs/toast/toast.yml
Does not have "warning" although it's available in the CSS:
https://github.com/adobe/spectrum-css/blob/master/src/toast/skin.css#L22

**Comment by lazd** [comment]
The warning variant is deprecated for Toast, so it should indeed be in the documentation with a tag indicating that it's deprecated. Thanks!

**Comment by Harbs** [comment]
Curious as to why it's deprecated.

**Comment by lazd** [comment]
@Harbs it was dropped from the design system and replaced with `negative`. @NateBaldwinDesign can elaborate.

**Comment by NateBaldwinDesign** [comment]
Many of the use cases we saw that were using the warning variant we felt could be replaced with either the `negative` or `informative` semantic, and we also had design and contrast issues with white text on orange.
