### ISSUE TITLE
Illustrated Message Text Color

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#676]
## Description
Currently, there are no text colors in the style for Illustrated Message and it relies on the presence of `.spectrum-Typography` in order for the text there in to be styled correctly:

```
.spectrum-IllustratedMessage {
  height: 100%;

  display: -ms-flexbox;

  display: flex;
  -ms-flex-direction: column;
      flex-direction: column;
  -ms-flex-align: center;
      align-items: center;
  -ms-flex-pack: center;
      justify-content: center;

  text-align: center;
}

.spectrum-IllustratedMessage-illustration {
  margin-bottom: 24px;
}

.spectrum-IllustratedMessage-heading {
  max-width: 500px;
  margin: 0;
}

.spectrum-IllustratedMessage-description {
  max-width: 500px;
  margin: 4px 0 0 0;

  font-style: italic;
}

.spectrum-IllustratedMessage--cta .spectrum-IllustratedMessage-description {
    font-style: normal;
  }

.spectrum-IllustratedMessage-illustration {
  color: var(--spectrum-global-color-gray-500);
  fill: currentColor;
  stroke: currentColor;
}

```

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/components/illustratedmessage/
2. Inspect the "Error 404: Page Not Found" content in the first example.
3. Notice that its styled via:
    ```
    .spectrum--light .spectrum-Heading--pageTitle { ... }
    ```
    instead of something specific to `.spectrum-IllustratedMessage-heading`

## Expected behavior
Content in an Illustrated Message component could be delivered without external influence.

**Comment by GarthDB** [comment]
This is still an issue and probably is widespread in other components.
