### ISSUE TITLE
Update Tag component

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#693]
## Description
spacing, icon option, image tags style, colors for selected tags

The design can be found on the [contributions](https://spectrum-contributions.corp.adobe.com/page/tag-beta/).

**Comment by Westbrook** [comment]
FYI Shantanu is looking a little out of place in the most recent release of this: https://opensource.adobe.com/spectrum-css/tag.html

I'd expect maybe that the Avatar therein expects some version of `spectrum-Avatar--size50` to display correctly?
