### ISSUE TITLE
Add updated sizing to Avatar

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#697]
## Description
Sizing and designs can be found [here](https://spectrum-contributions.corp.adobe.com/page/avatar-beta/#Size).

**Comment by Westbrook** [comment]
Now that this sizing is "officially" in Spectrum, where does this fall as far as priority for implementing at the Spectrum CSS level?

**Comment by lazd** [comment]
Looks like a dupe of #368

**Comment by lazd** [comment]
Looking at DNA, we have different sizes for Avatar, but they're numerical, not t-shirt sized... That's weird AF.

@NateBaldwinDesign not sure if we discussed this already, but are Avatars going to stay with numerical sizing, or are we going to use S/M/L etc.

**Comment by pfulton** [comment]
We'll take a new look at this one during our migration to core tokens.
