### ISSUE TITLE
Documentation site takes 10-15 seconds to load

### ISSUE THREAD

**Issue by aaronshekey** [adobe/spectrum-css#7]
### Expected Behavior
Loading the documentation site should be instant.

### Actual Behavior
When loading the documentation site, it takes a good 10-15 seconds on the latest macOS Mojave and Safari via Gigabit internet.

#### Steps to Reproduce
Load normally http://opensource.adobe.com/spectrum-css/

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
MacOS 10.14.1
Safari 12.0.1

![screen shot 2018-11-16 at 3 16 38 pm](https://user-images.githubusercontent.com/1369864/48647775-a36bc680-e9b2-11e8-8b5d-454f9630ef81.png)

**Comment by GarthDB** [comment]
Yeah, the biggest culprit is typekit. We are loading in all the languages for the typography examples and are looking into splitting it out into a separate page to handle the load time a better.

**Comment by lazd** [comment]
The docs are loading much faster after moving syntax highlight to a build-time task, but we'll leave this issue open until we have it much, much faster.

Try the 2.7.0 docs: http://opensource.adobe.com/spectrum-css/2.7.0/docs/

**Comment by aaronshekey** [comment]
Are we testing Safari? I'm viewing this on Safari 12.0.1 on macOS 10.4.1 and the `2.7.0` and I'm not observing any performance gains and now beachballs in the process 😕. I'm not actually able to measure anything using dev tools since the browser freezes. 🤔

**Comment by GarthDB** [comment]
Checking it in Safari, it does load, but it's quite slow (it does show the beachball for a bit). It seems to hang on redirect a bit. I'm not sure what's going on there, but it does load... eventually 🤦‍♂️ 

![image](https://user-images.githubusercontent.com/125516/49594167-8895cd80-f932-11e8-8f6f-49d2542e1830.png)

**Comment by GarthDB** [comment]
It takes 17s to redirect, load, and render the page in safari (that's not the first load, so that would be with some caching help)
![spectrum-css](https://user-images.githubusercontent.com/125516/49594696-b0d1fc00-f933-11e8-9435-680636d851d3.gif)

**Comment by lazd** [comment]
Fixed with the 2.14 docs site https://opensource.adobe.com/spectrum-css/2.14.0/docs/
