### ISSUE TITLE
Dropdown/picker field border color too light

### ISSUE THREAD

**Issue by pudjeeb** [adobe/spectrum-css#700]
## Description
Field border color is outdated (one gray too light). This was recently updated in DNA (Spectrum-DNA v5.24.0).

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Click on Dropdown component
3. Observe border color for standard (not quiet) dropdown.

## Expected behavior
Border color should be one gray up (gray-300 on default, gray-400 on hover and down)

## Environment
 - **Spectrum CSS version:** @spectrum-css/dropdown@2.0.0
 - **Browser(s) and OS(s):** Chrome 81.0.4044.122 on macOS 10.15.4

## Additional context
Noticed while verifying Picker (aka dropdown) for React V3

**Comment by pfulton** [comment]
Will be addressed during core tokens migration.
