### ISSUE TITLE
Break out IE 11 and Safari 10 hacks into separate files

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#705]
## Description

Move hacks into separate files, i.e. `compat-safari10.css` and `compat-ie11.css`. We *will not maintain these hacks* or add new hacks, it will be up to the community to contribute them if they need them.

## Why do you need this feature or component?

Right now, these hacks are present in the codebase, but are not required. They're also causing issues with implementing new designs (i.e. the `.spectrum-Button-label  { width 100% }` hack for Safari 10 makes it impossible to implement justified button group correctly without overriding it).

## How

1. Separate files within components

* `components/button/index.css` - Does not contain any hacks for IE 11 or Safari 10
* `components/button/compat-safari10.css` - Contains Button hacks for Safari 10

2. Separate compat components per component

* `components/button-compat/index-safari10.css` - Contains Button hacks for Safari 10
* `components/button-compat/index-ie11.css` - Contains Button hacks for IE 11

3. Single compat component per browser

* `components/compat-safari10/index.css` - Contains all hacks for Safari 10 for all components
* `components/compat-ie11/index.css` - Contains all hacks for IE 11 for all components

**Comment by lazd** [comment]
@GarthDB @jianliao @bernhard-adobe please weigh in on the above options. I am leaning towards #1 since it does not require maintaining/releasing separate components.

**Comment by misterbrownlee** [comment]
Single compat component would be my vote. I am, however, clearly not qualified to have a vote.

**Comment by jianliao** [comment]
I tend to choose option 3.
1. It will only add two new components(for now).
2. Centralizing all the hacks into a single place makes it possible to do the individual release.

**Comment by lazd** [comment]
@jianliao Note that option 1 adds 0 new components

Can you elaborate on your second point? The thing is, if we have separate components for the compat hacks, they will have to have dependencies on the components that they're hacking, otherwise implementation details may change between versions and break the hacks. So you'll have to manage the component version vs. the compat version...

Option 1 keeps the compat hacks coupled to the version of the component you're using and requires no new dependencies, so it's definitely the easiest route for consumers. Thoughts?

**Comment by jianliao** [comment]
Ah, right... I didn't realize that with the change of component, the hack also needs to evolve. I am onboarding with option 1. Thanks for the explanation.

**Comment by bernhard-adobe** [comment]
Why not just delete those hacks if we don't maintain IE 11 anymore?

**Comment by snowystinger** [comment]
given that these things are preventing new functionality, how does it help to move them out? more specifically, would these have higher specificity than the base so that they are always applied? will that cause more breaking because we've tried to put in new incompatible functionality that we know conflicts?

would teams be expected to only ship these to those respective browsers?

what does someone using react spectrum do to get these?

what about v3 where we have css modules that obscure the names?
