### ISSUE TITLE
Card: role=figure and tabindex=0 seem incorrect

### ISSUE THREAD

**Issue by jnurthen** [adobe/spectrum-css#706]
https://github.com/adobe/spectrum-css/blob/b617d0ed344e37add42ccbe317cd3dd3f698cb08/components/card/metadata/card-asset.yml#L8

both role=figure and tabindex=0 don't seem correct on a card. 

- I'd suggest group would be better than figure (as we have no idea what it may contain and figure implies certain types of content and the fact that it is referenced from the main text).
- Structural roles such as group (or figure) are not widgets so should not take focus so suggest removing tabindex=0
- Whatever structural role is chose it would be an improvement to label it using the card title.

**Comment by pfulton** [comment]
@jnurthen I realize this one is a bit old. Would you mind letting us know if it's still relevant?
