### ISSUE TITLE
Hover state present over item when user is not hovering on specific menu item [Major]

### ISSUE THREAD

**Issue by leuenbern** [adobe/spectrum-css#709]
## Description
Dropdown menu with multiple sub-menus maintains hover state for multiple items, despite the mouse not being over either.

## Steps to reproduce

There are no multi-submenu items on http://opensource.adobe.com/spectrum-css/, but the issue is still observable 

1. Go to https://opensource.adobe.com/spectrum-css/components/menu/#Nested
1. Observe "Feather" has the hover state
1. Mouse over other menu items
1. Observe that other menu items have the hover state AND "Feather" maintains its hover state.

**In App:**  https://jira.corp.adobe.com/browse/IAW-8078
Hs 2.12.0.3, Indesign 15.3
Open NUJ checklist dropdown and navigate over 1 of the items>notice the hover state
Navigate down the list to the next item and notice the hover state remains on the first item as well as being present on second item
expected: Hover state should only be on currently hovered menu item

## Expected behavior
Hover state should only be on currently hovered menu item

## Screenshots
![image](https://user-images.githubusercontent.com/52009653/80539938-39a06c00-895d-11ea-9874-b72e460117c1.png)
<img width="1680" alt="Screen Shot 2020-04-07 at 11 36 08 AM" src="https://user-images.githubusercontent.com/52009653/80539951-4329d400-895d-11ea-9c9e-23dcffd737f5.png">
<img width="1680" alt="Screen Shot 2020-04-07 at 11 36 13 AM" src="https://user-images.githubusercontent.com/52009653/80539953-43c26a80-895d-11ea-8389-3b43ebd76869.png">

## Environment
 - **Spectrum CSS version:** 2.30.0
 - **Browser(s) and OS(s):** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36 _on_ MacOS 10.15, Win 10

## Additional context
A similar issue occurred within React-Spectrum UXP and was fixed. That was tracked here: https://jira.corp.adobe.com/browse/IAW-7813 / https://jira.corp.adobe.com/browse/UXP-12541

**Comment by GarthDB** [comment]
@leuenbern feather doesn't have a hover state, it has `is-open` applied to it. A javascript implementation would need to manage the opening and closing of the sub menu and the state of the opened item. The larger issue is that the `is-open` state is the same as the `:hover`, and `:active` states in appearance so you can't easily distinguish them.

**Comment by GarthDB** [comment]
@leuenbern from the design guidelines file for [Side navigation](https://spectrum.adobe.com/page/side-navigation/):
![image](https://user-images.githubusercontent.com/125516/80543523-47a9b900-896c-11ea-8340-1eafbd823f73.png)

**Comment by GarthDB** [comment]
@leuenbern we aren't going to fix this as it is currently because it is inline with the current design, but Design is going to look at it and we will update the component with an updated design.

**Comment by leuenbern** [comment]
@GarthDB Thanks for taking a look at it. At some point, the particular error we were seeing in our code got fixed as a side-effect of other fixes we were doing. I'll keep an eye out for updated designs, regardless.
