### ISSUE TITLE
Different loading orders cause problems

### ISSUE THREAD

**Issue by ClassicOldSong** [adobe/spectrum-css#712]
## Description

When using `@adobe/spectrum-css` in my component library based on spectrum-css using postcss and postcss import I discovered that different import order of components could cause different results which should be considered as a bug. Since import order of components could not be controlled, this is very likely to become a problem for users.
## Steps to reproduce

Read below.

## Expected behavior
[This one is fine](https://codesandbox.io/s/spectrum-css-import-order-correct-obhk3?file=/index.html)

[This one is not](https://codesandbox.io/s/spectrum-css-import-order-incorrect-lp33i?file=/index.html)

## Screenshots

![image](https://user-images.githubusercontent.com/10512422/80736310-86926700-8b44-11ea-9c12-7c436e8b3bca.png)

## Environment
 - **Spectrum CSS version:** 2.18.0
 - **Browser(s) and OS(s):** All modern browsers on modern OS

## Additional context
Usage example:

component_textfield:
```css
@import "@adobe/spectrum-css/dist/components/textfield/index-vars.css";
```

component_stepper:
```css
@import "@adobe/spectrum-css/dist/components/icon/index-vars.css";
@import "@adobe/spectrum-css/dist/components/textfield/index-vars.css";
@import "@adobe/spectrum-css/dist/components/button/index-vars.css";
@import "@adobe/spectrum-css/dist/components/stepper/index-vars.css";
```

user:
```js
import Stepper from './component_stepper'
import TextField from './component_textfield'
```

Then stepper could display wrongly.

Stepper is just for demonstration. Other components could suffer from the same issue like decorated textfield.

**Comment by lazd** [comment]
Generally, Spectrum CSS is consumed directly by libraries such as [Spectrum Web Components](https://opensource.adobe.com/spectrum-web-components/) that have their own dependency tree -- i.e. a Stepper depends on Button and Textfield, and as such, loads them first. When not using a library, it's on you to follow the correct import order, [as documented here](https://github.com/adobe/spectrum-css/blob/master/README-legacy.md#import-order-and-components)

**Comment by ClassicOldSong** [comment]
Yeah and I am writing a library for my own frontend framework. It is a problem that not all css preprocessors could handle import orders correctly just as I mentioned above.

Thus, this problem could be solved easily by adding `!important` to dependent styles, which should not break anything existing.
