### ISSUE TITLE
Inconsistent icon sizing

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#726]
## Description
Spectrum Web Components noticed inconsistencies between our icon sizing and the DL icon sizes.

The DL site doesn't have the sizes documented, but standard sizes are used in avatar and status.

We are using calc to set certain sizes. We should switch to just what DNA defines. https://github.com/adobe/spectrum-css/blob/master/components/icon/workflow-icons.css#L13

synced to jira: https://jira.corp.adobe.com/browse/SDS-7661

**Comment by adixon-adobe** [comment]
If you're doing this you might consider deprecating the current sizes and just having the interface be css variables like this: #753

**Comment by adixon-adobe** [comment]
Here's a quick example of what I'm thinking of (just making up dimension size names here).

```
.spectrum {
  --spectrum-icon-default-size: var(--spectrum-global-dimension-size-150);
}

.spectrum-Button {
  --spectrum-icon-default-size: var(--spectrum-global-dimension-size-225);
}

.spectrum-Icon {
  size: var(--spectrum-icon-default-size);
}

.spectrum-Icon.spectrum-Icon--sizeL {
  size: var(--spectrum-global-dimension-size-300);
}
```

**Comment by Westbrook** [comment]
I really like the capabilities of a technique like https://css-tricks.com/using-custom-property-stacks-to-tame-the-cascade/ that could be leveraged in conjunction with the above like the following:

```
.spectrum-Icon {
    width: var(--spectrum-icon-width-user, var(--spectrum-icon-width-parent, var(--spectrum-icon-width-size, var(--spectrum-global-dimension-size-150))));
}

.spectrum-Icon--sizeM {
  --spectrum-icon-width-size: var(--spectrum-global-dimension-size-300);
}

.spectrum-Button.spectrum-Button--sizeL {
  --spectrum-icon-width-parent: var(--spectrum-global-dimension-size-400);
}

.user-override {
  /* Users like big icons, and they cannot lie... */
  --spectrum-icon-width-user: 1000px;
}
```

**Comment by lazd** [comment]
Yeah that makes a ton of sense. We should definitely support that, otherwise there's no way we can use custom icon sizes across the shadow DOM.
