### ISSUE TITLE
Toast Close Button Style Contrast

### ISSUE THREAD

**Issue by ktabors** [adobe/spectrum-css#730]
## Description
The close button when focused in a toast used to have a white background. It now has a light background. 

## Steps to reproduce
1. Go to http://localhost:3000/docs/toast.html
2. Tab to the close button of the toast.
3. Observe visual indication of selection.

## Expected behavior
Improve visual indication of focus ring of the toast close button.
Toast close button should have a focus ring and/or have a focused style with better contrast.

## Screenshots
![image](https://user-images.githubusercontent.com/309540/82266357-53aaea00-991e-11ea-9d7b-0f96500d31d7.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by NateBaldwinDesign** [comment]
@lazd the clear button should be given a focus ring in the same way that the Quiet Over Background Button does:
![image](https://user-images.githubusercontent.com/13972198/82353307-7be92600-99bc-11ea-9666-34975a976ad9.png)

**Comment by lazd** [comment]
Thanks, @NateBaldwinDesign! That makes sense. Not sure why it went away, but it's an easy fix.
