### ISSUE TITLE
Focus Ring on Split Button and Pagination

### ISSUE THREAD

**Issue by ktabors** [adobe/spectrum-css#731]
## Description
The focus ring for split buttons and pagination do not match the shape of the buttons. The focus ring is oval/round which isn't the shape of these buttons.

## Steps to reproduce
1. Go to http://localhost:3000/docs/pagination-button-style.html
OR
Go to http://localhost:3000/docs/splitbutton.html
2. Tab to any of the buttons and the focus ring is round around the button, but the buttons aren't round and are next to each other.
3. Observe visual indication of focus ring.

## Expected behavior
Improve the focus ring for split button and pagination.

## Screenshots
![image](https://user-images.githubusercontent.com/309540/82266688-33c7f600-991f-11ea-8a8f-db393e2676da.png)
![image](https://user-images.githubusercontent.com/309540/82266695-3b879a80-991f-11ea-9d7e-7e8b24ae0218.png)
![image](https://user-images.githubusercontent.com/309540/82266715-4d693d80-991f-11ea-813d-34199b11f856.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by lazd** [comment]
@badimon @pudjeeb @NateBaldwinDesign what should this look like?

**Comment by NateBaldwinDesign** [comment]
The edge that is affixed to the other button should be more squared -- probably a 2-4px border-radius

**Comment by lazd** [comment]
Ok, I'll mock that up and we can take a look. With the CTA split button, it's going to look rather funny with part of the ring overlapping the adjacent button, but we can peep it.

**Comment by lazd** [comment]
With `--spectrum-alias-border-radius-small`

## CTA

![image](https://user-images.githubusercontent.com/201344/82361457-b7392400-99bf-11ea-9f3e-087bf88857aa.png)
![image](https://user-images.githubusercontent.com/201344/82361556-db950080-99bf-11ea-91ab-32c53e250b5c.png)

## Primary

![image](https://user-images.githubusercontent.com/201344/82361566-df288780-99bf-11ea-800f-99a470acba81.png)
![image](https://user-images.githubusercontent.com/201344/82361582-e2bc0e80-99bf-11ea-884b-407b536b11d5.png)

Not gonna lie, that looks kinda weird...
