### ISSUE TITLE
Use icon with HTML element created with JavaScript

### ISSUE THREAD

**Issue by clavierCreatif** [adobe/spectrum-css#739]
Hello everyone,

## Description
I use Spectrum CSS and I have a problem, I can use icons with HTML element created with Javascript.
I share with you a screenshot : in HTML :  I use a actionButton with edit icon, icon will be display,in JS : I create a HTML button element, I add svg and use element but icon isn't displayed... (see capture2)Can you help me, how to use loadIcon function and use icon with HTML elements created with JavaScript.

## Screenshots
Button created in HTML file and one other with Javascript
![Capture](https://user-images.githubusercontent.com/20588938/82840172-f2f94f80-9ed1-11ea-817c-93fdbf68054d.JPG)

Icon isn't displayed (HTML : left, JS : right)
![Capture2](https://user-images.githubusercontent.com/20588938/82840174-f42a7c80-9ed1-11ea-89a3-b7d321fe73e4.JPG)

## Environment
Last version of Spectrum
Chrome and Brackets

**Comment by misterbrownlee** [comment]
Hi, @clavierCreatif ... sorry for missing this question!  We will look into your examples and get back to you.

**Comment by Beyarz** [comment]
> Hi, @clavierCreatif ... sorry for missing this question! We will look into your examples and get back to you.

How did it go?

**Comment by Westbrook** [comment]
You need to use the `createElementNS` API to ensure your `sVG` element is actually an SVG:  https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS

**Comment by mscherotter** [comment]
@clavierCreatif  - can you please share your code for loadIcons()?

**Comment by pfulton** [comment]
We'll reopen this if it's still an issue.
