### ISSUE TITLE
3.0 Component Structure

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#743]
## Description
I've been reviewing some of the beta releases for v3.0 in the context of Spectrum Web Components and have noticed what looks like a sharper turn towards BEM structure in the package delivery. This allows components like `Stepper` to reach into `Textfield` via selectors like `.spectrum-Stepper-input` which is applied to the `.spectrum-Textfield-input` element, however in a shadow DOM context would be obscured from the `.spectrum-Stepper` root. 

Would it be possible to export an altered or enhanced version of the `dist/index-vars.css` export, which currently surfaces a Custom Property API for local customization, to leverage that same API down into the child patterns as well?

## Why do you need this feature or component?
This would make placing Shadow DOM barriers, the browser native style encapsulation API, between patterns a more natural extension of the styles featured in the component packages published by this project.

## Additional context
In this way styles in `Stepper` that look like this:
```
[dir=ltr] .spectrum-Stepper-input {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
```
Would be rendered closer to:
```
[dir=ltr] .spectrum-Stepper {
    --spectrum-textfield-border-radius: var(--spectrum-alias-border-radius-regular) 0 0 var(--spectrum-alias-border-radius-regular);
}
```
Possibly with `Stepper` centric tokens exposed to customization from above:
```
[dir=ltr] .spectrum-Stepper {
    --spectrum-textfield-border-radius:
        var(--spectrum-stepper-border-radius, var(--spectrum-alias-border-radius-regular))
        0 0
        var(--spectrum-stepper-border-radius, var(--spectrum-alias-border-radius-regular));
}
```

**Comment by Westbrook** [comment]
In a similar way the Action Group pattern leverages the following CSS:
```
[dir="rtl"] .spectrum-ActionGroup--compact:not(.spectrum-ActionGroup--quiet).spectrum-ActionGroup--vertical .spectrum-ActionGroup-item:last-child {
          border-bottom-left-radius: var(--spectrum-actionbutton-border-radius, var(--spectrum-alias-border-radius-regular));
}
```
It would be great to see this achieved with something like:
```
[dir="rtl"] .spectrum-ActionGroup--compact:not(.spectrum-ActionGroup--quiet).spectrum-ActionGroup--vertical .spectrum-ActionGroup-item:last-child {
    --spectrum-actionbutton-border-radius: 0 0
        var(--spectrum-alias-border-radius-regular)
        var(--spectrum-alias-border-radius-regular);
}
```

**Comment by lazd** [comment]
This makes sense. Unless these properties are driven by component-specific variables, you can modify them across the shadow boundary. This would require a bit of a rework of the CSS, but I have an experiment in progress that makes this very simple to do. I'll share as soon as I get it into a decent place.

**Comment by Westbrook** [comment]
@lazd this has come up again in regards to the Combobox (`.spectrum-InputGroup`) pattern as part of https://github.com/adobe/spectrum-web-components/issues/1332 Do you have any update?

Here, the `.spectrum-InputGroup-input` selector expects access to the `.spectrum-Textfield-input` inside of the `.spectrum-Textfield`, similar to what we saw in the Number Field (previously Stepper). At first bite, the border radius alterations have an accessor in the `--spectrum-textfield-border-radius` Custom Property which can be expanded to support customization of all four corners of the element, however the `border-width` is currently applied via the `border` property, which does not expand in this way. `width: auto` and `flex: 1` are also applied in a way that I'm not 100% sure does anything since the update to have the `.spectrum-Textfield` live on a `div` wrapping the `input` element, as opposed to the previous pattern of applying that class directly to the `input`.

**Comment by snowystinger** [comment]
There are actually some other issues in selectors shared across files, it doesn't work with CSS modules for one, it also makes it very easy to have specificity collisions, leading to bugs depending on the order that the files are loaded.
We ran into this while working with InputGroup specifically.
