### ISSUE TITLE
Textfield Icon Cursor Issue

### ISSUE THREAD

**Issue by ktabors** [adobe/spectrum-css#745]
## Description
"Input jumping with padding"
MacOS - Chrome
Use a desktop browser. Goto a textfield with an icon like invalid,. Enter a long string that is bigger then the input's viewable region. Move the cursor to the start of the input's value. Click between the icon and the edge of the input, you won't see a cursor. Press the arrow key and the string will jump to show the cursor in the viewable portion of the input. This appears to be a known padding issue.

iOS - Safari
Go into a textfield with an icon like invalid. Create a long string. Exit the textfield. Press between the icon and the edge of the input, the cursor is placed there.

## Steps to reproduce

On a desktop browser like chrome or on a mobile device like ios safari
1. Go to http://opensource.adobe.com/spectrum-css/
2. Go to the textfield story https://opensource.adobe.com/spectrum-css/components/textfield/
3. Create a long string in a textfield with the invalid icon.
4. Click press between the icon and input edge.

## Expected behavior
The cursor to only be placed within the viewable portion of the input string. A solution that doesn't rely on padding since that seems to be the issue?

## Screenshots
![textfield cursor](https://user-images.githubusercontent.com/309540/83314834-2e956180-a1d1-11ea-844a-bf9888eab894.png)

Zip file with a video of the behavior on chrome. [cursor.zip](https://github.com/adobe/spectrum-css/files/4704832/cursor.zip)

## Environment
 - **Spectrum CSS version:** 2.18.0 (I think) @spectrum-css/textfield@2.0.0
 - **Browser(s) and OS(s):** Chrome 83.0.4103.61 (Official Build) (64-bit) on OS X 10.12.6 and iOS 13.4.1

**Comment by GarthDB** [comment]
I agree, if we use a non-padding solution we might be able to fix this, but it might be a browser bug because the input should behave differently with padding... maybe?
