### ISSUE TITLE
Animating box-shadow is incredibly performance heavy

### ISSUE THREAD

**Issue by snowystinger** [adobe/spectrum-css#746]
## Description

When running many focus animations they become choppy. This is an issue in TableView and other large collections where scrolling quickly is a necessity

## Steps to reproduce

Going to need to wait on that from react spectrum until we publish

## Expected behavior

Animations shouldn't get in the way of our components scrolling or other critical functions

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** 

## Additional context

This can be solved in a number of ways, but one simple one is to animate the opacity instead
```
& + .spectrum-Checkbox-box {
    &:after {
      box-shadow: 0 0 0 var(--spectrum-checkbox-focus-ring-size-key-focus) var(--spectrum-checkbox-focus-ring-color-key-focus);
      opacity: 0;
    }
}
&:focus-ring + .spectrum-Checkbox-box {
    &:after {
      opacity: 1;
    }
  }
```

**Comment by GarthDB** [comment]
Looks like it was fixed in https://github.com/adobe/spectrum-css/pull/754
