### ISSUE TITLE
Stop the artifactory dependencies

### ISSUE THREAD

**Issue by snowystinger** [adobe/spectrum-css#748]
## Description

Any chance we can eliminate the artifactory dependencies so I can delete all of that from my npmrc? :)

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Click on ...
3. Observe ...

## Expected behavior

Not to get these messages 
```
error https://artifactory.corp.adobe.com:443/artifactory/api/npm/npm-a4u-release/@a4u/a4u-collection-react-spectrum-open-source-color-icons-release/-/@a4u/a4u-collection-react-spectrum-open-source-color-icons-release-2.0.0.tgz: unable to get local issuer certificate
error https://artifactory.corp.adobe.com:443/artifactory/api/npm/npm-a4u-release/@a4u/a4u-collection-react-spectrum-open-source-release/-/@a4u/a4u-collection-react-spectrum-open-source-release-3.1.0.tgz: unable to get local issuer certificate
error https://artifactory.corp.adobe.com:443/artifactory/api/npm/npm-a4u-release/@a4u/a4u-collection-spectrum-css-release/-/@a4u/a4u-collection-spectrum-css-release-2.5.0.tgz: unable to get local issuer certificate
```

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):** 

## Additional context

synced to jira: https://jira.corp.adobe.com/browse/SDS-7587

**Comment by lazd** [comment]
I think #366 fixes this, @jianliao ?

**Comment by jianliao** [comment]
#662 should fix this issue.

**Comment by misterbrownlee** [comment]
This is blocked by #662

**Comment by lazd** [comment]
Hey @GarthDB @jianliao @misterbrownlee, this issue is in the sprint but is unassigned. Can someone take this on? It blocks continuous deployment.

cc @macdonst

**Comment by jianliao** [comment]
#1007 should get rid of the last dependency for artifactory.
