### ISSUE TITLE
Circle Loader distorts on Win10 Mozilla, macOS Firefox 62.0.2.

### ISSUE THREAD

**Issue by xitter** [adobe/spectrum-css#75]
### Expected Behavior
Circle loader should spin smoothly as it does in Chrome.

### Actual Behavior
Circle loader is distorted on Mozilla.

### Steps to Reproduce
Open circle loader.

### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
Mozilla, Windows 10

**Comment by GarthDB** [comment]
@xitter Any chance you could attach a screenshot? or a short screencast?

**Comment by hkhetan** [comment]
This seems to be happening in Safari and CEF (Windows) too. Here are the screenshots:
Safari:
![Screenshot 2020-02-22 at 6 35 37 PM](https://user-images.githubusercontent.com/52647992/74838030-c7058580-5348-11ea-80d6-c56d979e6323.png)
CEF (Windows):
<img width="960" alt="broken spinner" src="https://user-images.githubusercontent.com/52647992/74838073-e6041780-5348-11ea-9def-fc758564a2d5.png">

**Comment by misterbrownlee** [comment]
We aren't testing in CEF.  If this is still happening, please circle back with us and we can work together to find a way to add CEF as a priority.
