### ISSUE TITLE
icon should allow resizing with a css variable

### ISSUE THREAD

**Issue by adixon-adobe** [adobe/spectrum-css#753]
## Description
By default icon should have it's width/height using an overridable css variable. I think ideally the size would default to the equivalent of the small size now. So 18x18 in medium scale and 22x22 in large.

## Why do you need this feature or component?
Using a variable will allow overriding for t-shirt size components that use icons. E.g. a "large" action button can adjust the expected size of icons in the control using the variable, rather than relying on clients to provide the correct sized icon.

## Additional context
This is related to #726 and https://github.com/adobe/spectrum-web-components/issues/669

**Comment by pfulton** [comment]
This should be addressed in our core tokens migration.
