### ISSUE TITLE
Safari 10: Spectrum Button with few characters is misaligned

### ISSUE THREAD

**Issue by amarcus-adobe** [adobe/spectrum-css#76]
The Spectrum `Button` renders its contained span text off-center (to the left) when the text is shorter than the button's `min-width` attribute.

### Expected Behavior
Button text will be center-aligned regardless of the content length.
![image](https://user-images.githubusercontent.com/46543158/51568174-f6984480-1e4d-11e9-9a4e-12658d7a6cf3.png)

### Actual Behavior
Button text is left-aligned when the text is short.
![image](https://user-images.githubusercontent.com/46543158/51569222-9eaf0d00-1e50-11e9-9294-c0920870ad63.png)

### Reproduce Scenario (including but not limited to)
Viewing a [Spectrum button](http://opensource.adobe.com/spectrum-css/2.7.2/docs/#button---cta) in Safari 10.0, available in MacOS 10.12.

#### Steps to Reproduce
1. Log into a MacOS 10.12 machine with Safari 10.0
2. Open Safari 10.0 to http://opensource.adobe.com/spectrum-css/2.7.2/docs/#button---cta
3. Using the "Inspect Element" and/or Developer Panel, alter the button's contained span to display a short string, such as "Test"
4. View the button text rendering

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
Safari 10.0 on MacOS 10.12

#### Spectrum-CSS version
spectrum-css 2.7.2

#### Sample Code that illustrates the problem
From the modified example at http://opensource.adobe.com/spectrum-css/2.7.2/docs/#button---cta:
```
<button class="spectrum-Button spectrum-Button--cta">
  <span class="spectrum-Button-label">Test</span>
</button>
```

#### Screenshots (if applicable)
See above.

**Comment by lazd** [comment]
Looks like this is due to https://bugs.webkit.org/show_bug.cgi?id=169700
