### ISSUE TITLE
UI elements are not spaced correctly

### ISSUE THREAD

**Issue by stichiboi** [adobe/spectrum-css#761]
## Description
I'm trying to create a simple UI using the code snippets from the spectrum css documentation.
But when I preview the HTML file, the spacing between components is different from the one displayed in the code snippets.

I think I'm missing some key module
## Screenshots
This is what I want to recreate. I made it in ExtendScript
<img width="284" alt="Screenshot 2020-07-10 at 15 02 56" src="https://user-images.githubusercontent.com/38842504/87157360-71f9ea00-c2be-11ea-80f3-4d19c239667c.png">

But the layout is completely off when I try to create it using HTML with the Spectrum CSS, even though I literally copy-pasted the HTML code from the [verified documentation ](https://opensource.adobe.com/spectrum-css/tabs.html#basictabs)
<img width="183" alt="Screenshot 2020-07-10 at 15 02 23" src="https://user-images.githubusercontent.com/38842504/87157314-60b0dd80-c2be-11ea-8ff2-9cd581ac424c.png">

## Environment
 - **Spectrum CSS version:**  2.13.0 
 - **Browser(s) and OS(s):** Firefox 78.0.1 (but the same happens if I run the extension in AE 2020)

## Additional context
Here is the HTML code
```html
<!doctype html>
<html class="spectrum spectrum--dark spectrum--medium">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="node_modules/@spectrum-css/vars/dist/spectrum-global.css">
  <link rel="stylesheet" href="node_modules/@spectrum-css/vars/dist/spectrum-medium.css">
  <link rel="stylesheet" href="node_modules/@spectrum-css/vars/dist/spectrum-dark.css">

  <link rel="stylesheet" href="node_modules/@spectrum-css/button/dist/index-vars.css">
  <link rel="stylesheet" href="node_modules/@spectrum-css/buttongroup/dist/index-vars.css">
  <link rel="stylesheet" href="node_modules/@spectrum-css/page/dist/index-vars.css">
  <link rel="stylesheet" href="node_modules/@spectrum-css/tabs/dist/index-vars.css">
  <link rel="stylesheet" href="node_modules/@spectrum-css/typography/dist/index-vars.css">
</head>

<body>

  <div class="spectrum-ButtonGroup spectrum-ButtonGroup--vertical">
    <button class="spectrum-Button spectrum-Button--primary spectrum-ButtonGroup-item">
      <span class="spectrum-Button-label">Add Shapes</span>
    </button>
    <div class="spectrum-ButtonGroup spectrum-ButtonGroup-item">
      <button class="spectrum-Button spectrum-Button--primary spectrum-ButtonGroup-item">
        <span class="spectrum-Button-label">Update</span>
      </button>
      <button class="spectrum-Button spectrum-Button--primary spectrum-ButtonGroup-item">
        <span class="spectrum-Button-label">Refresh</span>
      </button>
    </div>
  </div>

  <div class="spectrum-Tabs spectrum-Tabs--horizontal">
    <a href="#1" class="spectrum-Tabs-item is-selected">
      <span class="spectrum-Tabs-itemLabel">Tab 1</span>
    </a>
    <a href="#2" class="spectrum-Tabs-item">
      <span class="spectrum-Tabs-itemLabel">Tab 2</span>
    </a>
    <a href="#3" class="spectrum-Tabs-item">
      <span class="spectrum-Tabs-itemLabel">Tab 3</span>
    </a>
    <a href="#4" class="spectrum-Tabs-item">
      <span class="spectrum-Tabs-itemLabel">Tab 4</span>
    </a>
    <div class="spectrum-Tabs-selectionIndicator" style="width: 27px; left: 0px;"></div>
  </div>

  <script src="js/libs/CSInterface.js"></script>
  <script src="js/libs/jquery-2.0.2.min.js"></script>

  <script src="js/themeManager.js"></script>
  <script src="js/main.js"></script>

</body>
</html>
```

**Comment by lazd** [comment]
`<html dir="ltr">`?

**Comment by lazd** [comment]
Also looks like those nested ButtonGroups aren't going to do what you want, judging by that vertical stretch on the Update button... I don't think we considered ButtonGroups within ButtonGroups. Please file a separate issue for nested ButtonGroups if it still is broken after the `dir="ltr"` fix.

**Comment by stichiboi** [comment]
@lazd Thanks! the dir="ltr" worked perfectly
How do you suggest doing the 3 button layout?

(don't worry if its too much bother, it's  just that i just started with Extensions and I'm afraid I'm missing some basics)

**Comment by lazd** [comment]
@stichiboi I'd say use `display: flex; flex-direction: column` on the parent element, throw two button groups inside of it, first one vertical with a single button, second one horizontal with 2 buttons.

**Comment by stichiboi** [comment]
Great!
Created the issue
Thanks again
