### ISSUE TITLE
Research: automated release of site

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#766]
synced to jira: https://jira.corp.adobe.com/browse/SDS-7341

**Comment by lazd** [comment]
Site releases should be done after new packages are released, at the top level. With that, this is a 1 line change in `package.json`:

https://github.com/adobe/spectrum-css/blob/master/package.json#L11

```diff
- "release": "npx lerna publish",
+ "release": "npx lerna publish && npm run release:site",
```
