### ISSUE TITLE
[Switch] Large size "on" doesn't seem to go as far right as it does left.

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#773]
## Description
![image](https://user-images.githubusercontent.com/1156657/88489008-716c7f00-cf5f-11ea-83f4-7c7432f3676f.png)
![image](https://user-images.githubusercontent.com/1156657/88489012-792c2380-cf5f-11ea-872e-2002122411fc.png)

When the "large" size switch travels to the "on" position it doesn't seem to go as far to the right and it does to the left when "off".

Currently, the styles is applied as follows when processed:
```
[dir='ltr'] .spectrum-ToggleSwitch-input:checked + .spectrum-ToggleSwitch-switch::before {
    transform: translateX(calc(100% - var(--spectrum-switch-handle-border-size, var(--spectrum-alias-border-size-thick))));
}
```
I think you want it to process down to:
```
translateX(calc(var(--spectrum-switch-track-width) - 100%))
```

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/toggle.html
2. Switch "Scale" to large.
3. Observe the difference between the "off" and "on" switches.

## Expected behavior
The spacing from the edge in both positions in the same.

**Comment by lazd** [comment]
@Westbrook yup, that was the issue. I believe it was changed from animating `left` to using `transform: translateX`, and folks didn't realize that the meaning of `100%` changed from parent width to child width. Easy fix!
