### ISSUE TITLE
[dir] support question

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#779]
## Description
With the move support `[dir]` in the 3.0 beta packages there is still a large amount of `left` and `right` usage in the CSS classes and CSS Custom Properties published for the various packages. Do you see moving to `before`/`after` or `start`/`end` sorts of things to match more closely with modern CSS naming conventions?

For instance, the Card pattern features close to this CSS:
```
[dir=ltr] .spectrum-Card-title {
    padding-right: var(
        --spectrum-card-title-padding-right,
        var(--spectrum-global-dimension-size-100)
    );
}
[dir=rtl] .spectrum-Card-title {
    padding-left: var(
        --spectrum-card-title-padding-right,
        var(--spectrum-global-dimension-size-100)
    );
}
```
This leverages `--spectrum-card-title-padding-right` for both right and left padding. In both cases the design implication is `padding-inline-end`, and while it may be a bit early to use that actual property in the CSS (I've not kept up with browser support as it relates the current - 2 version matrix used here), being we're experiencing a breaking change as it is, would it make sense to leverage Custom Properties more appropriate to longer term use?

## Why do you need this feature or component?
Spectrum Web Components surfaces the [Custom Property API in documentation](https://opensource.adobe.com/spectrum-web-components/components/avatar/api) of the various Spectrum CSS patterns we implement as a customization API and getting possible breaking changes out of the way, while also clarifying the usage of that API with naming over documentation, makes doing so more reliable.

## Additional context
Using something like `--spectrum-card-title-padding-inline-end` (in the case above) will also benefit the size of the CSS overtime as in the future the rule couplet outlined above could be realized as:
```
.spectrum-Card-title {
    padding-inline-end: var(
        --spectrum-card-title-padding-inline-end,
        var(--spectrum-global-dimension-size-100)
    );
}
```
Both halving the CSS required to support `[dir]` decisions, while also removing the need to resolve the value of `:dir` manually in contexts (like shadow DOM) where that sort of context selector isn't currently available cross browser.

synced to jira: https://jira.corp.adobe.com/browse/CSS-222

**Comment by pfulton** [comment]
Linked in Jira to investigate during the removal of postcss-logical: https://jira.corp.adobe.com/browse/CSS-164
