### ISSUE TITLE
[QuickActions] ".spectrum-QuickActions--left/right" not bound to "[dir]" values

### ISSUE THREAD

**Issue by Westbrook** [adobe/spectrum-css#785]
## Description
When using the `.spectrum-QuickActions--left/right` classes with the QuickActions pattern the position/animation styling isn't bound to the `[dir]` attribute and will appear the same regardless of the content direction currently featured on the page.

```
.spectrum-QuickActions--left.is-open {
    transform: translateX(
        var(
            --spectrum-dropdown-flyout-menu-offset-y,
            var(--spectrum-global-dimension-size-75)
        )
    );
}

.spectrum-QuickActions--right.is-open {
    transform: translateX(
        calc(
            -1 * var(--spectrum-dropdown-flyout-menu-offset-y, var(--spectrum-global-dimension-size-75))
        )
    );
}
```

synced to jira: https://jira.corp.adobe.com/browse/CSS-221

**Comment by pfulton** [comment]
@Westbrook is this still an issue for you all? If so, we can look at taking care of this when we do the logical properties work.

**Comment by pfulton** [comment]
Linked in Jira to investigate during the removal of postcss-logical: https://jira.corp.adobe.com/browse/CSS-164
