### ISSUE TITLE
Header of Accordion component relies on user agent style to work

### ISSUE THREAD

**Issue by jianliao** [adobe/spectrum-css#79]
### Expected Behavior
Hover state of  `spectrum-Accordion-itemHeader` should not rely on user agent style for div to work. Because if I want to use it on a custom element or use it with customized normalize css, it will not work properly.

![image](https://user-images.githubusercontent.com/1207520/51647301-0b013d80-1f31-11e9-96a9-58156dd01eb0.png)

### Actual Behavior
Hover state of `spectrum-Accordion-itemHeader` reply on below user agent style to work.
`
div {
    display: block;
}
`

![screen shot 2019-01-23 at 4 57 32 pm](https://user-images.githubusercontent.com/1207520/51647267-f2912300-1f30-11e9-8b06-9a5e214df248.png)

### Reproduce Scenario (including but not limited to)

Use spectrum-css with angular component.

#### Steps to Reproduce

Suppose I have a component template as below:

```html
<ac-accordion class="spectrum-Accordion">
    <ac-accordion-item class="spectrum-Accordion-item">
        <ac-accordion-item-header class="spectrum-Accordion-itemHeader">Header 1</ac-accordion-item-header>
    </ac-accordion-item>
    <ac-accordion-item class="spectrum-Accordion-item">
        <ac-accordion-item-header class="spectrum-Accordion-itemHeader">Header 2</ac-accordion-item-header>
    </ac-accordion-item>
</ac-accordion>
```

Since class `spectrum-Accordion-itemHeader` is on a custom element, not on div. The hover state would not work.

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)

Latest Chrome Beta

#### Spectrum-CSS version

2.7.2

**Comment by jianliao** [comment]
If the fix would be adding `display: block` on spectrum-Accordion-itemHeader class, I would love to provide a PR.

**Comment by lazd** [comment]
@jianliao sounds like that would be the proper fix! Please go ahead and send the PR.
