### ISSUE TITLE
Display Problems in CC 2017

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#80]
### Expected Behavior
In CC 2018 the search widget looks like this:
![adobe_indesign_cc_2018](https://user-images.githubusercontent.com/395968/51668307-924ebf80-1fca-11e9-8597-0b075e362790.png)

### Actual Behavior
In CC 2017, it looks like this:
![screenshot_1_24_19__11_21_am](https://user-images.githubusercontent.com/395968/51668378-c0cc9a80-1fca-11e9-921f-3b06272ec8c3.png)

All the SVG <use> elements appear to be doubled up and one instance enlarged.
### Reproduce Scenario (including but not limited to)
n/a
#### Steps to Reproduce
n/a
#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
InDesign CC 2017 on Mac
#### Spectrum-CSS version
Latest

**Comment by lazd** [comment]
You need to add `.spectrum--medium` or `.spectrum--large` as an outer class to tell it which icon to display. See https://github.com/adobe/spectrum-css#medium-and-large

**Comment by Harbs** [comment]
This is the classlist I have on `<body>`:
`Application spectrum spectrum--medium spectrum--dark`

That works for CC 2018, but not for CC 2017.

For kicks I added `spectrum--medium` to also the `<html>` tag and that seems to do the trick.

InDesign CC 2017 uses CEP 7 which renders using Chromium version 41.0.2272.104 while CC 2018 uses CEP8 which uses 57.0.2987.74. That's likely the cause of the difference, although for the life of me I can't understand why there would be a difference whether the `spectrum--medium` class is applied to `<body>` or to `<html>`...

Even after adding `spectrum--medium` to `<html>` the problem with the placeholder text in Search not being italic is still an issue. Should I create a separate issue for that?

**Comment by Harbs** [comment]
Further investigation seems to indicate that the following is needed for CC 2017:
````
.spectrum-Textfield::-webkit-input-placeholder {
  font-weight: 400;
  font-style: italic;
  transition: color 130ms ease-in-out;
}
````
Adding that seems to fix the italics issue.  Should I make a PR for that?
