### ISSUE TITLE
When Spectrum Angular will be open-sourced?

### ISSUE THREAD

**Issue by lordsfantasy** [adobe/spectrum-css#800]

**Comment by misterbrownlee** [comment]
Great question!  We are not directly involved in that team's work.  I will forward that question to them and someone will either answer here directly, or we relay their response.  Thanks!

**Comment by lordsfantasy** [comment]
Ok, thanks! I will look forward to it.

**Comment by iamwillpowell** [comment]
Hi. Unfortunately, we don't have current plans to open source the Angular components. It has come up a few times and things could change. In the meantime, you might investigate using Spectrum Web Components with Angular. https://opensource.adobe.com/spectrum-web-components/
