### ISSUE TITLE
Check card against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#811]
Check [card](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/card)
- [ ] matches DL
- [ ] check VRT passes
- [ ] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by jianliao** [comment]
VRT fail caused by workflow icon size change.
![image](https://user-images.githubusercontent.com/1207520/92627801-bedb4c00-f280-11ea-9889-1b2f5b97c938.png)
