### ISSUE TITLE
Check button against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#813]
Check [button](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/button)
- [ ] matches DL
- [x] check VRT passes
- [x] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

### Components
- ❌ Action button: icon sizing issues
- ✅ Button - CTA
- ✅ Button - Over Background
- ❌ Button - Primary: icon sizing issues
- ✅ Button - Secondary
- ✅ Button - Warning
- ✅ Logic button
- ❌ Cycle button: icon sizing issues
- ✅ Clear button
- ✅ Split button

**Comment by lazd** [comment]
Tokens 17 borks the icon sizing and crops custom icons:
![image](https://user-images.githubusercontent.com/201344/93239121-37398580-f737-11ea-98be-a15f5beaa90b.png)


Token 17 Action button with icon: 
![image](https://user-images.githubusercontent.com/201344/93239165-43bdde00-f737-11ea-8ffa-c5896d0d2896.png)

Previous Action button with icon:
![image](https://user-images.githubusercontent.com/201344/93239192-4ae4ec00-f737-11ea-9176-35532e9278c3.png)

**Comment by lazd** [comment]
@jianliao can you weigh in on the icon issues? I have a feeling this might be a good issue for you to handle; I did the legwork of identifying the problems, but I think you have the knowledge to solve them already at the top of your head.
