### ISSUE TITLE
Check actiongroup against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#814]
Check [actiongroup](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/actiongroup)
- [ ] matches DL
- [ ] check VRT passes
- [ ] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by GarthDB** [comment]
![image](https://user-images.githubusercontent.com/125516/92629551-b6d4d980-f28b-11ea-8443-cf3e9916f099.png)
border missing and icon sizing breaking VRT - related to #813

**Comment by lazd** [comment]
Border change is intentional according to @pudjeeb
