### ISSUE TITLE
Check colorhandle against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#815]
Check [colorhandle](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/colorhandle)
- [ ] matches DL
- [ ] check VRT passes
- [ ] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by GarthDB** [comment]
![image](https://user-images.githubusercontent.com/125516/92624696-082d9a80-f285-11ea-9a7e-4dc3d41e352a.png)
Positioning is off.

**Comment by lazd** [comment]
Yeah the loupe has scooted over a little...
