### ISSUE TITLE
Add sass compiling validation phrase while building the library

### ISSUE THREAD

**Issue by jianliao** [adobe/spectrum-css#82]
### Expected Behavior
To avoid the problem like #61, we can introduce a sass compiling phrase while building the library. I've used this solution to catch a few invalid CSS file issues for angular-spectrum component library.

The solution is pretty simple:
1. Add gulp-sass as dev dependency
2. Create task and attach to the end phrase of build task. We don't need to keep the generated files, if sass compiling passed, we remove the generated files.

I would like to provide a PR if you agree.
  
#### Spectrum-CSS version
Latest version and all the future versions.

**Comment by GarthDB** [comment]
I'm for anything that improves code consistency and validation. @jianliao would you want to do any validation on a ci like Travis?

**Comment by jianliao** [comment]
I just created a PR #84 for review. It is super fast. If we could integrate it with build task. Every change we made could be ensure not breaking the angular-cli like tool.
