### ISSUE TITLE
Check dropzone against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#821]
Check [dropzone](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/dropzone)
- [ ] matches DL
- [ ] check VRT passes
- [ ] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by GarthDB** [comment]
![image](https://user-images.githubusercontent.com/125516/92625034-6e1a2200-f285-11ea-8421-8f681664d9cd.png)
Typography is off.

**Comment by lazd** [comment]
Not only did Typography change, but with the new Typography styles, we can't get the old colors. Asked @NateBaldwinDesign about this and will do as he says.

With old Typography:
![image](https://user-images.githubusercontent.com/201344/93241754-a82e6c80-f73a-11ea-8c1c-d12695ef876b.png)

With new Typography:
![image (1)](https://user-images.githubusercontent.com/201344/93241773-af557a80-f73a-11ea-9c20-61a24282918d.png)

**Comment by lazd** [comment]
@NateBaldwinDesign said we can just use the colors as-is and file a bug, so I deed it.
