### ISSUE TITLE
Check progressbar against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#829]
Check [progressbar](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/progressbar)
- [x] matches DL
- [ ] check VRT passes
- [x] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by GarthDB** [comment]
VRT not returning image for progress bar

**Comment by bernhard-adobe** [comment]
I did not notice any differences between the latest release and the version in branch `spectrum-tokens-17`. The renaming of _Bar Loader_ into _Progress Bar_ is intended in `DNA-beta-6-17
`
![Screen Shot 2020-09-15 at 22 03 10](https://user-images.githubusercontent.com/52184321/93284820-7b617000-f7a1-11ea-9e27-9a3f59cbe4c9.png)
![Screen Shot 2020-09-15 at 22 04 07](https://user-images.githubusercontent.com/52184321/93284823-7dc3ca00-f7a1-11ea-8a07-cc1119fcf898.png)
![Screen Shot 2020-09-15 at 22 04 21](https://user-images.githubusercontent.com/52184321/93284827-7ef4f700-f7a1-11ea-8ee9-f160cafa5181.png)
