### ISSUE TITLE
Check menu against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#836]
Check [menu](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/menu)
- [ ] matches DL
- [ ] check VRT passes
- [ ] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by GarthDB** [comment]
Border has gone missing and positioning is changed by icon sizing changes.
![image](https://user-images.githubusercontent.com/125516/92626212-da495580-f286-11ea-9127-457d5e5cc78a.png)

**Comment by jianliao** [comment]
ActionButton Border missing is expected. Below screen captured from un-released `ActionButton-v6.0.xd` 
![image](https://user-images.githubusercontent.com/1207520/92626606-fc3eda00-f27e-11ea-91c4-277fe6fdc0a8.png)
