### ISSUE TITLE
Check icon against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#839]
Check [icon](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/icon)
- [ ] matches DL
- [x] check VRT passes
- [x] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by GarthDB** [comment]
Icon doesn't have VRT

**Comment by jianliao** [comment]
Looks like all the input field examples with icon got broken.
![image](https://user-images.githubusercontent.com/1207520/93933321-535c9a00-fcd6-11ea-88f6-4bf85801ed7a.png)
