### ISSUE TITLE
Check underlay against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#841]
Check [underlay](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/underlay)
- [x] matches DL
- [ ] check VRT passes
- [ ] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by GarthDB** [comment]
No vrt for underlay

**Comment by bernhard-adobe** [comment]
## Summary:
Modal & Tray look good.
I confirm that the CSS props are being applied to the underlay in main.

The token `  --spectrum-dialog-underlay-background-color: var(--spectrum-alias-background-color-modal-overlay);`
got removed and replaced with `  --spectrum-dialog-confirm-overlay-background-color: var(--spectrum-alias-background-color-modal-overlay);`
The values are identical. 


## How has this been tested:
Chrome Version 87.0.4260.0 (Official Build) canary (x86_64) on MacOS


## Screenshots:

![Screen Shot 2020-09-17 at 16 22 45](https://user-images.githubusercontent.com/52184321/93524188-20935a00-f902-11ea-8e71-89d636207b02.png)
![Screen Shot 2020-09-17 at 16 16 59](https://user-images.githubusercontent.com/52184321/93524189-21c48700-f902-11ea-9a54-2c3c8b881df8.png)
![Screen Shot 2020-09-17 at 15 49 52](https://user-images.githubusercontent.com/52184321/93524196-2426e100-f902-11ea-896b-4713b83fcaa7.png)
