### ISSUE TITLE
Check radio against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#845]
Check [radio](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/radio)
- [ ] matches DL
- [x] check VRT passes
- [x] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by lazd** [comment]
@GarthDB I think something might not have gone totally right here, it seems Radio and Radio Quiet are the same, Emphasis not implemented. Should I file a separate issue?
