### ISSUE TITLE
Check slider against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#850]
Check [slider](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/slider)
- [ ] matches DL
- [ ] check VRT passes
- [ ] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by GarthDB** [comment]
Some label sizing changes and this variant is broken in VRT
![image](https://user-images.githubusercontent.com/125516/92627507-b25af180-f288-11ea-9545-04a32c9bcc01.png)

**Comment by bernhard-adobe** [comment]
also slider-variant color is missing from code. 
![Screen Shot 2020-09-16 at 17 34 47](https://user-images.githubusercontent.com/52184321/93394899-ef078980-f842-11ea-9e39-df5b0a00cd6d.png)
