### ISSUE TITLE
Please include Chromium 41 in testing platforms

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#86]
I think a significant target for spectrum is CEP panels and we need to target multiple versions of CC.

Many users are still using older versions of CC apps and are stuck using Chromium version 41.0.2272.104 for rendering of content. That makes Chromium 41 an important target for Spectrum.

 I already discovered some rendering issues in that version of Chromium in issue #80  and there there might be more.

https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_8.x/Documentation/CEP%208.0%20HTML%20Extension%20Cookbook.md#chromium-embedded-framework-cef

**Comment by GarthDB** [comment]
@Harbs we do not have a dedicated qe - any chance we could get some community help with this platform?

**Comment by Harbs** [comment]
Okie Dokie. I'll report any issues I find... ;)
