### ISSUE TITLE
Stepper Deprecated?

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#87]
The documentation for Stepper says it's deprecated with no explanation.

I can't imagine why you'd want to deprecate a stepper. It seems like an important UI component. Could we have some insight into this?

**Comment by lazd** [comment]
Yes, stepper is indeed deprecated. The idea is that a number field would be used instead, with the arrow keys. 

@NateBaldwinDesign can elaborate.

**Comment by MikeLundahl** [comment]
Hi, just started using spectrum-css and are still learning and finding my way around it. is there any updates on the stepper? Is there a component that replaces this since it's deprecated? 
[https://opensource.adobe.com/spectrum-css/components/stepper/](url)

**Comment by GarthDB** [comment]
@MikeLundahl There aren't any plans to update stepper.

**Comment by lazd** [comment]
@MikeLundahl @Harbs Stepper was was un-deprecated, zombie stepper has been released as 3.0.0-beta.3 https://github.com/adobe/spectrum-css/blob/master/components/stepper/CHANGELOG.md#300-beta1
