### ISSUE TITLE
Check tags against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#870]
Check [tags](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/tags)
- [ ] matches DL
- [x] check VRT passes
- [x] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by GarthDB** [comment]
Icons breaking VRT 
![image](https://user-images.githubusercontent.com/125516/92629188-2bf3df00-f28b-11ea-90a2-20044a24bd5f.png)

**Comment by jianliao** [comment]
This issue is caused by #819
