### ISSUE TITLE
Check overlay against DL and VRT

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#872]
Check [overlay](https://github.com/adobe/spectrum-css/tree/spectrum-tokens-17/components/overlay)
- [ ] matches DL
- [ ] check VRT passes
- [ ] check and update migration guides [example](https://github.com/adobe/spectrum-css/blob/f58d8e071e5cce8db653e61c5a09b7690c236f63/components/pagination/metadata/pagination-explicit.yml#L3)

**Comment by GarthDB** [comment]
Fix with #227

**Comment by bernhard-adobe** [comment]
I looked at the overlay and can confirm that there are no visual changes or code changes between `spectrum-tokens-17` and `main`. The animation definitions have a different line-wrapping in the tokens branch which I am considering reverting to consistency. 

# Screenshots:
<img width="1911" alt="Screen Shot 2020-09-21 at 16 52 31" src="https://user-images.githubusercontent.com/52184321/93821906-52bbf900-fc2d-11ea-9f97-bf7946ee6d5b.png">

![Screen Shot 2020-09-21 at 17 08 25](https://user-images.githubusercontent.com/52184321/93821936-5e0f2480-fc2d-11ea-9c08-b065b78a91a2.png)

**Comment by bernhard-adobe** [comment]
I pushed a small line-break change for Underlay in https://github.com/adobe/spectrum-css/commit/c897c23c1e4004cfdc6541ceb5a5b4b00bb198d4
