### ISSUE TITLE
Clear Button misplaced in SearchWithin

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#880]
## Description
Clear Button misplaced in SearchWithin

## Steps to reproduce

1. Build the docs from the main branch.
1. Go to http://localhost:3000/docs/searchwithin.html
2. Look at the `Default (Changed Selection)` example
3. Observe the clear button is to far to the left.

## Expected behavior
The position should match the other examples

## Screenshots
![Image 9-1-20 at 11 09 PM](https://user-images.githubusercontent.com/395968/91901356-c8751a80-eca8-11ea-9671-a453fd286559.jpg)

## Environment
 - **Spectrum CSS version:** (latest)
 - **Browser(s) and OS(s):** Firefox on Mac (didn't check other browsers)

**Comment by Harbs** [comment]
FYI, I just checked in Chromium and the problem does not appear there.

**Comment by Harbs** [comment]
To be completely clear, the text field border is drawing wider than the actual input in Firefox, but in chromium it's drawing to the true input border. The clear button appears to be in the correct location in all cases.

**Comment by Harbs** [comment]
Further inspection seems to indicate that it has something to do with the input `min-width`. The default value in FIrefox is `auto` which sets the width too wide. (Interestingly enough, explicitly setting it to `auto` in Chromium does not cause issues.) I have no idea why the difference between browsers, but explicitly setting the input `min-width` to `inherit` makes the problem go away.

HTH...

**Comment by lazd** [comment]
Gotcha, seems like we need to change the `min-width`. Go ahead and send a PR with your fix and we'll merge!

**Comment by misterbrownlee** [comment]
Thanks for breaking CSS, @Harbs 🤣

**Comment by misterbrownlee** [comment]
Oh... correction.  Thanks for *fixing* CSS ;)

**Comment by Harbs** [comment]
`inherit` helps in that case, but if the dropdown selected text is wide, things get wonky...
![Screen Shot 2020-09-02 at 1 46 02 PM](https://user-images.githubusercontent.com/395968/91972046-cbacec80-ed22-11ea-91c3-4805d2a5397b.png)

**Comment by Harbs** [comment]
The following CSS solves this case:

````
.spectrum-SearchWithin > .spectrum-Textfield {
  flex-grow: 1;
}
````
My proposed fix to both of these issues is to change:
````
.spectrum-SearchWithin-input {
  -ms-flex: 1;
      flex: 1;
}
````
to:
````
.spectrum-SearchWithin-input {
  -ms-flex: 1;
      flex: 1;
  min-width: inherit;
}
.spectrum-SearchWithin > .spectrum-Textfield {
  flex-grow: 1;
}
````
If that makes sense to you, I'll create a PR.

**Comment by Harbs** [comment]
I also propose adding the following to `.spectrum-SearchWithin-picker`

`max-width: calc(100% - 100px);`

Currently, a very wide dropdown/picker will shrink the search field down to 48 pixels which IMO is much too narrow: 
![Image 9-2-20 at 2 35 PM](https://user-images.githubusercontent.com/395968/91976398-8cce6500-ed29-11ea-850a-f07ae54ef822.jpg)

With the above change, it looks like this:
![Screen Shot 2020-09-02 at 2 36 25 PM](https://user-images.githubusercontent.com/395968/91976555-ce5f1000-ed29-11ea-833a-4ede6fbccae1.png)

**Comment by Harbs** [comment]
Possible, a css variable is better than a hard-coded 100px. Not sure which one is appropriate.

**Comment by Harbs** [comment]
I'm guessing it should be   `--spectrum-global-dimension-size-1200` (96px) or `--spectrum-global-dimension-size-1250` (100px).

Although I'm not sure how localized `Search` placeholders will look with hard-coded dimensions.

I can create the PR without the last change, or with direction on the correct way to implement that last change.

Please let me know which is better. :-)

**Comment by lazd** [comment]
Hmm, I think we can accomplish this without the `width: calc()` business, which I think is why we had a `min-width` on the input to begin with...

**Comment by Harbs** [comment]
I tried using `min-width` on the input, but the clear button ended up in the wrong place. `calc` worked better. But you guys probably have better css-foo than I do... 😉

**Comment by Harbs** [comment]
(Notice the clear button in the top image where the min-width of the input is 48px.)
