### ISSUE TITLE
Migration Issues

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#882]
## Description
We were having trouble updating our CSS in our spectrum implementation. We last updated at about the beginning of the year. There were LOTS! of changes since then. We ended up going through all the components and compiling a list of issues we found.

## Additional context
A CHANGELOG file which is updated with changes (i.e. additions, subtractions and changes) would be very much appreciated!

## Here is our shorthand list 
* **Action Button:** Emphasized, click doesn't work.
* **Action Group:** Removed.
* **AssetList:** Missing > check why
* **Breadcrumbs:** nested (root visible) missing nav root. Same for multiline nested, compact nested, compact nested root visible, title disabled
* **ButtonGroup:** needs changes
* **Calendar:** focused
* **Color Area:** Markup, missing things...
* **Color Handle:** new
* **Color Loupe:** new
* **Color Slider:** new
* **Color Wheel:** new
* **Combobox:** text field changes
* **Date Picker:** structure changed
* **Dialog:** is a mess
* **Dropdown:** renamed to Picker
* **Link:** removed subtle, added secondary
* **Pagination - explicit:** use new textfield
* **Pagination - page:** needs work
* **Popover:** dialog style...
* **Radio:** 2 long radios connected
* **Rule:** renamed to Divider
* **Search:** needs new text field
* **SearchWithin:** needs new text field and dropdown
* **Side Nav:** icon is not in selectionbox
* **Stepper:** needs change and new textfield
* **Tabs:** missing a lot
* **Tags:** messed up
* **Thumbnail:** new
* **Toast:** some are deprecated
* **Tool:** removed
* **Tooltip:** some are deprecated
* **Treeview:** changes
* **Typography:** changes
* **RTLlayout:** new `dir='ltr'` is now required somewhere up the HTML tree for normal LTR layout

I hope this is helpful to someone...

**Comment by lazd** [comment]
We've got a changelog for every component (here's [Button](https://github.com/adobe/spectrum-css/blob/main/components/button/CHANGELOG.md)), but we don't have a changelog with everything in one place. Hope that helps!

**Comment by GarthDB** [comment]
@Harbs there are also migration guides in the metadata for some components.

**Comment by lazd** [comment]
Like @GarthDB, we have some migration guides here: https://opensource.adobe.com/spectrum-css/textfield.html#migrationguide

Please do file separate issues for anything that's messed up!
