### ISSUE TITLE
Toast missing separator in color stop build

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#884]
## Description
Toast is supposed to have a separator

The following CSS is output for the colorstop css:

````
.spectrum--light [dir="ltr"] .spectrum-Toast-buttons {
  border-left-color: rgba(255, 255, 255, 0.2);
}
.spectrum--light [dir="rtl"] .spectrum-Toast-buttons {
  border-right-color: rgba(255, 255, 255, 0.2);
}
````
I don't understand all the nitty gritty of CSS, but for some reason, browsers don't seem to see this CSS. I thought  that it might be the dir='ltr' between the selectors, but moving it to the beginning does not help. Somehow, the combination of descendants and dir pseudo-selectors don't seem to work.

Considering that the colors are the same for all color stops, it seems to me that the fix is simply to have a single set of declarations for all color stops:
````
[dir="ltr"] .spectrum-Toast-buttons {
  border-left-color: rgba(255, 255, 255, 0.2);
}
[dir="rtl"] .spectrum-Toast-buttons {
  border-right-color: rgba(255, 255, 255, 0.2);
}
````
The above CSS works as expected.

**Comment by Harbs** [comment]
(I'm not sure how to accomplish that goal, because a lot of the css processing goes over my head, but I suspect the declaration should be moved from `skin.css` to `index.css`.)

**Comment by lazd** [comment]
Ok, I see what's happening. We're defining a left/right sided property in `skin.css`, which needs to be wrapped by the theme color (i.e. `.spectrum--light`). But since it is sided, it also needs to be wrapped by a `[dir]` to apply to the correct side for RTL.

We should be applying `[dir]` before `.spectrum--*` in our PostCSS output, or we should be defining the sidedness of the border (`border-width`) in `index.css` and the color in `skin.css`.

**Comment by Harbs** [comment]
For the record, there appears to be a difference between `[dir='ltr']` and `:dir(ltr)`.

Both of the following versions appear to work as expected:

````
.spectrum--light :dir(ltr) .spectrum-Toast-buttons {
  border-left-color: rgba(255, 255, 255, 0.2);
}
.spectrum--light :dir(rtl) .spectrum-Toast-buttons {
  border-right-color: rgba(255, 255, 255, 0.2);
}
````
and 
````
:dir(ltr) .spectrum--light .spectrum-Toast-buttons {
  border-left-color: rgba(255, 255, 255, 0.2);
}
:dir(rtl) .spectrum--light .spectrum-Toast-buttons {
  border-right-color: rgba(255, 255, 255, 0.2);
}
````

**Comment by Harbs** [comment]
Perhaps `:dir` should be used instead of `[dir]`?

**Comment by Harbs** [comment]
@lazd I'm not sure if I didn't understand you or the other way around, but neither of the following work:

````
.spectrum--light [dir="ltr"] .spectrum-Toast-buttons {
  border-left-color: rgba(255, 255, 255, 0.2);
}
.spectrum--light [dir="rtl"] .spectrum-Toast-buttons {
  border-right-color: rgba(255, 255, 255, 0.2);
}
````
or
````
[dir="ltr"] .spectrum--light .spectrum-Toast-buttons {
  border-left-color: rgba(255, 255, 255, 0.2);
}
[dir="rtl"] .spectrum--light .spectrum-Toast-buttons {
  border-right-color: rgba(255, 255, 255, 0.2);
}
````

**Comment by Harbs** [comment]
I think I understand why the css is not working:
As per the note on this page https://developer.mozilla.org/en-US/docs/Web/CSS/:dir, `[dir]` does not work with inheritance.

The reason `[dir]` works in most cases is because `[dir]` matches the ancestor and the next selector matches the descendant. In my html, dir and the spectrum theme is both attached to the same element (i.e. `body`) for `dir="ltr"] .spectrum--light` to work, `.spectrum--light` must be nested in inside an element with `dir` of `ltr`. The other CSS works the other way around.

But `:dir` doesn't care about hierarchy. It seems to me that `:dir` is a better fit for spectrum than `[dir]`.

I hope my observations are useful... 😄

**Comment by Harbs** [comment]
Things are obviously not as simple as I thought. I tried to change `[dir]` to `:dir()` wholesale in the toast css and it messed other things up. For example, the right and left padding only works with `[dir]` and not `:dir()`. I'm clueless as to why.

Sometimes CSS feels like black magic... 😉

**Comment by Harbs** [comment]
The underlying cause is effecting other components such as Table. We're applying `dir` to the `<html>` element as well as the first `div` below `body`. `body` has the color class applied. That way the hierarchy of the css doesn't matter...

**Comment by GarthDB** [comment]
This seems to be fixed now - the separator is visible in all color stops.
