### ISSUE TITLE
Vertical Rhythm

### ISSUE THREAD

**Issue by vladimircores** [adobe/spectrum-css#887]
## Description
Vertical Rhythm is necessary part to provide order to layout. In your documentation I could not find anything mentioning this design concept. Request: please add something about vertical rhythm and maybe tools to check it on the page.

## Why do you need this feature or component?
It makes the page and typography feel consistent and visually pleasant (from [this](https://dev.to/adrianbdesigns/mastering-css-vertical-rhythm-om9) article).

## Additional context
This is an interesting tool to check vertical rhythm: https://basehold.it/

Peace,
VM

**Comment by GarthDB** [comment]
@vladimircores, thanks for the recommendation. The typography components already are designed to work with specific spacing (vertically and horizontally). They are not specifically designed to use the vertical rhythm mentioned in the article and there aren't plans to work towards that currently. For more details, take a look at the design language usage guidelines for typography.
