### ISSUE TITLE
Miller Columns

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#89]
While attempting to implement the Miller Column component, we discovered we're not sure what the intent is.

The only use of Miller Columns that I'm aware of is a browser for a file directory structure.

Miller Columns has two variants. One where you can select folders and one where you can't. There's also check-boxes and I'm not sure what the purpose of the checkboxes are.

I'd love to get some explanation of the user experience and intended use cases.

Thanks!

**Comment by lazd** [comment]
@NateBaldwinDesign do we have docs we can share with @Harbs?

**Comment by misterbrownlee** [comment]
Hi!  We're following up on questions, sorry for the late response.  Miller is still under development internally, and as such documentation isn't available outside of Adobe. Once there is, it will be mentioned on the what's new page of the Spectrum docs, so keep an eye out there.  Thanks!

https://spectrum.adobe.com/page/whats-new/

**Comment by Harbs** [comment]
If someone could leave a note when there's more info, I'd appreciate it.

Thanks!
