### ISSUE TITLE
Wrong reference to spectrum-Dialog-wrapper

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#891]
## Description
The Dialog example has the following text:
````In order to avoid blurry Dialogs, wrap them in <div class="spectrum-Dialog-wrapper"> and apply .is-open to both the Wrapper and the Dialog at the same time.````

If I'm not mistaken, `spectrum-Dialog-wrapper` has been removed in favor of `spectrum-Modal-wrapper`. The docs should be changed.

## Link to documentation
https://opensource.adobe.com/spectrum-css/dialog.html#usage
I'm not sure where to find a current build of the docs, but it can be still seen when running locally.

**Comment by GarthDB** [comment]
Thanks!

**Comment by Harbs** [comment]
When is the plan to merge `spectrum-tokens-17` into `main`? I'd like to coordinate my own updates.
