### ISSUE TITLE
ActionBar uses ButtonGroup

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#894]
## Description
I'm pretty sure that with v3 it should be using ActionGroup

(just a quick note before I forget)

I'm not sure if `spectrumButtonGroup` without `spectrum-ButtonGroup-item` is _supposed_ to work like that or not, but it currently works like a "compact" group.

synced to jira: https://jira.corp.adobe.com/browse/SDS-7519

**Comment by GarthDB** [comment]
This has been fixed. Action Bar currently uses `spectrum-ActionGroup` which has `spectrum-ActionGroup-item`s.
