### ISSUE TITLE
Fix broken images in Quiet Card examples

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#9]
### Expected Behavior

No broken images

### Actual Behavior

So many broken images

#### Steps to Reproduce

1. Go here http://opensource.adobe.com/spectrum-css/2.6.0/docs/?color=light&scale=medium&method=standalone#card---gallery
2. Be sad at broken images

#### Spectrum-CSS version

2.6.0

**Comment by GarthDB** [comment]
Fixed by https://github.com/adobe/spectrum-css/pull/15
