### ISSUE TITLE
Suggestion: Maintain two versions of spectrum css

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#901]
## Description
As discussed recently #892, there are various reasons to modernize the css. That includes using grid and more exclusive use of css variables etc. That causes backwards-compatibility issues. I'd like to suggest that there be two paths for the spectrum css.

1. Targeted at optimal and future-proof output.
2. Targeted at legacy and specialized needs.

This can be in the form of different branches, or an alternate folder structure.

## Why do you need this feature or component?
* Output path 1 is obviously important for Adobe internally and is probably the more "correct" approach going forward.
* Output path 1 can be optimized to output the smallest possible css and would not need the cumbersome color stops output.
* Output path 2 is important for supporting legacy browsers such as IE11 which is still needed in certain corporate environments. It's also important for supporting CEP7 which is needed for come CEP panels.
* Output path 2 can also be used for implementing some non-standard needs which don't have completely strict adherence to the Adobe Design approval but might be needed for some practical considerations.
* Additionally, there's a long outstanding request for customization for CEP panels. #95 Non-standard styling to fulfill that request can go in the non-standard output path.

## Additional context
If this idea is acceptable, I am volunteering to help make it happen and help support it.

There will be additional work maintaining at least some amount of duplication of css, but I think there's a lot to be said for having two clear usage paths depending on needs.

**Comment by GarthDB** [comment]
@Harbs there is a lot of logic in the problem arises with resources. If you would like to maintain a backward-compatible version you could do so with the public [Spectrum Tokens](https://www.npmjs.com/package/@adobe/spectrum-tokens) package and stay relatively in sync with the main Spectrum CSS, but it will be a lot of work; probably close to complete duplication of work between the 2 versions.
