### ISSUE TITLE
Stepper Keyboard Navigation

### ISSUE THREAD

**Issue by Harbs** [adobe/spectrum-css#906]
## Description
A Stepper has three interactive elements: The text field, the up button, and the down button.

There is documentation (and css) for how a stepper should look when it has keyboard focus. It's unclear what should happen when a user tabs into the up and down buttons. I can see two valid ways of handling it:

1. Disable tabbing into the stepper buttons and keyboard interaction should only be via the textfield. Stepping up and down can be handled using keyboard arrow keys.
2. Allow tabbing into the buttons and spacebar/enter would work as a click, but then there needs to be a focus ring on those buttons as well.

The fact that the buttons are aria-hidden and has a tab-index of -1 lends me to believe that the intended behavior is the first option, but I'd like confirmation on that.

What is the intended interaction behavior?

## Link to documentation
https://opensource.adobe.com/spectrum-css/stepper.html

**Comment by GarthDB** [comment]
From @NateBaldwinDesign: "focus on the entire field (giving those buttons a blue border too) however the buttons themselves do not receive discrete focus. The keyboard interaction should be that when the field is in focus, up and down arrows will increment the value in the same amount that would be incremented by clicking on either of the arrow buttons."

**Comment by Harbs** [comment]
Perfect. That's what I was hoping/assuming.
