### ISSUE TITLE
Search Within is showing 2 close icons when focused

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#907]
## Description
Search Within is showing 2 close icons when focused

## Steps to reproduce

1. Go to https://opensource.adobe.com/spectrum-css/searchwithin.html
2. Click on a search within component
3. Observe the 2 close icons

## Expected behavior
It should only have one.

## Screenshots
![image](https://user-images.githubusercontent.com/125516/93130202-701e1f80-f68f-11ea-956c-36f7cd86f082.png)

## Environment
 - **Spectrum CSS version:** @spectrum-css/searchwithin@3.0.0-beta.4
 - **Browser(s) and OS(s):** Version 85.0.4183.102 Chrome MacOS

**Comment by pfulton** [comment]
This is still an issue @Deanna-w1
