### ISSUE TITLE
Slider: ticks are not aligned to slider value

### ISSUE THREAD

**Issue by mischnic** [adobe/spectrum-css#927]
## Description

Moving the slider onto a tick doesn't actually give you the value of the tick.

## Screenshots

Slider set to 0:

<img width="788" alt="Bildschirmfoto 2020-09-21 um 15 57 22" src="https://user-images.githubusercontent.com/4586894/93775799-24d1b700-fc23-11ea-8f3f-8cffd0159a8b.png">

Slider set to 20:

<img width="789" alt="Bildschirmfoto 2020-09-21 um 15 56 54" src="https://user-images.githubusercontent.com/4586894/93775740-15526e00-fc23-11ea-813b-0205289e794d.png">

## Steps to reproduce

0. Go to https://opensource.adobe.com/spectrum-css/slider.html#tickwithlabels
1. Move the slider to the very left. The handle is not actually on the tick, but to the right of it.
2. Open the dev tools of your browser, focus the handle `div` and move the handle until it's set to the value 20 (= `left: 20%;`). The handle should now be directly on the tick marked 20, but the tick is once again shifted to the left.

## Expected behavior

The ticks should align with the actual values of the slider, so the center of the circle should be on the tick.

## Environment
 - **Spectrum CSS version:** current version of the website? , probably `@spectrum-css/slider@3.0.0-beta.2`
 - **Browser(s) and OS(s):** Chrome 85.0.4183.102, macOS 10.15

## Additional context

Working on React Spectrum

**Comment by GarthDB** [comment]
That's no good. @mischnic are you using it with React Spectrum or just Spectrum CSS?

**Comment by mischnic** [comment]
I noticed this with React Spectrum (when implementing it: https://github.com/adobe/react-spectrum/pull/1083), but this happens on the Spectrum CSS docs as well.

**Comment by GarthDB** [comment]
I was just discussing it with the react team. We have some things to fix there and it involves the zero tick not corresponding to the center of the handle when the handle is at the zero position. Same for when it is at the upper limit position.

**Comment by mischnic** [comment]
So the two possible solutions would be:

- Don't change the track and move the ticks to the correct position. But this doesn't match the Spectrum Contributions Slider spec. 

<img width="836" alt="Bildschirmfoto 2020-09-23 um 10 38 52" src="https://user-images.githubusercontent.com/4586894/93988433-fb32a000-fd88-11ea-8a7a-92822384d0c4.png">


```diff
diff --git components/slider/index.css components/slider/index.css
index a913fa67..fe2a817a 100644
--- components/slider/index.css
+++ components/slider/index.css
@@ -327,7 +327,7 @@ governing permissions and limitations under the License.
 
   z-index: 0;
 
-  margin: 0 var(--spectrum-slider-track-margin-offset);
+  margin: 0 calc(var(--spectrum-slider-tick-mark-width) / 2 * -1);
   margin-block-start: calc(var(--spectrum-slider-tick-mark-height) + calc(var(--spectrum-slider-track-height) / 2));
 }
 ```

- Make the slider go "off" the track:

<img width="885" alt="Bildschirmfoto 2020-09-23 um 10 42 14" src="https://user-images.githubusercontent.com/4586894/93988813-7431f780-fd89-11ea-8ea5-c48ba891ea30.png">

Something along the lines of 
```diff
diff --git components/slider/index.css components/slider/index.css
index a913fa67..62cf0942 100644
--- components/slider/index.css
+++ components/slider/index.css
@@ -13,7 +13,7 @@ governing permissions and limitations under the License.
 @import '../commons/index.css';

 :root {
-  --spectrum-slider-controls-margin: calc(var(--spectrum-slider-handle-width) / 2);
+  --spectrum-slider-controls-margin: 0;
   --spectrum-slider-track-margin-offset: calc(var(--spectrum-slider-controls-margin) * -1);

   --spectrum-slider-handle-margin-top: calc(var(--spectrum-slider-handle-width) / -2);
```
