### ISSUE TITLE
Update Slider to use text tokens from DNA 6.0.0-beta.18

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#933]
From DNA:
Slider value text had been missing from DNA. Original designs illustrate the value text as being `gray-800`, which is higher contrast than the label itself.

Added typographic tokens relative to `value-text` in all sliders

synced to jira: https://jira.corp.adobe.com/browse/SDS-7562

**Comment by pfulton** [comment]
This component has been migrated to use `@adobe/spectrum-tokens`.
