### ISSUE TITLE
[ActionBar] Validate Action Bar is using update tokens from DNA 6.0.0-beta.18 release

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#934]
From [DNA](https://git.corp.adobe.com/Spectrum/spectrum-dna/pull/418)
- Abstracted shared/common "popover styles" from `Popover` into mixin `PopoverStyle`
- Extended `PopoverStyle` into `Popover`
- Added `ActionBar` component (also extends `PopoverStyle`

synced to jira: https://jira.corp.adobe.com/browse/SDS-7563

**Comment by pfulton** [comment]
This component has been migrated to `@adobe/spectrum-tokens` and this issue is no longer relevant.
