### ISSUE TITLE
T-shirt sizing for Text Area

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#945]
Migration guide from [DNA](https://git.corp.adobe.com/gist/nbaldwin/198d1b43c69a7fb8c2aaf23cbb22a677).
Part of DNA [v6.0.0-beta.21](https://git.corp.adobe.com/Spectrum/spectrum-dna/releases/tag/v6.0.0-beta.21).

synced to jira: https://jira.corp.adobe.com/browse/SDS-7574

**Comment by pfulton** [comment]
Will be done as part of core tokens migration & design catch-up
