### ISSUE TITLE
T-shirt sizing for Search (contribution)

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#946]
Migration guide from [DNA](https://git.corp.adobe.com/gist/nbaldwin/0359ccb13041d1df66afdd0742c14012).
Part of DNA [v6.0.0-beta.21](https://git.corp.adobe.com/Spectrum/spectrum-dna/releases/tag/v6.0.0-beta.21).

synced to jira: https://jira.corp.adobe.com/browse/SDS-7575

**Comment by pfulton** [comment]
Will be done as part of core tokens migration & design catch-up
