### ISSUE TITLE
[Feat. request] Small size

### ISSUE THREAD

**Issue by undavide** [adobe/spectrum-css#95]
Hi,
I guess many CEP Panels (and later UXP) devs will happily jump to Spectrum CSS: is there any plan to add a Small scale, besides Medium and Large, that would maybe fit better such projects? Screen real estate in CC Apps is quite _pricey_ :-) 
Thank you,

Davide

**Comment by Harbs** [comment]
Agree. Medium is not bad, but I would go for a smaller size in panels. If you look at the CC Library panel (for example), many of the spectrum components are there but significantly smaller than medium.

**Comment by undavide** [comment]
It would be nice to know – since Spectrum CSS has been made opensource – whether we are allowed to _borrow_ the CSS that is currently in use for CC apps...
Besides, if the work of shrinking the components has already been done, perhaps with a bit of luck it'll be easier to get it open-sourced / documented as well...

**Comment by jardicc** [comment]
+1

**Comment by lazd** [comment]
@NateBaldwinDesign what's the deal with this one? How hard would it be to get data in DNA to generate a small size?

**Comment by undavide** [comment]
As a side note, the tones are slightly shifted too, compared to CC Apps.
E.g., the background of Spectrum are (r=g=b, from darkest to lightest) 30, 50,  245, 255, while the background of _native_ CC Panels (Photoshop as a reference) are 52, 83, 184, 240. 
Maybe the CEP teams have done some extra preparation, in addition to the resize.

**Comment by Harbs** [comment]
You're right. I wonder why I hadn't noticed that yet.

**Comment by danielglage** [comment]
+1

I DID happily jump to Spectrum CSS and agree with the original post. See attached screenshot for comparison of the "medium" scale to a native InCopy Panel. "Hello, world!" is set in P.

![spectrum-css_needs_small_scale](https://user-images.githubusercontent.com/53834031/62717137-a35d9c00-ba03-11e9-8c98-f177d1a151a5.png)

**Comment by danielglage** [comment]
> As a side note, the tones are slightly shifted too, compared to CC Apps.

This works for me:

```
var style = document.createElement("style");
document.head.appendChild(style);
var sheet = style.sheet;

sheet.insertRule(".spectrum--darkest { background-color: rgb(50, 50, 50); }", 0);
sheet.insertRule(".spectrum--dark { background-color: rgb(83, 83, 83); }", 0);
sheet.insertRule(".spectrum--light { background-color: rgb(184, 184, 184); }", 0);
sheet.insertRule(".spectrum--lightest { background-color: rgb(250, 250, 250); }", 0);
```
(This doesn't adjust text color or element backgrounds.)

**Comment by misterbrownlee** [comment]
was `blocked by design`

**Comment by Harbs** [comment]
What does the label change mean to this issue?

**Comment by misterbrownlee** [comment]
Also... removing blocked label because we're adding things in an ongoing way and the conversation is happening :)

**Comment by Harbs** [comment]
Here's some specific requests:
1. The color stops are off for CEP panels. I have a branch which adjusts many of the colors. It's not perfect, but it's better for panels than the default spectrum stops. https://github.com/adobe/spectrum-css/compare/main...Harbs:cep-colors
2. I have overridden ActionButtons where the height and width are set to 23px. (min-width needs to be changed too.)
3. I have actionbuttons where I need to override left and right margins.
4. If it were easier, I'd probably use a smaller search and searchwithin
5. Same goes for Dropdown (or Picker as it's now called).

HTH

**Comment by Harbs** [comment]
Another couple of targeted points:
1. items in lists need to be smaller.
2. The smallest thumbnail size is `S` which is 30 pixels. For CEP panel lists you want thumbnails going down to about 16-20 pixels.

**Comment by misterbrownlee** [comment]
Design has this on their radar, we will create an issue to change CSS once a decision is made.
