### ISSUE TITLE
Remove deprecated tokens for DNA v6.0.0-beta.21

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#950]
🗑 Removed ‘mouse-focus’ state from Tabs
🗑 Removed ‘mouse-focus’ state from Tab Bar
🗑 Removed ‘mouse-focus’ state from Bottom Navigation
🗑 Removed ‘popover-offset’ from Combo box
🗑 Removed ‘thumbnail’ tokens from Picker
🗑 Removed ‘thumbnail’ tokens from List Item

synced to jira: https://jira.corp.adobe.com/browse/SDS-7579

**Comment by misterbrownlee** [comment]
Is this still open?   Beta-6 releated.
