### ISSUE TITLE
Meter/Progress Bar token update part of DNA v6.0.0-beta.25

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#957]
* Meter update: semantics (Negative, Notice, Positive) as variants
* Meter update: "small" renamed "s", "large" renamed "m"
* Progress Bar update: "small" renamed "s", "large" renamed "m"

synced to jira: https://jira.corp.adobe.com/browse/SDS-7585

**Comment by pfulton** [comment]
Will be done as part of core tokens migration & design catch-up
