### ISSUE TITLE
Slider token updates part of DNA v6.0.0-beta.25

### ISSUE THREAD

**Issue by GarthDB** [adobe/spectrum-css#958]
* Slider update: Editable is no longer a tokenized variant (metadata only)
* Slider update: Range is no longer a tokenized variant (metadata only)
* Slider update: Fill is no longer a variant; track-fill-color added to all variants

synced to jira: https://jira.corp.adobe.com/browse/SDS-7586

**Comment by pfulton** [comment]
Will be done as part of core tokens migration & design catch-up
