### ISSUE TITLE
ToggleSwitch does not fire

### ISSUE THREAD

**Issue by SergioNoivak** [adobe/spectrum-css#960]
## Description

Using 	@spectrum-css/toggle@3.0.0-beta.2
 the switch is simply not triggered, which appears to be a bug in the spectrum css framework.

![save error](https://user-images.githubusercontent.com/28708432/93892317-c9ef9c80-fcc2-11ea-9611-e5848ef460db.PNG)

**Comment by GarthDB** [comment]
@SergioNoivak when you click it, it doesn't move?
It is working on the currently released website which is using `@spectrum-css/toggle@3.0.0-beta.2`
https://opensource.adobe.com/spectrum-css/toggle.html

Are you using the same markup?

**Comment by Schmiddl** [comment]
Hi, I ran into the same issue. Did you set the dir-attribute in your HTML-Tag? dir="ltr" is the switch where the class decides to which direction the switch has to move!
