### ISSUE TITLE
[Mac/Firefox] Texts on Buttons are not centred vertically

### ISSUE THREAD

**Issue by mopandit** [adobe/spectrum-css#964]
## Description

We have included Spectrum Button component in our page, we observe that button text is not centered correctly in FireFox browser.

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Click on ...
3. Observe ...

## Expected behavior

Button text should align vertically across the browser.

## Screenshots

This screenshot from our request page shows difference in their alignment:
<img width="721" alt="RequestPage" src="https://user-images.githubusercontent.com/71743655/93958959-5195e380-fd75-11ea-9ceb-e1c5e117e0c8.png">

Same when open the storybook https://react-spectrum.corp.adobe.com/storybook/?path=/story/button--variant-cta  in chrome and Firebox, I could see very little difference their alignment:
<img width="622" alt="StoryBoard" src="https://user-images.githubusercontent.com/71743655/93958887-21e6db80-fd75-11ea-9653-f2e6dedb742d.png">

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**  Firefox

## Additional context

More information is available on react-spectrum issue:
https://git.corp.adobe.com/React/react-spectrum-v2/issues/618

**Comment by GarthDB** [comment]
@mopandit you're comparing Firefox to Chrome on MacOS?

**Comment by mopandit** [comment]
> @mopandit you're comparing Firefox to Chrome on MacOS?

@GarthDB  Yes. Both comparision is done btween chrome and fireFox on MacOS.
