### ISSUE TITLE
Accordion: Heading: Multi-line (long) headings overflow accordion content (line-height is off, height is fixed)

### ISSUE THREAD

**Issue by zbrownell** [adobe/spectrum-css#97]
### Expected Behavior

When headings for accordion items are longer than their container, they should flow to a new line, which is spaced in a manner that makes it visually distinct from other items in the accordion. Further, when a new line is wrapped, the heading needs to be able to adjust its own size to grow taller and encompass all of its content, otherwise, this content is rendered on top of any other content below it (if expanded, accordion item content; else, other accordion item headings)

### Actual Behavior

Accordion header wraps to new line, which is spaced in line with other items and overflows its parent container

#### Steps to Reproduce

1. Go to https://git.corp.adobe.com/pages/Coral/coral-spectrum/dist/playground
2. Create an accordion (or, copy/paste snippet; below)
3. Adjust one of the headings to be extremely long
4. Observe

Snippet that displays errant behavior:
```
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://git.corp.adobe.com/pages/Coral/coral-spectrum/dist/playground/dist/css/coral.css"/>
  <script src="https://git.corp.adobe.com/pages/Coral/coral-spectrum/dist/playground/dist/js/coral.js"></script>
  <script>window.addEventListener("message", function(e) {document.head.insertAdjacentHTML("beforeend", e.data)});</script>
  <!-- Load other libraries/frameworks e.g. via a CDN -->
</head>
<body class="coral--light">
      <coral-accordion>
        <coral-accordion-item selected="">
          <coral-accordion-item-label>First label, let's see how it handles very long text content and wrapping, now that the white-space: nowrap style declaration has been removed. Eh oh. Trouble.</coral-accordion-item-label>
          This is the first bit o'content
        </coral-accordion-item>
        <coral-accordion-item>
          <coral-accordion-item-label>Second</coral-accordion-item-label>
          This is the second bit o'content
        </coral-accordion-item>
        <coral-accordion-item>
          <coral-accordion-item-label>Third</coral-accordion-item-label>
          This is the third bit o'content
        </coral-accordion-item>
      </coral-accordion>
</body>
</html>

```

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)

Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Mac 10.14.2 (18C54)

...however, I believe this behavior will consistently reproduce across all browsers/platforms.

#### Spectrum-CSS version

I'm hoping that the documentation page uses the latest version, so 2.7.3?

#### Sample Code that illustrates the problem

See steps (above)

#### Screenshots (if applicable)

Accordion Item Expanded
<img width="1728" alt="screen shot 2019-02-13 at 11 41 32 am" src="https://user-images.githubusercontent.com/25671661/52727981-65b41500-2f84-11e9-885c-b76b7b42aa13.png">

Accordion Item Collapsed
<img width="1728" alt="screen shot 2019-02-13 at 11 41 42 am" src="https://user-images.githubusercontent.com/25671661/52727999-6fd61380-2f84-11e9-8e5f-5b26dcbd990a.png">

**Comment by zbrownell** [comment]
I fixed this issue in the Admin Console and wanted to suggest a similar change for Coral. We can solve this problem by removing the hard reliance on line-height to achieve vertical alignment of the accordion content. By moving a bit of top/bottom padding to each item and taking a bit of height away from the line-height, we achieve an exact recreation of the original list rendering, while allowing for headings to wrap to new lines (oh, we also have to change the `height` declaration to `auto` and move the current height value to a `min-height` property; which, will allow each heading to expand gracefully while not collapsing in the case of missing heading, etc).

These changes should do the trick:
```
._coral-Accordion-itemHeader {
    position: relative;
    box-sizing: border-box;
    padding: 8px 16px 8px 34px;
    margin: 0;
    height: auto;
    min-height: 39px;
    font-size: 11px;
    text-transform: uppercase;
    line-height: 23px;
    letter-spacing: 0.0006em;
    text-overflow: ellipsis;
    cursor: pointer;
    font-weight: 500;
}
```
...and, it ends up looking like this:

Accordion Item Expanded
<img width="1728" alt="screen shot 2019-02-13 at 11 53 01 am" src="https://user-images.githubusercontent.com/25671661/52728832-fdfec980-2f85-11e9-92b0-08a2ebf95538.png">

Accordion Item Collapsed
<img width="1728" alt="screen shot 2019-02-13 at 11 53 15 am" src="https://user-images.githubusercontent.com/25671661/52728851-0820c800-2f86-11e9-947c-485be949ead5.png">

**Comment by lazd** [comment]
@zbrownell thanks for the report! I'm checking with Design to see if this should truncate or wrap.

**Comment by lazd** [comment]
@NateBaldwinDesign weighed in and informed us that Accordion item titles should wrap, and should maintain a sensible top and bottom padding. I've went ahead and submitted a fix.
