### ISSUE TITLE
Slider: side labels

### ISSUE THREAD

**Issue by mischnic** [adobe/spectrum-css#970]
## Description

There should be a class for putting the label on the side of the slider: https://spectrum.adobe.com/page/slider/#Label-position

## Screenshots

This should be possible:

<img width="277" alt="Bildschirmfoto 2020-09-23 um 19 13 25" src="https://user-images.githubusercontent.com/4586894/94046348-dc57fc00-fdd0-11ea-9e2a-dd6bde9255db.png">

## Environment
 - **Spectrum CSS version:** 74000c8

## Additional context

Trying to upstream this to minimize changes in the CSS "fork" in the React Spectrum repo: https://github.com/adobe/react-spectrum/pull/1083

I've tried to implement this, though it's not perfect: https://reactspectrum.blob.core.windows.net/reactspectrum/797685ea11c15e51df80889902724c7a0073d78d/storybook/index.html?path=/story/slider--labelposition-side

CSS:

https://github.com/adobe/react-spectrum/blob/797685ea11c15e51df80889902724c7a0073d78d/packages/%40adobe/spectrum-css-temp/components/slider/skin.css#L308-L325

**Comment by pfulton** [comment]
@Deanna-w1 let's look at this one when we migrate and work on Slider.
