### ISSUE TITLE
Calendar component breaks inside a absolute positioned div [Edge only]

### ISSUE THREAD

**Issue by xitter** [adobe/spectrum-css#99]
### Expected Behavior
Calendar component should render correctly inside a absolute positioned div.

### Actual Behavior
Calendar component day title text overlaps the month header in edge.

#### Browser name/version/os (ie Chrome Version 62.0.3202.94 (Official Build) (64-bit) MacOS)
Edge

#### Spectrum-CSS version
2.7.4

#### Sample Code that illustrates the problem
```
<div style="position:absolute;top:10;left:10">
     // Calender Markup
</div>
```

#### Screenshots (if applicable)
<img width="581" alt="screen shot 2019-02-20 at 11 33 25 am" src="https://user-images.githubusercontent.com/8026722/53069995-c94dbd80-3503-11e9-8053-28249a01c65f.png">

**Comment by xitter** [comment]
I debugged this bug and found out that there's a problem in Edge with rendering a relative positioned table cell(**th** & **td**), which is being used in calendar to display the cells, i.e.

```
<th role="columnheader" scope="col" class="spectrum-Calendar-tableCell">       // position: relative
      <abbr class="spectrum-Calendar-dayOfWeek" title="Tuesday">Tu</abbr>      // position: absolute
</th>
```

There are two solutions to fix this issue(which I can think of):


1. Wrap content of cell within a relative div, i.e above layout changes to
```
<th role="columnheader" scope="col">
   <div class="spectrum-Calendar-tableCell">                                   // position: relative
      <abbr class="spectrum-Calendar-dayOfWeek" title="Tuesday">Tu</abbr>      // position: absolute
   </div>
</th>
```

2. Get rid of relative/absolute to position the cell content at bottom and use flex-box, i.e. 
```
 .spectrum-Calendar-tableCell {
     display: flex;
     align-items: flex-end;
 }
```

**Comment by lazd** [comment]
@xitter thanks for the report. I went ahead and fixed it by making `dayOfWeek` a flexbox and aligning the text to the bottom.
